/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

import caja.bo.ClienteBO;
import caja.bo.DocumentoPagoBO;
import caja.mapeo.entidades.Bbva;
import caja.mapeo.entidades.BbvaRetorno;
import caja.mapeo.entidades.Scotiabank;
import caja.mapeo.entidades.ScotiabankRetorno;
import caja.mapeo.entidades.Serie;
import caja.mapeo.entidades.TipoDocPago;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import units.DatePicker;

/**
 *
 * @author user
 */
public class dGeneracionComprobanteScotiabank extends javax.swing.JDialog {

    private ScotiabankRetorno scotiabankRetorno;
    private Scotiabank scotiabank;
    private Object frm;
    private int tipoCarga;

    /**
     * Creates new form dGeneracionComprobanteBbva
     */
    public dGeneracionComprobanteScotiabank(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Date ahora = new Date();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        txtFecha.setText(f.format(ahora));
        DocumentoPagoBO dpBO = DocumentoPagoBO.getInstance();
        List<TipoDocPago> lDocumentos = dpBO.ObtenerTodosTipoDocPago();
//        Object[] losValores = new Object[lDocumentos.size()];
        for (TipoDocPago td : lDocumentos) {
            cbTipoDocumento.addItem(td);
        }
        cbTipoDocumento.setSelectedIndex(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbTipoDocumento = new javax.swing.JComboBox();
        cbSerie = new javax.swing.JComboBox<>();
        txtNroComprobante = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("FECHA:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("TIPO DOCUMENTO:");

        txtFecha.setEditable(false);

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NRO SERIE:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("NRO:");

        cbTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoDocumentoActionPerformed(evt);
            }
        });

        cbSerie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0001", "0002", "0003", "0004", "0005", "0006", "0007", "0008", "0009", "0010" }));
        cbSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSerieActionPerformed(evt);
            }
        });

        txtNroComprobante.setEditable(false);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/ok_mediano.png"))); // NOI18N
        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/cancel_mediano.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbTipoDocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbSerie, 0, 198, Short.MAX_VALUE)
                                .addComponent(txtNroComprobante)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNroComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void CargarDatos(Object f, Scotiabank b, ScotiabankRetorno r, int tc) {
        this.frm = f;
        this.scotiabank = b;
        this.scotiabankRetorno = r;
        this.tipoCarga = tc;
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DatePicker dtp = new DatePicker(this);
        if (!dtp.setPickedDate().isEmpty()) {
            txtFecha.setText(dtp.setPickedDate());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ObtenerCorrelativo() {
        if (cbSerie.getSelectedItem() != null) {
            String serieActual = cbSerie.getSelectedItem().toString();
            DocumentoPagoBO dBO = DocumentoPagoBO.getInstance();
            List<TipoDocPago> lDocPago = dBO.ObtenerTodosTipoDocPago();
            TipoDocPago docPago = null;
            for (TipoDocPago dp : lDocPago) {
                if (dp.getNombreDocPago().equals(cbTipoDocumento.getSelectedItem().toString())) {
                    docPago = dp;
                    break;
                }
            }
            List<Serie> l = dBO.ObtenerTodasSeries_SegunTipoDocumento(docPago.getIdTipoDocPago());
            cbSerie.removeAllItems();
            for (Serie s : l) {
                cbSerie.addItem(s.getSerie());
            }
            cbSerie.setSelectedItem(serieActual);
//            TipoDocSerie tds = dBO.ObtenerTipoDocSerie(docPago.getIdTipoDocPago(), cbSerie.getSelectedItem().toString());
//            int nroCorrelativo = dBO.ObtenerSolamenteCorrelativo_Metodo2(tds.getId());
//            lbNroComprobanteTentativo.setText("NRO CMP: " + String.valueOf(nroCorrelativo));
//            if (docPago.getEsElectronico() != null) {
//                if (docPago.getEsElectronico().equals("S")) {
//                    txtNroCmp.setEnabled(false);
//                } else {
//                    txtNroCmp.setEnabled(true);
//                }
//            } else {
//                txtNroCmp.setEnabled(true);
//            }
        }
    }

    private void ObtenerUltimoNroComprobante() {
        if (cbSerie.getSelectedItem() != null) {
            DocumentoPagoBO dBO = DocumentoPagoBO.getInstance();
            int nro = dBO.ObtenerUltimoNroComprobante(((TipoDocPago) cbTipoDocumento.getSelectedItem()).getIdTipoDocPago(), cbSerie.getSelectedItem().toString());
            txtNroComprobante.setText(String.valueOf(nro + 1));
        }
    }


    private void cbTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoDocumentoActionPerformed
        this.ObtenerCorrelativo();
        this.ObtenerUltimoNroComprobante();
    }//GEN-LAST:event_cbTipoDocumentoActionPerformed

    private void cbSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSerieActionPerformed
        this.ObtenerCorrelativo();
        this.ObtenerUltimoNroComprobante();
    }//GEN-LAST:event_cbSerieActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void Generar() {
        try {
            DocumentoPagoBO dpBO = DocumentoPagoBO.getInstance();
            boolean estaCerrado = dpBO.EstaCerradoElDia(txtFecha.getText());
            if (estaCerrado) {
                JOptionPane.showMessageDialog(this,
                        "EL DÍA " + txtFecha.getText() + " ESTÁ CERRADO",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            Date fecha = f.parse(txtFecha.getText());
            //------------------------------------------------------------------
            ClienteBO cBO = ClienteBO.getInstance();
            cBO.GenerarComprobantePagoScotiabank(fecha, ((TipoDocPago) cbTipoDocumento.getSelectedItem()).getIdTipoDocPago(), cbSerie.getSelectedItem().toString(), this.scotiabankRetorno.getId());
            if (this.tipoCarga == 1) {
                ((frmScotiabankRetorno) this.frm).CargarDatos(this.scotiabank);
            }
            if (this.tipoCarga == 2) {
                ((frmScotiabankRetornoSubir) this.frm).CargarDatos(this.scotiabank);
            }
            this.dispose();
        } catch (ParseException ex) {
            Logger.getLogger(dGeneracionComprobanteScotiabank.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (this.scotiabankRetorno.getSeGeneroComprobantes() != null) {
            if (this.scotiabankRetorno.getId() != 0) {
                if (this.scotiabankRetorno.getSeGeneroComprobantes().equals("N")) {
                    this.Generar();
                } else {
                    JOptionPane.showMessageDialog(this, "NO SE PUEDE VOLVER A GENERAR LOS COMPROBANTES", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "PRIMERO DEBE SUBIR LA INFORMACIÓN", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            this.Generar();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dGeneracionComprobanteScotiabank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dGeneracionComprobanteScotiabank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dGeneracionComprobanteScotiabank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dGeneracionComprobanteScotiabank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dGeneracionComprobanteScotiabank dialog = new dGeneracionComprobanteScotiabank(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbSerie;
    private javax.swing.JComboBox cbTipoDocumento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNroComprobante;
    // End of variables declaration//GEN-END:variables
}
