/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

import caja.bo.ClienteBO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class dHistorialDetalladoContador extends javax.swing.JDialog {

    /**
     * Creates new form dHistorialDetalladoContador
     */
    public dHistorialDetalladoContador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private String ObtenerMes(int mes) {
        String pmes = "";
        if (mes == 1) {
            pmes = "ENE";
        }
        if (mes == 2) {
            pmes = "FEB";
        }
        if (mes == 3) {
            pmes = "MAR";
        }
        if (mes == 4) {
            pmes = "ABR";
        }
        if (mes == 5) {
            pmes = "MAY";
        }
        if (mes == 6) {
            pmes = "JUN";
        }
        if (mes == 7) {
            pmes = "JUL";
        }
        if (mes == 8) {
            pmes = "AGO";
        }
        if (mes == 9) {
            pmes = "SEP";
        }
        if (mes == 10) {
            pmes = "OCT";
        }
        if (mes == 11) {
            pmes = "NOV";
        }
        if (mes == 12) {
            pmes = "DIC";
        }
        return pmes;
    }

    public void CargarDatos(int idContador, String codigo, String nombre) {
        lbCodigo.setText(codigo);
        lbNombre.setText(nombre);
        ClienteBO cBO = ClienteBO.getInstance();
        List lPagos = cBO.ObtenerHistorialPagos(idContador);
        DefaultTableModel model = (DefaultTableModel) tDetalleHistorial.getModel();
        int mesDesde = 0;
        int mesHasta = 0;
        int anioDesde = 0;
        int anioHasta = 0;
        int contador = 0;
        double importe = 0;
        String rangoFecha = "";
        for (Object pobj : lPagos) {
            Object[] obj = (Object[]) pobj;
            importe = (int) obj[2] * (double) obj[3];
            importe = Math.round(importe * Math.pow(10, 2)) / Math.pow(10, 2);
            if (obj[4] != null) {
                anioDesde = (int) obj[4];
                mesDesde = (int) obj[5];
                anioHasta = (int) obj[6];
                mesHasta = (int) obj[7];
                rangoFecha = " " + ObtenerMes(mesDesde) + " " + String.valueOf(anioDesde);
                rangoFecha = rangoFecha + " A " + ObtenerMes(mesHasta) + " " + String.valueOf(anioHasta);
            }
            model.setNumRows(contador);
            model.addRow(new Object[contador]);
            tDetalleHistorial.setValueAt(contador + 1, contador, 0);
            tDetalleHistorial.setValueAt(obj[0], contador, 1);
            tDetalleHistorial.setValueAt((String) obj[1] + rangoFecha, contador, 2);
            tDetalleHistorial.setValueAt(importe, contador, 3);
            //tDetalleHistorial.setValueAt(c.getUniversidad(), contador, 4);
            contador = contador + 1;
            rangoFecha = "";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDetalleHistorial = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HISTORIAL DETALLE");

        jLabel1.setText("CODIGO:");

        lbCodigo.setText("jLabel2");

        jLabel3.setText("NOMBRE:");

        lbNombre.setText("jLabel2");

        tDetalleHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO", "FECHA", "DESCRIPCION", "IMPORTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tDetalleHistorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCodigo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNombre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dHistorialDetalladoContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dHistorialDetalladoContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dHistorialDetalladoContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dHistorialDetalladoContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dHistorialDetalladoContador dialog = new dHistorialDetalladoContador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JTable tDetalleHistorial;
    // End of variables declaration//GEN-END:variables
}
