/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

import caja.bo.CongresoBO;
import caja.mapeo.entidades.Congreso;
import caja.mapeo.entidades.CongresoParticipantes;
import caja.mapeo.entidades.DocumentoPagoDet;
import caja.mapeo.entidades.TipoDocIdentidad;
import java.util.List;

/**
 *
 * @author user
 */
public class dIncripcionCongresoIndividual extends javax.swing.JDialog {

    private frmComprobantePagoDetalle fDetalle;
    private DocumentoPagoDet detalle;

    /**
     * Creates new form dIncripcionCongreso
     */
    public dIncripcionCongresoIndividual(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbCongreso = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbTipoParticipante = new javax.swing.JComboBox();
        btnGuardar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreConcepto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CONGRESO:");

        jLabel2.setText("NOMBRE:");

        cbTipoParticipante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PARTICIPANTE", "ORDINARIO", "OBSERVADOR", "ACOMPAÑANTE", "ESTUDIANTE" }));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/Guardar2.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtNombre.setEditable(false);

        jLabel3.setText("CONCEPTO:");

        txtNombreConcepto.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre)
                    .addComponent(cbCongreso, 0, 534, Short.MAX_VALUE)
                    .addComponent(txtNombreConcepto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTipoParticipante, 0, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(btnGuardar)
                .addContainerGap(324, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbCongreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbTipoParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        CongresoParticipantes cp = new CongresoParticipantes();
        cp.setTipoDocIdentidad(new TipoDocIdentidad(1));
        cp.setNroDocIdentidad(this.detalle.getDocumentoPago().getCliente().getPnroDocumento());
        cp.setApePat(this.detalle.getDocumentoPago().getCliente().getPapePat());
        cp.setApeMat(this.detalle.getDocumentoPago().getCliente().getPapeMat());
        cp.setNombres(this.detalle.getDocumentoPago().getCliente().getPnombre());
        cp.setCliente(this.detalle.getDocumentoPago().getCliente());
        cp.setDocumentoPagoDet(this.detalle);
        cp.setCongreso((Congreso) cbCongreso.getSelectedItem());
        cp.setEntregoMaterial("N");
        if (cbTipoParticipante.getSelectedItem().equals("ORDINARIO")) {
            cp.setTipoParticipante(1);
        }
        if (cbTipoParticipante.getSelectedItem().equals("OBSERVADOR")) {
            cp.setTipoParticipante(2);
        }
        if (cbTipoParticipante.getSelectedItem().equals("ACOMPAÑANTE")) {
            cp.setTipoParticipante(3);
        }
        if (cbTipoParticipante.getSelectedItem().equals("ESTUDIANTE")) {
            cp.setTipoParticipante(4);
        }
        if (cbTipoParticipante.getSelectedItem().equals("PARTICIPANTE")) {
            cp.setTipoParticipante(5);
        }
        CongresoBO cBO = CongresoBO.getInstance();
        cBO.GuardarCongresoParticipantes(cp);
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    public void CargarDatos(frmComprobantePagoDetalle f, DocumentoPagoDet dpd, List<Congreso> lCongreso) {
        this.fDetalle = f;
        this.detalle = dpd;
        txtNombreConcepto.setText(dpd.getConceptoPagoDetalle().getDescripcion());
        txtNombre.setText(dpd.getDocumentoPago().getCliente().getPapePat() + " " + dpd.getDocumentoPago().getCliente().getPapeMat() + " " + dpd.getDocumentoPago().getCliente().getPnombre());
        for (Congreso c : lCongreso) {
            cbCongreso.addItem(c);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dIncripcionCongresoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dIncripcionCongresoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dIncripcionCongresoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dIncripcionCongresoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dIncripcionCongresoIndividual dialog = new dIncripcionCongresoIndividual(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbCongreso;
    private javax.swing.JComboBox cbTipoParticipante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreConcepto;
    // End of variables declaration//GEN-END:variables
}
