/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

import caja.bo.CongresoBO;
import caja.mapeo.entidades.Congreso;
import caja.mapeo.entidades.CongresoParticipantes;
import caja.mapeo.entidades.DocumentoPagoDet;
import caja.mapeo.entidades.TipoDocIdentidad;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author user
 */
public class dIncripcionCongreso extends javax.swing.JDialog {

    private frmComprobantePagoDetalle fDetalle;
    private DocumentoPagoDet detalle;

    /**
     * Creates new form dIncripcionCongreso
     */
    public dIncripcionCongreso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        TableColumn columna = tDetalle.getColumn("NRO");
        columna.setPreferredWidth(40);
        columna.setMinWidth(40);
        columna.setMaxWidth(40);
        columna = tDetalle.getColumn("PARTICIPANTEOBJ");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
    }

    public void CargarDatos(frmComprobantePagoDetalle f, DocumentoPagoDet dpd, List<Congreso> lCongreso) {
        this.fDetalle = f;
        this.detalle = dpd;
        txtNombreConcepto.setText(dpd.getConceptoPagoDetalle().getDescripcion());
//        txtNombre.setText(dpd.getDocumentoPago().getCliente().getPapePat() + " " + dpd.getDocumentoPago().getCliente().getPapeMat() + " " + dpd.getDocumentoPago().getCliente().getPnombre());
        for (Congreso c : lCongreso) {
            cbCongreso.addItem(c);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbCongreso = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDetalle = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApePat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApeMat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        cbTipoParticipante = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNombreConcepto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CONGRESO:");

        tDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO", "DNI", "APE PAT", "APE MAT", "NOMBRES", "TIPO", "PARTICIPANTEOBJ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tDetalle);

        jLabel2.setText("DNI:");

        jLabel3.setText("APE PAT:");

        txtApePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApePatKeyReleased(evt);
            }
        });

        jLabel4.setText("APE MAT:");

        txtApeMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApeMatKeyReleased(evt);
            }
        });

        jLabel5.setText("NOMBRES:");

        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombresKeyReleased(evt);
            }
        });

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        cbTipoParticipante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PARTICIPANTE", "ORDINARIO", "OBSERVADOR", "ACOMPAÑANTE", "ESTUDIANTE" }));

        jLabel6.setText("TIPO:");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/Guardar2.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel7.setText("CONCEPTO:");

        txtNombreConcepto.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtDni))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbCongreso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(txtApePat, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(txtApeMat, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(cbTipoParticipante, 0, 115, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAgregar))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(txtNombreConcepto)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNombreConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbCongreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApePat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApeMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar)
                    .addComponent(cbTipoParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (!txtDni.getText().isEmpty() && !txtApePat.getText().isEmpty() && !txtApeMat.getText().isEmpty() && !txtNombres.getText().isEmpty()) {
            DefaultTableModel modelDetalle = (DefaultTableModel) tDetalle.getModel();
            if (modelDetalle.getRowCount() > this.detalle.getCantidad()) {
                JOptionPane.showMessageDialog(this,
                        "NO PUEDE HABER MAS DE " + this.detalle.getCantidad() + " PARTICIPANTES",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            }
            CongresoParticipantes cp = new CongresoParticipantes();
            cp.setTipoDocIdentidad(new TipoDocIdentidad(1));
            cp.setNroDocIdentidad(txtDni.getText());
            cp.setApePat(txtApePat.getText());
            cp.setApeMat(txtApeMat.getText());
            cp.setNombres(txtNombres.getText());
            cp.setCongreso((Congreso) cbCongreso.getSelectedItem());
            cp.setDocumentoPagoDet(this.detalle);
            cp.setEntregoMaterial("N");
            if (cbTipoParticipante.getSelectedItem().equals("ORDINARIO")) {
                cp.setTipoParticipante(1);
            }
            if (cbTipoParticipante.getSelectedItem().equals("OBSERVADOR")) {
                cp.setTipoParticipante(2);
            }
            if (cbTipoParticipante.getSelectedItem().equals("ACOMPAÑANTE")) {
                cp.setTipoParticipante(3);
            }
            if (cbTipoParticipante.getSelectedItem().equals("ESTUDIANTE")) {
                cp.setTipoParticipante(4);
            }
            if (cbTipoParticipante.getSelectedItem().equals("PARTICIPANTE")) {
                cp.setTipoParticipante(5);
            }
            int numFilas = modelDetalle.getRowCount();
            modelDetalle.setNumRows(numFilas);
            modelDetalle.addRow(new Object[numFilas]);
            tDetalle.setValueAt(numFilas + 1, numFilas, 0);
            tDetalle.setValueAt(cp.getNroDocIdentidad(), numFilas, 1);
            tDetalle.setValueAt(cp.getApePat(), numFilas, 2);
            tDetalle.setValueAt(cp.getApeMat(), numFilas, 3);
            tDetalle.setValueAt(cp.getNombres(), numFilas, 4);
            if (cp.getTipoParticipante() == 1) {
                tDetalle.setValueAt("ORDINARIO", numFilas, 5);
            }
            if (cp.getTipoParticipante() == 2) {
                tDetalle.setValueAt("OBSERVADOR", numFilas, 5);
            }
            if (cp.getTipoParticipante() == 3) {
                tDetalle.setValueAt("ACOMPAÑANTE", numFilas, 5);
            }
            if (cp.getTipoParticipante() == 4) {
                tDetalle.setValueAt("ESTUDIANTE", numFilas, 5);
            }
            if (cp.getTipoParticipante() == 5) {
                tDetalle.setValueAt("PARTICIPANTE", numFilas, 5);
            }
            tDetalle.setValueAt(cp.getTipoParticipante(), numFilas, 5);
            tDetalle.setValueAt(cp, numFilas, 6);
            
            txtDni.setText("");
            txtApePat.setText("");
            txtApeMat.setText("");
            txtNombres.setText("");
        } else {
            JOptionPane.showMessageDialog(this,
                    "DEBE LLENAR TODOS LOS CAMPOS",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        CongresoBO cBO = CongresoBO.getInstance();
//        cBO.GuardarCongresoParticipantes(cp);

        DefaultTableModel modelDetalle = (DefaultTableModel) tDetalle.getModel();
        int numFilas = modelDetalle.getRowCount();
        if (numFilas > 0) {
            for (int i = 0; i < numFilas; i++) {
                CongresoParticipantes cp = (CongresoParticipantes) modelDetalle.getValueAt(i, 6);
                boolean seGuardo = cBO.GuardarCongresoParticipantes(cp);
                if (!seGuardo) {
                    JOptionPane.showMessageDialog(this,
                            "NO SE GUARDO EL DETALLE",
                            "ERROR",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                } else {
                    JOptionPane.showMessageDialog(this,
                            "SE GUARDÓ LOS DATOS",
                            "OK",
                            JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "DEBE INGRESAR DETALLE AL COMPROBANTE",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtApePatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApePatKeyReleased
        txtApePat.setText(txtApePat.getText().toUpperCase());
    }//GEN-LAST:event_txtApePatKeyReleased

    private void txtApeMatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeMatKeyReleased
        txtApeMat.setText(txtApeMat.getText().toUpperCase());
    }//GEN-LAST:event_txtApeMatKeyReleased

    private void txtNombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyReleased
        txtNombres.setText(txtNombres.getText().toUpperCase());
    }//GEN-LAST:event_txtNombresKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dIncripcionCongreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dIncripcionCongreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dIncripcionCongreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dIncripcionCongreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dIncripcionCongreso dialog = new dIncripcionCongreso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbCongreso;
    private javax.swing.JComboBox cbTipoParticipante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tDetalle;
    private javax.swing.JTextField txtApeMat;
    private javax.swing.JTextField txtApePat;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombreConcepto;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
