/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

import caja.bo.DocumentoPagoBO;
import caja.bo.SeguridadBO;
import caja.mapeo.entidades.DocumentoPago;
import caja.mapeo.entidades.Operacion;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
//import javax.swing.table.TableColumn;
import units.DatePicker;

/**
 *
 * @author user
 */
public class dIngresarOperacion extends javax.swing.JDialog {

    private frmComprobantePagoCabecera fComprobante;
    private DocumentoPago documentoPago;

    /**
     * Creates new form dIngresarOperacion
     */
    public dIngresarOperacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        SeguridadBO sBO = SeguridadBO.getInstance();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        txtFecha.setText(format.format(sBO.ObtenerFechaServidor()));
        txtMoneda.setText("SOLES - CONGRESO");
        TableColumn columna = tOperacion.getColumn("FCH");
        columna.setPreferredWidth(70);
        columna.setMinWidth(70);
        columna.setMaxWidth(70);
        columna = tOperacion.getColumn("NRO");
        columna.setPreferredWidth(70);
        columna.setMinWidth(70);
        columna.setMaxWidth(70);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNroOperacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnFecha = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbCuenta = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtMoneda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tOperacion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DATOS OPERACIÓN");

        jLabel1.setText("NRO:");

        txtNroOperacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroOperacionKeyTyped(evt);
            }
        });

        jLabel2.setText("FECHA:");

        txtFecha.setEditable(false);

        btnFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/calendario.png"))); // NOI18N
        btnFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/Guardar2.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/cancel_mediano.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("N CTA:");

        cbCuenta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "001102200100070967" }));
        cbCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCuentaActionPerformed(evt);
            }
        });

        jLabel4.setText("MONE:");

        txtMoneda.setEditable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/add_mini.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tOperacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FCH", "CTA", "NRO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tOperacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tOperacionKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tOperacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMoneda)
                            .addComponent(cbCuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNroOperacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(btnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNroOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void CargarDatos(frmComprobantePagoCabecera f, DocumentoPago dp) {
        this.fComprobante = f;
        this.documentoPago = dp;
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        if (dp.getFechaOperacion() != null) {
            txtFecha.setText(format.format(dp.getFechaOperacion()));
        }
        if (dp.getNroOperacion() != null) {
            txtNroOperacion.setText(dp.getNroOperacion());
        }
    }


    private void btnFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaActionPerformed
        DatePicker dtp = new DatePicker(this);
        if (!dtp.setPickedDate().isEmpty()) {
            txtFecha.setText(dtp.setPickedDate());
        }
    }//GEN-LAST:event_btnFechaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        try {
            DocumentoPagoBO dBO = DocumentoPagoBO.getInstance();
//                String nroOperacion = txtNroOperacion.getText().trim();
//                String nroCuenta = cbCuenta.getSelectedItem().toString();
            List<Operacion> l = new ArrayList();
            DefaultTableModel m = (DefaultTableModel) tOperacion.getModel();
            for (int i = 0; i < m.getRowCount(); i++) {
                String fechaOperacion = tOperacion.getValueAt(i, 0).toString();
                String nroCuenta = tOperacion.getValueAt(i, 1).toString();
                String nroOperacion = tOperacion.getValueAt(i, 2).toString();
                Operacion operacion = dBO.verificarExisteNroOperacion(nroCuenta, nroOperacion);
                if (operacion != null) {
                    JOptionPane.showMessageDialog(this,
                            "LA OPERACION YA ESTA REGISTRADA CON EL COMPROBANTE " + operacion.getDocumentoPago().getTipoDocSerie().getTipoDocPago().getNombreDocPago() + " " + operacion.getDocumentoPago().getTipoDocSerie().getSerie().getSerie() + "-" + operacion.getDocumentoPago().getNroDocumentoPago() + "\n NOMBRE CLIENTE:" + operacion.getDocumentoPago().getNombreCliente(),
                            "ERROR",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
                Operacion nuevaOperacion = new Operacion();
                nuevaOperacion.setFechaOperacion(f.parse(fechaOperacion));
                nuevaOperacion.setNroCuenta(nroCuenta);
                nuevaOperacion.setNroOperacion(nroOperacion);
                l.add(nuevaOperacion);
            }
            this.fComprobante.agregarNroOperacionFecha(l);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this,
                    "OCURRIO UN ERROR CON LA FECHA",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
        dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNroOperacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroOperacionKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
//            if (c != '.') {
            getToolkit().beep();
            evt.consume();
//            }
        }
//        char c = evt.getKeyChar();
//        if (c == ' ') {
//            getToolkit().beep();
//            evt.consume();
//        }
    }//GEN-LAST:event_txtNroOperacionKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCuentaActionPerformed
        if (cbCuenta.getSelectedItem().equals("00110220010012731411")) {
            txtMoneda.setText("SOLES - CONGRESO");
        }
        if (cbCuenta.getSelectedItem().equals("00110220010012732214")) {
            txtMoneda.setText("DOLARES - CONGRESO");
        }
        if (cbCuenta.getSelectedItem().equals("00110220010007096713")) {
            txtMoneda.setText("SOLES");
        }
        if (cbCuenta.getSelectedItem().equals("00002897002100004003")) {
            txtMoneda.setText("SOLES");
        }
    }//GEN-LAST:event_cbCuentaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtNroOperacion.setText(txtNroOperacion.getText().trim());
        if (!txtNroOperacion.getText().isEmpty() && !txtFecha.getText().isEmpty()) {
            for (int i = 0; i < tOperacion.getRowCount(); i++) {
                String nroCuenta = tOperacion.getValueAt(i, 1).toString();
                String nroOperacion = tOperacion.getValueAt(i, 2).toString();
                if (cbCuenta.getSelectedItem().toString().equals(nroCuenta) && txtNroOperacion.getText().equals(nroOperacion)) {
                    JOptionPane.showMessageDialog(this,
                            "EL NRO DE OPERACION YA EXISTE",
                            "ERROR",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            DefaultTableModel modelDetalle = (DefaultTableModel) tOperacion.getModel();
            int numFilas = modelDetalle.getRowCount();
            modelDetalle.setNumRows(numFilas);
            modelDetalle.addRow(new Object[numFilas]);
//        SimpleDateFormat f = new SimpleDateFormat();
            tOperacion.setValueAt(txtFecha.getText(), numFilas, 0);
            tOperacion.setValueAt(cbCuenta.getSelectedItem().toString(), numFilas, 1);
            tOperacion.setValueAt(txtNroOperacion.getText(), numFilas, 2);
        } else {
            JOptionPane.showMessageDialog(this,
                    "DEBE LLENAR EL NRO DE OPERACION",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tOperacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tOperacionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            int fila = tOperacion.getSelectedRow();
            if (fila > -1) {
                DefaultTableModel m = (DefaultTableModel) tOperacion.getModel();
                m.removeRow(fila);
            }
        }
    }//GEN-LAST:event_tOperacionKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dIngresarOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dIngresarOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dIngresarOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dIngresarOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dIngresarOperacion dialog = new dIngresarOperacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFecha;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbCuenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tOperacion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMoneda;
    private javax.swing.JTextField txtNroOperacion;
    // End of variables declaration//GEN-END:variables
}
