/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

//import caja.bo.AnioMesBO;
import caja.bo.ClienteBO;
import caja.bo.SeguridadBO;
//import caja.mapeo.entidades.AnioMes;
import caja.mapeo.entidades.BbvaRetorno;
import caja.mapeo.entidades.ScotiabankRetorno;
//import caja.mapeo.entidades.BbvaRetornoDetalle;
//import caja.mapeo.entidades.Cliente;
import java.awt.Desktop;
//import java.io.BufferedReader;
import java.io.File;
//import java.io.FileInputStream;
//import java.io.FileNotFoundException;
import java.io.FileOutputStream;
//import java.io.FileReader;
//import java.io.IOException;
//import java.text.ParseException;
//import java.text.SimpleDateFormat;
//import java.util.ArrayList;
//import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
//import javax.swing.filechooser.FileNameExtensionFilter;
//import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class dScotiabankOpciones extends javax.swing.JDialog {

    private Object frm;
    private int tipoCarga;
    private ScotiabankRetorno scotiabankRetorno;

    /**
     * Creates new form dOpcionesBbva
     */
    public dScotiabankOpciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSeleccionarArchivo = new javax.swing.JButton();
        btnSubirArchivo = new javax.swing.JButton();
        btnGenerarComprobantes = new javax.swing.JButton();
        btnImprimirComprobantes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSeleccionarArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/buscar5.png"))); // NOI18N
        btnSeleccionarArchivo.setText("SELECCIÓN ARCHIVO");
        btnSeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarArchivoActionPerformed(evt);
            }
        });

        btnSubirArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/subir_archivo.png"))); // NOI18N
        btnSubirArchivo.setText("SUBIR ARCHIVO");
        btnSubirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirArchivoActionPerformed(evt);
            }
        });

        btnGenerarComprobantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/generar.png"))); // NOI18N
        btnGenerarComprobantes.setText("GENERAR COMPROBANTES");
        btnGenerarComprobantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarComprobantesActionPerformed(evt);
            }
        });

        btnImprimirComprobantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/impresora_mini.png"))); // NOI18N
        btnImprimirComprobantes.setText("IMPRIMIR COMPROBANTES");
        btnImprimirComprobantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirComprobantesActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/txt_mini.png"))); // NOI18N
        jButton1.setText("VER ARCHIVO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSeleccionarArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubirArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenerarComprobantes, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(btnImprimirComprobantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSeleccionarArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubirArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarComprobantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimirComprobantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void CargarDatos(Object f, int tc, ScotiabankRetorno br) {
        this.frm = f;
        this.tipoCarga = tc;
        this.scotiabankRetorno = br;
        if (tc == 1) {
            btnSubirArchivo.setEnabled(true);
            btnSeleccionarArchivo.setEnabled(true);
            if (br != null) {
                if (br.getSeSubioArchivo() != null) {
                    if (br.getSeSubioArchivo().equals("S")) {
                        btnSeleccionarArchivo.setEnabled(false);
                        btnSubirArchivo.setEnabled(false);
                    }
                }
            }
        }
        if (tc == 2) {
            btnSeleccionarArchivo.setEnabled(false);
            btnSubirArchivo.setEnabled(false);
        }
    }

    private void CargarArchivo() {
        try {
            JFileChooser file = new JFileChooser();
            file.showOpenDialog(this);
            File abre = file.getSelectedFile();
            if (this.tipoCarga == 1) {
                ((frmScotiabankRetornoSubir) this.frm).CargarArchivo(abre);
                int resp = JOptionPane.showConfirmDialog(null, "¿DESEA SUBIR EL ARCHIVO?", "PREGUNTA", JOptionPane.YES_NO_OPTION);
                if (resp == 0) {
                    ((frmScotiabankRetornoSubir) this.frm).SubirArchivo();
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex + ""
                    + "\nNo se ha encontrado el archivo",
                    "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
        }
    }


    private void btnSeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarArchivoActionPerformed
        this.CargarArchivo();
        this.dispose();
    }//GEN-LAST:event_btnSeleccionarArchivoActionPerformed

    private void btnSubirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirArchivoActionPerformed
        if (this.tipoCarga == 1) {
            ((frmScotiabankRetornoSubir) this.frm).SubirArchivo();
        }
        this.dispose();
    }//GEN-LAST:event_btnSubirArchivoActionPerformed

    private void btnGenerarComprobantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarComprobantesActionPerformed
        SeguridadBO sBO = SeguridadBO.getInstance();
        ScotiabankRetorno br = (ScotiabankRetorno) sBO.CargarObjeto("ScotiabankRetorno", this.scotiabankRetorno.getId());
        if (br.getSeGeneroComprobantes()!= null) {
            if (br.getSeGeneroComprobantes().equals("S")) {
                JOptionPane.showMessageDialog(this, "YA SE GENERÓ COMPROBANTES DE PAGO", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "YA SE GENERÓ COMPROBANTES DE PAGO", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (this.tipoCarga == 1) {
            ((frmScotiabankRetornoSubir) this.frm).GenerarComprobante();
        }
        if (this.tipoCarga == 2) {
            ((frmScotiabankRetorno) this.frm).GenerarComprobante();
        }
        this.dispose();
    }//GEN-LAST:event_btnGenerarComprobantesActionPerformed

    private void btnImprimirComprobantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirComprobantesActionPerformed
        ClienteBO cBO = ClienteBO.getInstance();
        cBO.ImprimirDocumentoPago_SegunScotiabank(this.scotiabankRetorno.getId());
    }//GEN-LAST:event_btnImprimirComprobantesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (this.scotiabankRetorno != null) {
                if (this.scotiabankRetorno.getArchivo() != null) {
                    String[] options = new String[]{"DESCARGAR", "CANCELAR"};
                    int response = JOptionPane.showOptionDialog(null, "OPCIONES", "SELECCIONAR OPCIÓN",
                            JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                            null, options, options[0]);
                    if (response == 0) {
                        byte contenido[] = this.scotiabankRetorno.getArchivo();
                        if (Desktop.isDesktopSupported()) {
                            if (contenido != null) {
                                FileOutputStream fileOuputStream = new FileOutputStream(this.scotiabankRetorno.getNombreArchivo());
                                fileOuputStream.write(contenido);
                                fileOuputStream.close();
                                File archivo = new File(this.scotiabankRetorno.getNombreArchivo());
                                //fileOuputStream.
                                Desktop.getDesktop().open(archivo);
                            } else {
                                JOptionPane.showMessageDialog(this,
                                        "NO HAY ARCHIVO PDF ASOCIADO A ESTE OPERACIÓN",
                                        "ERROR",
                                        JOptionPane.ERROR_MESSAGE);
                            }
                        }
                    } else {
                        return;
                    }
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex + ""
                    + "\nNo se ha encontrado el archivo",
                    "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dScotiabankOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dScotiabankOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dScotiabankOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dScotiabankOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dScotiabankOpciones dialog = new dScotiabankOpciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarComprobantes;
    private javax.swing.JButton btnImprimirComprobantes;
    private javax.swing.JButton btnSeleccionarArchivo;
    private javax.swing.JButton btnSubirArchivo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
