/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

import caja.bo.AnioMesBO;
import caja.bo.ClienteBO;
import caja.frm.frmPrincipal;
//import caja.frm.frmPrincipal;
import caja.mapeo.entidades.AnioMes;
import caja.mapeo.entidades.Bbva;
import caja.mapeo.entidades.BbvaRetorno;
//import caja.mapeo.entidades.BbvaRetornoDetalle;
//import caja.mapeo.entidades.BbvaContador;
//import java.awt.Desktop;
//import java.io.BufferedWriter;
import java.io.File;
//import java.io.FileWriter;
//import java.io.IOException;
//import java.io.PrintWriter;
//import java.text.SimpleDateFormat;
//import java.util.Calendar;
//import java.util.Date;
import java.util.List;
//import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
//import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Date;
import javax.swing.JFileChooser;

/**
 *
 * @author user
 */
public class frmBBVARetorno extends javax.swing.JInternalFrame {

//    private int nroOperacion = 0;
    private Bbva bbva = null;
    private BbvaRetorno bbvaRetornoSeleccionado = null;
    private List<BbvaRetorno> lista = null;
    private List lCobranza = null;

    /**
     * Creates new form frmBBVA
     */
    public frmBBVARetorno() {
        initComponents();
        tDetalle.setAutoResizeMode(tDetalle.AUTO_RESIZE_OFF);
        TableColumn columna = tRetorno.getColumn("NRO");
        columna.setPreferredWidth(40);
        columna.setMinWidth(40);
        columna.setMaxWidth(40);
        columna = tRetorno.getColumn("OBJ");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna = tDetalle.getColumn("NRO");
        columna.setPreferredWidth(40);
        columna.setMinWidth(40);
        columna.setMaxWidth(40);
        columna = tDetalle.getColumn("NOMBRE");
        columna.setPreferredWidth(200);
        columna.setMinWidth(200);
        columna.setMaxWidth(200);
        columna = tDetalle.getColumn("REFERENCIA");
        columna.setPreferredWidth(140);
        columna.setMinWidth(140);
        columna.setMaxWidth(140);
        columna = tDetalle.getColumn("I. ORIGEN");
        columna.setPreferredWidth(70);
        columna.setMinWidth(70);
        columna.setMaxWidth(70);
        columna = tDetalle.getColumn("I. DEPOSITO");
        columna.setPreferredWidth(70);
        columna.setMinWidth(70);
        columna.setMaxWidth(70);
        columna = tDetalle.getColumn("I. MORA");
        columna.setPreferredWidth(70);
        columna.setMinWidth(70);
        columna.setMaxWidth(70);
        columna = tDetalle.getColumn("DOC");
        columna.setPreferredWidth(200);
        columna.setMinWidth(200);
        columna.setMaxWidth(200);
        columna = tDetalle.getColumn("OBJ");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
//        columna = tContador.getColumn("COD");
//        columna.setPreferredWidth(80);
//        columna.setMinWidth(80);
//        columna.setMaxWidth(80);
//        columna = tContador.getColumn("OBJ");
//        columna.setPreferredWidth(0);
//        columna.setMinWidth(0);
//        columna.setMaxWidth(0);
//        columna = tDetalle.getColumn("NRO");
//        columna.setPreferredWidth(40);
//        columna.setMinWidth(40);
//        columna.setMaxWidth(40);
//        columna = tDetalle.getColumn("MONTO");
//        columna.setPreferredWidth(70);
//        columna.setMinWidth(70);
//        columna.setMaxWidth(70);
//        columna = tDetalle.getColumn("CODIGO");
//        columna.setPreferredWidth(70);
//        columna.setMinWidth(70);
//        columna.setMaxWidth(70);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tRetorno = new javax.swing.JTable();
        lbUbicacion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tDetalle = new javax.swing.JTable();
        txtFiltroNombre = new javax.swing.JTextField();
        txtFiltroNombre.addKeyListener(
            new KeyAdapter(){
                public void keyReleased (KeyEvent e){
                    FiltrarContadorNombre();
                }} );
                jButton3 = new javax.swing.JButton();

                setClosable(true);
                setTitle("BBVA");
                setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/icono.png"))); // NOI18N
                setPreferredSize(new java.awt.Dimension(900, 600));

                tRetorno.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "NRO", "RUC", "COD. CLASE", "T. MONEDA", "F. PROCESO", "C. RECAU.", "T. REGIS.", "T. PAGOS", "T. DEPOSI", "OBJ"
                    }
                ) {
                    boolean[] canEdit = new boolean [] {
                        false, false, false, false, false, false, false, false, false, false
                    };

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
                tRetorno.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        tRetornoMouseClicked(evt);
                    }
                });
                jScrollPane1.setViewportView(tRetorno);

                lbUbicacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                lbUbicacion.setText("DATOS:");

                tDetalle.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "NRO", "NOMBRE", "REFERENCIA", "I. ORIGEN", "I. DEPOSITO", "I. MORA", "OFI. PAGO", "NRO. MOV", "FEC. PAGO", "T. VALOR", "C. ENTRADA", "OBJ", "DOC"
                    }
                ) {
                    boolean[] canEdit = new boolean [] {
                        false, false, false, false, false, false, false, false, false, false, false, false, false
                    };

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
                tDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        tDetalleMouseClicked(evt);
                    }
                });
                jScrollPane2.setViewportView(tDetalle);

                jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/opciones.png"))); // NOI18N
                jButton3.setText("OPCIONES");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton3ActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFiltroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbUbicacion)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                        .addContainerGap())
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void tRetornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tRetornoMouseClicked
        if (evt.getClickCount() == 2) {
            int fila = tRetorno.getSelectedRow();
            if (fila >= 0) {
                DefaultTableModel model = (DefaultTableModel) tRetorno.getModel();
//                DefaultTableModel m = (DefaultTableModel) tDetalle.getModel();
                BbvaRetorno br = (BbvaRetorno) model.getValueAt(fila, 9);
                this.bbvaRetornoSeleccionado = br;
                ClienteBO cBO = ClienteBO.getInstance();
                lCobranza = cBO.ObtenerBbvaRetornoDetalle(br.getId());
                DefaultTableModel m = (DefaultTableModel) tDetalle.getModel();
                m.setRowCount(0);
                int contador = 0;
                for (Object p : lCobranza) {
                    Object[] o = (Object[]) p;
                    String nombre = (String) o[0];
                    String referencia = (String) o[1];
                    double iOrigen = (double) o[2];
                    double iDeposito = (double) o[3];
                    double iMora = (double) o[4];
                    int oficinaPago = (int) o[5];
                    int nroMovimiento = (int) o[6];
                    Date fechaPago = (Date) o[7];
                    int tipoValor = (int) o[8];
                    int canalEntrada = (int) o[9];
                    String documentoPago = "";
                    if (o[10] != null) {
                        documentoPago = (String) o[10];
                    }
                    m.addRow(new Object[contador]);
                    tDetalle.setValueAt(contador + 1, contador, 0);
                    tDetalle.setValueAt(nombre, contador, 1);
                    tDetalle.setValueAt(referencia, contador, 2);
                    tDetalle.setValueAt(iOrigen, contador, 3);
                    tDetalle.setValueAt(iDeposito, contador, 4);
                    tDetalle.setValueAt(iMora, contador, 5);
                    tDetalle.setValueAt(oficinaPago, contador, 6);
                    tDetalle.setValueAt(nroMovimiento, contador, 7);
                    tDetalle.setValueAt(fechaPago, contador, 8);
                    tDetalle.setValueAt(tipoValor, contador, 9);
                    tDetalle.setValueAt(canalEntrada, contador, 10);
                    tDetalle.setValueAt(canalEntrada, contador, 11);
                    tDetalle.setValueAt(documentoPago, contador, 12);
                    contador = contador + 1;
                }

            }
        }
    }//GEN-LAST:event_tRetornoMouseClicked

    public void GenerarComprobante() {
        frmPrincipal f = (frmPrincipal) this.getParent().getParent().getParent().getParent().getParent();
        if (this.bbvaRetornoSeleccionado != null) {
            if (this.bbvaRetornoSeleccionado.getSeGeneroComprobantes() != null) {
                if (this.bbvaRetornoSeleccionado.getSeGeneroComprobantes().equals("N")) {
                    f.AbrirFormularioGenerarOperacionBbva(this, this.bbva, this.bbvaRetornoSeleccionado, 1);
                } else {
                    JOptionPane.showMessageDialog(this, "NO SE PUEDE VOLVER A GENERAR LOS COMPROBANTES", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                f.AbrirFormularioGenerarOperacionBbva(this, this.bbva, this.bbvaRetornoSeleccionado, 1);
            }
        } else {
            JOptionPane.showMessageDialog(this, "DEBE ELEGIR UN ITEM RETORNO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (this.bbvaRetornoSeleccionado != null) {
            frmPrincipal fPrin = (frmPrincipal) this.getParent().getParent().getParent().getParent().getParent();
            fPrin.AbrirFormularioBbvaOpciones(this, 2, this.bbvaRetornoSeleccionado);
        } else {
            JOptionPane.showMessageDialog(this, "DEBE ELEGIR UN ITEM DE RETORNO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDetalleMouseClicked
//        if (evt.getClickCount() == 2) {
//            int fila = tDetalle.getSelectedRow();
//            if (fila >= 0) {
//                int idDocumentoPagoDet = tDetalle.getValueAt(fila, 11);
//            }
//        }
    }//GEN-LAST:event_tDetalleMouseClicked

    public void CargarDatos(Bbva b) {
        this.bbva = b;
        ClienteBO cBO = ClienteBO.getInstance();
//        Bbva b = cBO.ObtenerBbva(this.nroOperacion);
        lbUbicacion.setText("NRO OP: " + b.getNroOperacion() + " | FECHA OP: " + b.getFechaOperacion() + " | TIPO IDENTIFICACION: " + b.getTipoIdentificacion());
        this.lista = cBO.ObtenerBbvaRetorno_SegunIdBbva(b.getId());
        DefaultTableModel model = (DefaultTableModel) tRetorno.getModel();
        model.setNumRows(0);
        int contador = 0;
        for (BbvaRetorno c : lista) {
//            Object[] o = (Object[]) c;
//            String cod = (String) o[0];
//            String apePat = (String) o[1];
//            String apeMat = (String) o[2];
//            String nombre = (String) o[3];
//            int id = (int) o[4];
            model.addRow(new Object[contador]);
            tRetorno.setValueAt(contador + 1, contador, 0);
            tRetorno.setValueAt(c.getRuc(), contador, 1);
            tRetorno.setValueAt(c.getCodigoClase(), contador, 2);
            tRetorno.setValueAt(c.getMoneda(), contador, 3);
            tRetorno.setValueAt(c.getFecha(), contador, 4);
            tRetorno.setValueAt(c.getCuentaRecaudadora(), contador, 5);
            tRetorno.setValueAt(c.getTotalRegistros(), contador, 6);
            tRetorno.setValueAt(c.getTotalPagos(), contador, 7);
            tRetorno.setValueAt(c.getTotalDepositos(), contador, 8);
            tRetorno.setValueAt(c, contador, 9);
            contador = contador + 1;
        }
        model = (DefaultTableModel) tDetalle.getModel();
        model.setRowCount(0);
        this.bbvaRetornoSeleccionado = null;
    }

    public void GenerarOperacionBbva(int aDesde, int aHasta, int mDesde, int mHasta) {
        Thread queryThread = new Thread() {
            public void run() {
                ClienteBO cBO = ClienteBO.getInstance();
                String[] Movimientos = {"Carga Parcial", "Carga Total", "Eliminacion de Registros"};
                String TipoMovimiento = (String) JOptionPane.showInputDialog(null,
                        "Cual es el tipo de Movimiento?",
                        "Elegir",
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        Movimientos,
                        Movimientos[0]);
                if (TipoMovimiento.equals("Carga Parcial")) {
                    TipoMovimiento = "P";
                } else {
                    if (TipoMovimiento.equals("Carga Total")) {
                        TipoMovimiento = "T";
                    } else {
                        TipoMovimiento = "E";
                    }
                }
                AnioMesBO amBO = AnioMesBO.getInstance();
                AnioMes amDesde = amBO.ObtenerAnioMes(aDesde, mDesde);
                AnioMes amHasta = amBO.ObtenerAnioMes(aHasta, mHasta);
//                cBO.GenerarEstructuraDatosCobranzaInstitucional_BBVA(jProgressBar1, TipoMovimiento, amDesde.getNroOrden(), amHasta.getNroOrden(), TipoMovimiento);
            }
        };
        queryThread.start();
    }

    private void FiltrarContadorNombre() {
        if (this.lCobranza != null) {
            String pFiltro = txtFiltroNombre.getText();
            pFiltro = pFiltro.toUpperCase();
            txtFiltroNombre.setText(pFiltro);
            DefaultTableModel m = (DefaultTableModel) tDetalle.getModel();
            m.setNumRows(0);
            int contador = 0;
            for (Object p : this.lCobranza) {
                Object[] o = (Object[]) p;
                String nombre = (String) o[0];
                String referencia = (String) o[1];
                double iOrigen = (double) o[2];
                double iDeposito = (double) o[3];
                double iMora = (double) o[4];
                int oficinaPago = (int) o[5];
                int nroMovimiento = (int) o[6];
                Date fechaPago = (Date) o[7];
                int tipoValor = (int) o[8];
                int canalEntrada = (int) o[9];
                String documentoPago = "";
                if (o[10] != null) {
                    documentoPago = (String) o[10];
                }
                String nombreCompleto = nombre;
                if (nombreCompleto.contains(pFiltro)) {
                    m.addRow(new Object[contador]);
                    tDetalle.setValueAt(contador + 1, contador, 0);
                    tDetalle.setValueAt(nombre, contador, 1);
                    tDetalle.setValueAt(referencia, contador, 2);
                    tDetalle.setValueAt(iOrigen, contador, 3);
                    tDetalle.setValueAt(iDeposito, contador, 4);
                    tDetalle.setValueAt(iMora, contador, 5);
                    tDetalle.setValueAt(oficinaPago, contador, 6);
                    tDetalle.setValueAt(nroMovimiento, contador, 7);
                    tDetalle.setValueAt(fechaPago, contador, 8);
                    tDetalle.setValueAt(tipoValor, contador, 9);
                    tDetalle.setValueAt(canalEntrada, contador, 10);
                    tDetalle.setValueAt(documentoPago, contador, 12);
                    contador = contador + 1;
                }
            }
        }
    }

    private void LeerRegistro(File abre, String registro) throws FileNotFoundException, IOException {
//        String tipoRegistro = registro.substring(0, 2);
//        if (tipoRegistro.equals("01")) {
//            DefaultTableModel modelDetalle = (DefaultTableModel) tRetorno.getModel();
//            int contador = modelDetalle.getRowCount();
//            String ruc = registro.substring(3, 13);
//            String codigClase = registro.substring(14, 16);
//            String tipoMoneda = registro.substring(17, 19);
//            String fechaProceso = registro.substring(20, 27);
//            String cuentaRecaudadora = registro.substring(28, 45);
//
//            BbvaRetorno c = new BbvaRetorno();
//            FileInputStream ficheroStream = new FileInputStream(abre);
//            byte contenido[] = new byte[(int) abre.length()];
//            ficheroStream.read(contenido);
//            c.setArchivo(contenido);
//            c.setNombreArchivo(abre.getName());
////            cBO.GuardarBbvaRetorno(c);
//
//            modelDetalle.setNumRows(modelDetalle.getRowCount() + 1);
//            modelDetalle.addRow(new Object[contador]);
//            tRetorno.setValueAt(contador, contador, 0);
//            tRetorno.setValueAt(ruc, contador, 1);
//            tRetorno.setValueAt(codigClase, contador, 2);
//            tRetorno.setValueAt(tipoMoneda, contador, 3);
//            tRetorno.setValueAt(fechaProceso, contador, 4);
//            tRetorno.setValueAt(cuentaRecaudadora, contador, 5);
//            tRetorno.setValueAt(c, contador, 11);
//            this.bbvaRetorno = c;
//        }
//        if (tipoRegistro.equals("02")) {
//            DefaultTableModel modelDetalle = (DefaultTableModel) tDetalle.getModel();
//            int contador = modelDetalle.getRowCount();
//            String nombre = registro.substring(2, 32);
//            String referencia = registro.substring(32, 80);
//            String importeOrigen = registro.substring(80, 95);
//            double iOrigen = Double.valueOf(importeOrigen) / 100;
//            iOrigen = Math.round(iOrigen * Math.pow(10, 2)) / Math.pow(10, 2);
//            String importeDestino = registro.substring(95, 110);
//            double iDestino = Double.valueOf(importeDestino) / 100;
//            iDestino = Math.round(iDestino * Math.pow(10, 2)) / Math.pow(10, 2);
//            String importeMora = registro.substring(110, 125);
//            double iMora = Double.valueOf(importeMora) / 100;
//            iMora = Math.round(iMora * Math.pow(10, 2)) / Math.pow(10, 2);
//            String oficinaPago = registro.substring(125, 129);
//            String nroMovimiento = registro.substring(129, 135);
//            String fechaPago = registro.substring(135, 143);
//            String tipoValor = registro.substring(143, 145);
//            String canalEntrada = registro.substring(145, 147);
//
//            BbvaRetornoDetalle r = new BbvaRetornoDetalle();
//            r.setNombre(nombre);
//            r.setReferencia(referencia);
//            r.setCanalEntrada(Integer.valueOf(canalEntrada));
//            r.setImporteOrigen(iOrigen);
//            r.setImporteDeposito(iDestino);
//            r.setNroMovimiento(Integer.valueOf(nroMovimiento));
//            r.setOficinaPago(Integer.valueOf(oficinaPago));
//            r.setTipoValor(Integer.valueOf(tipoValor));
//
//            modelDetalle.addRow(new Object[contador]);
//            tDetalle.setValueAt(contador + 1, contador, 0);
//            tDetalle.setValueAt(nombre, contador, 1);
//            tDetalle.setValueAt(referencia, contador, 2);
//            tDetalle.setValueAt(iOrigen, contador, 3);
//            tDetalle.setValueAt(iDestino, contador, 4);
//            tDetalle.setValueAt(iMora, contador, 5);
//            tDetalle.setValueAt(oficinaPago, contador, 6);
//            tDetalle.setValueAt(nroMovimiento, contador, 7);
//            tDetalle.setValueAt(fechaPago, contador, 8);
//            tDetalle.setValueAt(tipoValor, contador, 9);
//            tDetalle.setValueAt(canalEntrada, contador, 10);
//            tDetalle.setValueAt(r, contador, 11);
//        }
//        if (tipoRegistro.equals("03")) {
//            DefaultTableModel modelDetalle = (DefaultTableModel) tRetorno.getModel();
//            int contador = modelDetalle.getRowCount();
//            String totalRegistros = registro.substring(3, 11);
//            String totalPagos = registro.substring(12, 26);
//            String totalDeposito = registro.substring(27, 41);
//            modelDetalle.setNumRows(modelDetalle.getRowCount() + 1);
//            modelDetalle.addRow(new Object[contador]);
//            tRetorno.setValueAt(totalRegistros, contador, 6);
//            tRetorno.setValueAt(totalPagos, contador, 7);
//            tRetorno.setValueAt(totalDeposito, contador, 8);
//        }
    }

    private void CargarArchivo() {
        try {
//            CsvReader reader = null;
            JFileChooser file = new JFileChooser();
            file.showOpenDialog(this);
            File abre = file.getSelectedFile();
            DefaultTableModel modelDetalle = (DefaultTableModel) tDetalle.getModel();
            modelDetalle.setRowCount(0);
            if (abre != null) {
                if (abre.getName().endsWith(".txt") || abre.getName().endsWith(".TXT")) {
                    lbUbicacion.setText(abre.toString());
                    String cadena;
                    FileReader f = new FileReader(abre.toString());
                    BufferedReader b = new BufferedReader(f);
                    while ((cadena = b.readLine()) != null) {
                        this.LeerRegistro(abre, cadena);
                    }
                    b.close();
                } else {
                    JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR ARCHIVOS CON EXTENSION .PDF");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex + ""
                    + "\nNo se ha encontrado el archivo",
                    "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
        }
    }

    private String RellenarEspacionBlanco(String cadena, int cant) {
        int contador = cadena.length();
        while (contador < cant) {
            cadena = cadena + " ";
            contador++;
        }
        return cadena;
    }

    private String RellenarCeros(String cadena, int cant) {
        int contador = 0;
        while (contador < cant) {
            cadena = cadena + "0";
            contador++;
        }
        return cadena;
    }

    private String ObtenerMes(int mes) {
        String m = "";
        if (mes == 1) {
            m = "ENE";
        }
        if (mes == 2) {
            m = "FEB";
        }
        if (mes == 3) {
            m = "MAR";
        }
        if (mes == 4) {
            m = "ABR";
        }
        if (mes == 5) {
            m = "MAY";
        }
        if (mes == 6) {
            m = "JUN";
        }
        if (mes == 7) {
            m = "JUL";
        }
        if (mes == 8) {
            m = "AGO";
        }
        if (mes == 9) {
            m = "SEP";
        }
        if (mes == 10) {
            m = "OCT";
        }
        if (mes == 11) {
            m = "NOV";
        }
        if (mes == 12) {
            m = "DIC";
        }
        return m;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbUbicacion;
    private javax.swing.JTable tDetalle;
    private javax.swing.JTable tRetorno;
    private javax.swing.JTextField txtFiltroNombre;
    // End of variables declaration//GEN-END:variables
}
