/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

import caja.bo.FinanciamientoBO;
import caja.mapeo.entidades.Financiamiento;
import caja.frm.frmPrincipal;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author user
 */
public class frmFinanciamientos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmFinanciamientos
     */
    public frmFinanciamientos() {
        initComponents();

        TableColumn columna = tFinanciamiento.getColumn("NRO");
        columna.setPreferredWidth(40);
        columna.setMinWidth(40);
        columna.setMaxWidth(40);
        columna = tFinanciamiento.getColumn("COD");
        columna.setPreferredWidth(50);
        columna.setMinWidth(50);
        columna.setMaxWidth(50);
        columna = tFinanciamiento.getColumn("1ER PAGO");
        columna.setPreferredWidth(70);
        columna.setMinWidth(70);
        columna.setMaxWidth(70);
        columna = tFinanciamiento.getColumn("N. CUOTA");
        columna.setPreferredWidth(70);
        columna.setMinWidth(70);
        columna.setMaxWidth(70);
        columna = tFinanciamiento.getColumn("MONTO");
        columna.setPreferredWidth(50);
        columna.setMinWidth(50);
        columna.setMaxWidth(50);
        columna = tFinanciamiento.getColumn("NOMBRE");
        columna.setPreferredWidth(250);
        columna.setMinWidth(250);
        columna.setMaxWidth(250);
        columna = tFinanciamiento.getColumn("IDFINANCIAMIENTO");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);

        columna = tDetalleFinanciamiento.getColumn("NRO");
        columna.setPreferredWidth(40);
        columna.setMinWidth(40);
        columna.setMaxWidth(40);
        columna = tDetalleFinanciamiento.getColumn("MONTO");
        columna.setPreferredWidth(50);
        columna.setMinWidth(50);
        columna.setMaxWidth(50);
        columna = tDetalleFinanciamiento.getColumn("CUOTA");
        columna.setPreferredWidth(50);
        columna.setMinWidth(50);
        columna.setMaxWidth(50);

        FinanciamientoBO fBO = FinanciamientoBO.getInstance();
        DefaultTableModel model = (DefaultTableModel) tFinanciamiento.getModel();
        List<Financiamiento> lFinanciamiento = fBO.ObtenerTodosFinanciamientosTodosContadores();
        model.setNumRows(0);
        int contador = 0;
        for (Financiamiento f : lFinanciamiento) {
            model.setNumRows(contador);
            model.addRow(new Object[contador]);
            tFinanciamiento.setValueAt(contador + 1, contador, 0);
            tFinanciamiento.setValueAt(f.getCliente().getCcodigoCole(), contador, 1);
            tFinanciamiento.setValueAt(f.getCliente().getPapePat() + " " + f.getCliente().getPapeMat() + " " + f.getCliente().getPnombre(), contador, 2);
            tFinanciamiento.setValueAt(f.getPrimerPago(), contador, 3);
            tFinanciamiento.setValueAt(f.getNroCuotas(), contador, 4);
            tFinanciamiento.setValueAt(f.getMontoCadaCuota(), contador, 5);
            tFinanciamiento.setValueAt(f.getAnioDesde() + " " + this.ObtenerMes(f.getMesDesde()), contador, 6);
            tFinanciamiento.setValueAt(f.getAnioHasta() + " " + this.ObtenerMes(f.getMesHasta()), contador, 7);
            tFinanciamiento.setValueAt(f.getIdFinanciamiento(), contador, 8);
            contador = contador + 1;
        }

        /*model = (DefaultTableModel) tDetalle.getModel();
         model.setNumRows(0);*/
    }

    private String ObtenerMes(int mes) {
        String pmes = "";
        if (mes == 1) {
            pmes = "ENERO";
        }
        if (mes == 2) {
            pmes = "FEBRERO";
        }
        if (mes == 3) {
            pmes = "MARZO";
        }
        if (mes == 4) {
            pmes = "ABRIL";
        }
        if (mes == 5) {
            pmes = "MAYO";
        }
        if (mes == 6) {
            pmes = "JUNIO";
        }
        if (mes == 7) {
            pmes = "JULIO";
        }
        if (mes == 8) {
            pmes = "AGOSTO";
        }
        if (mes == 9) {
            pmes = "SEPTIEMBRE";
        }
        if (mes == 10) {
            pmes = "OCTUBRE";
        }
        if (mes == 11) {
            pmes = "NOVIEMBRE";
        }
        if (mes == 12) {
            pmes = "DICIEMBRE";
        }
        return pmes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tFinanciamiento = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tDetalleFinanciamiento = new javax.swing.JTable();

        setClosable(true);
        setTitle("LISTADO FINANCIAMIENTOS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/icono.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(756, 622));

        jLabel1.setText("CODIGO:");

        jLabel2.setText("NOMBRE:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("CODIGO:");

        lbCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCodigo.setForeground(new java.awt.Color(0, 102, 204));
        lbCodigo.setText("0000");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("NOMBRE:");

        lbNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(0, 102, 204));
        lbNombre.setText("----");

        tFinanciamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO", "COD", "NOMBRE", "1ER PAGO", "N. CUOTA", "MONTO", "DESDE", "HASTA", "IDFINANCIAMIENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tFinanciamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tFinanciamientoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tFinanciamiento);

        tDetalleFinanciamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO", "ESTADO", "CUOTA", "MONTO", "DOC PAGO", "SERIE", "NRO DOC", "FCH DOC", "FCH VEN", "D. PRORR."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tDetalleFinanciamiento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNombre)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbCodigo)
                    .addComponent(jLabel4)
                    .addComponent(lbNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void CargarDetalleFinanciamientos() {
        FinanciamientoBO fBO = FinanciamientoBO.getInstance();
        int fila = tFinanciamiento.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tFinanciamiento.getModel();
        String codigo = String.valueOf(model.getValueAt(fila, 1));
        String nombre = String.valueOf(model.getValueAt(fila, 2));
        lbCodigo.setText(codigo);
        lbNombre.setText(nombre);
        String idFinanciamiento = String.valueOf(model.getValueAt(fila, 8));
        List<Object> lDetalleFinanciamiento = fBO.ObtenerDetalleFinanciamiento(Integer.valueOf(idFinanciamiento));
        model = (DefaultTableModel) tDetalleFinanciamiento.getModel();
        model.setNumRows(0);
        int contador = 0;
        for (Object pobj : lDetalleFinanciamiento) {
            Object[] obj = (Object[]) pobj;
            model.setNumRows(contador);
            model.addRow(new Object[contador]);
            tDetalleFinanciamiento.setValueAt(contador + 1, contador, 0);
            if (((String) obj[0]).equals("CI")) {
                tDetalleFinanciamiento.setValueAt("CUOTA INICIAL", contador, 1);
            }
            if (((String) obj[0]).equals("FC")) {
                tDetalleFinanciamiento.setValueAt("F. CANCELADO", contador, 1);
            }
            if (((String) obj[0]).equals("FS")) {
                tDetalleFinanciamiento.setValueAt("F. PENDIENTE PAGO", contador, 1);
            }
            if (((String) obj[0]).equals("FR")) {
                tDetalleFinanciamiento.setValueAt("REINCORPORACIÓN", contador, 1);
            }
            tDetalleFinanciamiento.setValueAt(obj[1], contador, 2);
            tDetalleFinanciamiento.setValueAt(obj[2], contador, 3);
            tDetalleFinanciamiento.setValueAt(obj[3], contador, 4);
            tDetalleFinanciamiento.setValueAt(obj[4], contador, 5);
            tDetalleFinanciamiento.setValueAt(obj[5], contador, 6);
            tDetalleFinanciamiento.setValueAt(obj[6], contador, 7);
            tDetalleFinanciamiento.setValueAt(obj[7], contador, 8);
            tDetalleFinanciamiento.setValueAt(obj[8], contador, 9);
            contador = contador + 1;
        }
    }


    private void tFinanciamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tFinanciamientoMouseClicked
        if (evt.getClickCount() == 2) {
            frmPrincipal fPrin = (frmPrincipal) this.getParent().getParent().getParent().getParent().getParent();
            Thread queryThread = new Thread() {
                public void run() {
                    frmCargando fCargando = new frmCargando();
                    fPrin.AgregarFormulario(fCargando);
                    int x = (fPrin.getWidth() - fCargando.getWidth()) / 2;
                    int y = (fPrin.getHeight() - fCargando.getHeight()) / 2;
                    fCargando.setLocation(x, y);
                    fCargando.setVisible(true);
                    fCargando.toFront();
                    CargarDetalleFinanciamientos();
                    fCargando.dispose();
                }
            };
            queryThread.start();
        }
    }//GEN-LAST:event_tFinanciamientoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JTable tDetalleFinanciamiento;
    private javax.swing.JTable tFinanciamiento;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
