/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

//import caja.bo.ClienteBO;
import caja.bo.DocumentoPagoBO;
import caja.bo.SeguridadBO;
import caja.bo.SociedadBO;
//import caja.mapeo.entidades.Cliente;
import caja.mapeo.entidades.DocumentoPago;
import caja.frm.frmPrincipal;
import caja.mapeo.entidades.Cliente;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author juan carlos
 */
public class frmMovimientosSociedad extends javax.swing.JInternalFrame {

    private Cliente cliente;
//    private Object tReportePersona;

    /**
     * Creates new form frmMovimientosSociedad
     */
    public frmMovimientosSociedad() {
        initComponents();
        TableColumn columna = tReporteSociedades.getColumn("NRO");
        columna.setPreferredWidth(10);
        columna = tReporteSociedades.getColumn("ID");
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna.setPreferredWidth(0);
        columna = tReporteSociedades.getColumn("NOMBRE");
        columna.setPreferredWidth(300);
        columna = tReporteSociedades.getColumn("MATRICULA");
        columna.setPreferredWidth(40);
        txtNombreSociedad.setEditable(false);
        txtNumero.setEditable(false);
        String Nombre = "";
        txtNombreSociedad.setText(Nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMovimientosSociedad = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNombreSociedad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        cbFiltro = new javax.swing.JComboBox();
        btnBuscarSociedad = new javax.swing.JButton();
        pbSociedades = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tReporteSociedades = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Movimientos de Sociedades"));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Movimientos de Sociedades");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/icono.png"))); // NOI18N

        btnMovimientosSociedad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMovimientosSociedad.setText("GENERAR REPORTE");
        btnMovimientosSociedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientosSociedadActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre Sociedad:");

        jLabel4.setText("Búsqueda:");

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "POR NOMBRE", "POR RUC", "POR CODIGO" }));

        btnBuscarSociedad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/buscar_mini1.png"))); // NOI18N
        btnBuscarSociedad.setText("BUSCAR");
        btnBuscarSociedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSociedadActionPerformed(evt);
            }
        });

        tReporteSociedades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NRO", "NOMBRE", "MATRICULA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tReporteSociedades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tReporteSociedadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tReporteSociedades);

        jLabel5.setText("Codigo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMovimientosSociedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscarSociedad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNombreSociedad, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 145, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pbSociedades, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarSociedad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbSociedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombreSociedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMovimientosSociedad)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarContador() {

        txtNombreSociedad.setEditable(false);
        txtNumero.setEditable(false);

        btnMovimientosSociedad.setEnabled(false);

        int tipoBusqueda = 0;
        if (cbFiltro.getSelectedItem() == "POR CODIGO") {
            tipoBusqueda = 1;
        } else if (cbFiltro.getSelectedItem() == "POR RUC") {
            tipoBusqueda = 2;
        } else if (cbFiltro.getSelectedItem() == "POR NOMBRE") {
            tipoBusqueda = 3;
        }

        SociedadBO s = SociedadBO.getInstance();
        List<Cliente> l = s.BuscarSociedad(txtBusqueda.getText(), tipoBusqueda);
        DefaultTableModel modelo = (DefaultTableModel) tReporteSociedades.getModel();
        modelo = (DefaultTableModel) tReporteSociedades.getModel();
        modelo.setRowCount(l.size());
        int contador = 0;
        for (Cliente docPago : l) {
            modelo.setNumRows(contador);
            modelo.addRow(new Object[contador]);
            tReporteSociedades.setValueAt(docPago.getIdCliente(), contador, 0);
            tReporteSociedades.setValueAt(contador + 1, contador, 1);
            tReporteSociedades.setValueAt(docPago.getSnombreSociedad(), contador, 2);
            tReporteSociedades.setValueAt(docPago.getScodigoSoc(), contador, 3);
            contador++;
        }
    }

    public void ImprimirMovimientosSociedades() {
        try {
            if (this.cliente != null) {
                String jdbcDriver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
                Class.forName(jdbcDriver);
                SeguridadBO sBO = SeguridadBO.getInstance();
                String url = sBO.getUrlReporte();
                String user = "sa";
                String pass = "4dm1n1str4c10nGOB90570";
                Connection con = DriverManager.getConnection(url, user, pass);
                String fullPath = "";
                Map param;
                fullPath = "reportes/Historial_Sociedades.jasper";
                param = new HashMap();
                param.put("IDCLIENTE", this.cliente.getIdCliente());
                param.put("RUC", this.cliente.getSruc());
                param.put("Codigo", this.cliente.getSnombreSociedad());
                param.put("Nombre_Sociedad", txtNombreSociedad.getText());
                param.put("REPORT_LOCALE", new Locale("en", "EN"));
                JasperPrint JPrint = JasperFillManager.fillReport(fullPath, param, con);
                JasperViewer.viewReport(JPrint, false);
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }


    private void btnMovimientosSociedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientosSociedadActionPerformed
        frmPrincipal fPrin = (frmPrincipal) this.getParent().getParent().getParent().getParent().getParent();
        Thread queryThread = new Thread() {
            public void run() {
                frmCargando fCargando = new frmCargando();
                fPrin.AgregarFormulario(fCargando);
                int x = (fPrin.getWidth() - fCargando.getWidth()) / 2;
                int y = (fPrin.getHeight() - fCargando.getHeight()) / 2;
                fCargando.setLocation(x, y);
                fCargando.setVisible(true);
                fCargando.toFront();
                ImprimirMovimientosSociedades();
                fCargando.dispose();
            }
        };
        queryThread.start();
    }//GEN-LAST:event_btnMovimientosSociedadActionPerformed

    private void btnBuscarSociedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSociedadActionPerformed
        Thread queryThread = new Thread() {
            public void run() {
                pbSociedades.setIndeterminate(true);
                pbSociedades.setStringPainted(true);
                pbSociedades.setString("BUSCANDO SOCIEDADES, POR FAVOR ESPERE");
                pbSociedades.setValue(100);
                pbSociedades.repaint();
                buscarContador();
                pbSociedades.setString("BUSQUEDA FINALIZADA");
                pbSociedades.setStringPainted(false);
                pbSociedades.setIndeterminate(false);
            }
        };
        queryThread.start();
    }//GEN-LAST:event_btnBuscarSociedadActionPerformed

    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        if (evt.getKeyCode() == 10) {
            this.buscarContador();
        }
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void tReporteSociedadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tReporteSociedadesMouseClicked
        if (evt.getClickCount() == 2) {
            int fila = tReporteSociedades.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tReporteSociedades.getModel();
            int idCliente = Integer.valueOf(model.getValueAt(fila, 0).toString());
            SeguridadBO sBO = SeguridadBO.getINSTANCE();
            Cliente cli = (Cliente) sBO.CargarObjeto("Cliente", idCliente);
            this.cliente = cli;
            txtNombreSociedad.setText(cli.getSnombreSociedad());
            txtNumero.setText(cli.getScodigoSoc());
            txtNombreSociedad.setEditable(true);
            txtNumero.setEditable(true);
            btnMovimientosSociedad.setEnabled(true);
        }
    }//GEN-LAST:event_tReporteSociedadesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarSociedad;
    private javax.swing.JButton btnMovimientosSociedad;
    private javax.swing.JComboBox cbFiltro;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar pbSociedades;
    private javax.swing.JTable tReporteSociedades;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtNombreSociedad;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
