/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

import caja.bo.ClienteBO;
import caja.bo.DocumentoPagoBO;
import caja.bo.EmpresaBO;
import caja.bo.SeguridadBO;
import caja.mapeo.entidades.Cliente;
import caja.mapeo.entidades.DocumentoPago;
import caja.frm.frmPrincipal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author juan carlos
 */
public class frmMovimientosEmpresa extends javax.swing.JInternalFrame {

    private Cliente cliente;

    /**
     * Creates new form frmMovimientosEmpresa
     */
    public frmMovimientosEmpresa() {
        initComponents();
        TableColumn columna = tReporteEmpresas.getColumn("NRO");
        columna.setPreferredWidth(10);
        columna = tReporteEmpresas.getColumn("ID");
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna.setPreferredWidth(0);
        columna = tReporteEmpresas.getColumn("NOMBRE");
        columna.setPreferredWidth(300);
        columna = tReporteEmpresas.getColumn("RUC");
        columna.setPreferredWidth(40);
        txtNombreEmpresa.setEditable(false);
        txtNumero.setEditable(false);
        String Nombre = "";
        txtNombreEmpresa.setText(Nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMovimientosEmpresa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNombreEmpresa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        cbFiltro = new javax.swing.JComboBox();
        btnBuscar = new javax.swing.JButton();
        pbEmpresas = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tReporteEmpresas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Movimientos de Empresas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/icono.png"))); // NOI18N

        btnMovimientosEmpresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMovimientosEmpresa.setText("GENERAR REPORTE");
        btnMovimientosEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientosEmpresaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Empresa:");

        jLabel3.setText("BÚSQUEDA:");

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "POR NOMBRE", "POR RUC" }));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/buscar_mini1.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tReporteEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NRO", "NOMBRE", "RUC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tReporteEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tReporteEmpresasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tReporteEmpresas);

        jLabel4.setText("Ruc:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMovimientosEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(pbEmpresas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMovimientosEmpresa)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarContador() {

        txtNombreEmpresa.setEditable(false);
        txtNumero.setEditable(false);

        btnMovimientosEmpresa.setEnabled(false);

        int tipoBusqueda = 0;
        if (cbFiltro.getSelectedItem() == "POR RUC") {
            tipoBusqueda = 1;
        } else if (cbFiltro.getSelectedItem() == "POR NOMBRE") {
            tipoBusqueda = 2;
        }

        EmpresaBO e = EmpresaBO.getInstance();
        List<Cliente> l = e.BuscarEmpresa(txtBusqueda.getText(), tipoBusqueda);
        DefaultTableModel modelo = (DefaultTableModel) tReporteEmpresas.getModel();
        modelo = (DefaultTableModel) tReporteEmpresas.getModel();
        modelo.setRowCount(l.size());
        int contador = 0;
        for (Cliente docPago : l) {
            modelo.setNumRows(contador);
            modelo.addRow(new Object[contador]);
            tReporteEmpresas.setValueAt(docPago.getIdCliente(), contador, 0);
            tReporteEmpresas.setValueAt(contador + 1, contador, 1);
            tReporteEmpresas.setValueAt(docPago.getEnombre(), contador, 2);
            tReporteEmpresas.setValueAt(docPago.getEruc(), contador, 3);
            contador++;
        }
    }

    public void ImprimirMovimientosEmpresas() {
        try {
            if (this.cliente != null) {
                String jdbcDriver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
                Class.forName(jdbcDriver);
                SeguridadBO sBO = SeguridadBO.getInstance();
                String url = sBO.getUrlReporte();
                String user = "sa";
                String pass = "4dm1n1str4c10nGOB90570";
                Connection con = DriverManager.getConnection(url, user, pass);
                String fullPath = "";
                Map param;
                fullPath = "reportes/Historial_Empresas.jasper";
                param = new HashMap();
                String rucEmpresa = "";
//                rucEmpresa = txtEmpresa.getText();
                String nombreEmpresa = "";
                nombreEmpresa = txtNombreEmpresa.getText();
                param.put("IDCLIENTE", this.cliente.getIdCliente());
                param.put("RUC", rucEmpresa);
                param.put("Nombre_Empresa", nombreEmpresa);
                param.put("REPORT_LOCALE", new Locale("en", "EN"));
                JasperPrint JPrint = JasperFillManager.fillReport(fullPath, param, con);
                JasperViewer.viewReport(JPrint, false);
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }


    private void btnMovimientosEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientosEmpresaActionPerformed
        frmPrincipal fPrin = (frmPrincipal) this.getParent().getParent().getParent().getParent().getParent();
        Thread queryThread = new Thread() {
            public void run() {
                frmCargando fCargando = new frmCargando();
                fPrin.AgregarFormulario(fCargando);
                int x = (fPrin.getWidth() - fCargando.getWidth()) / 2;
                int y = (fPrin.getHeight() - fCargando.getHeight()) / 2;
                fCargando.setLocation(x, y);
                fCargando.setVisible(true);
                fCargando.toFront();
                ImprimirMovimientosEmpresas();
                fCargando.dispose();
            }
        };
        queryThread.start();
    }//GEN-LAST:event_btnMovimientosEmpresaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Thread queryThread = new Thread() {
            public void run() {
                pbEmpresas.setIndeterminate(true);
                pbEmpresas.setStringPainted(true);
                pbEmpresas.setString("BUSCANDO EMPRESAS, POR FAVOR ESPERE");
                pbEmpresas.setValue(100);
                pbEmpresas.repaint();
                buscarContador();
                pbEmpresas.setString("BUSQUEDA FINALIZADA");
                pbEmpresas.setStringPainted(false);
                pbEmpresas.setIndeterminate(false);
            }
        };
        queryThread.start();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        if (evt.getKeyCode() == 10) {
            this.buscarContador();
        }
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void tReporteEmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tReporteEmpresasMouseClicked
        if (evt.getClickCount() == 2) {
            int fila = tReporteEmpresas.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tReporteEmpresas.getModel();
            int idCliente = Integer.valueOf(model.getValueAt(fila, 0).toString());
            SeguridadBO sBO = SeguridadBO.getINSTANCE();
            Cliente cli = (Cliente) sBO.CargarObjeto("Cliente", idCliente);
            this.cliente = cli;
            txtNombreEmpresa.setText(cli.getEnombre());
            txtNumero.setText(cli.getEruc());
            txtNombreEmpresa.setEditable(true);
            txtNumero.setEditable(true);
            btnMovimientosEmpresa.setEnabled(true);
        }
    }//GEN-LAST:event_tReporteEmpresasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMovimientosEmpresa;
    private javax.swing.JComboBox cbFiltro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar pbEmpresas;
    private javax.swing.JTable tReporteEmpresas;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
