/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

//import caja.bo.ClienteBO;
//import caja.bo.ClienteBO;
import caja.bo.ContadorBO;
import caja.bo.DocumentoPagoBO;
import caja.bo.SeguridadBO;
//import caja.entidades.Cliente;
import caja.mapeo.entidades.DocumentoPago;
import caja.frm.frmPrincipal;
import caja.mapeo.entidades.Cliente;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author juan carlos
 */
public class frmMovimientosContador extends javax.swing.JInternalFrame {

    private Cliente cliente;

    /**
     * Creates new form frmMovimientosContador
     */
    public frmMovimientosContador() {
        initComponents();

        TableColumn columna = tReporteContador.getColumn("NRO");
        columna.setPreferredWidth(10);
        columna = tReporteContador.getColumn("ID");
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna.setPreferredWidth(0);
        columna = tReporteContador.getColumn("NOMBRE");
        columna.setPreferredWidth(300);
        columna = tReporteContador.getColumn("MATRICULA");
        columna.setPreferredWidth(40);

        DocumentoPagoBO docBO = DocumentoPagoBO.getInstance();

        txtNombre.setEditable(false);
        txtNumero.setEditable(false);

        String Codigo = "";
//        txtCodigo.setText(Codigo);

        String Nombre = "";
        txtNombre.setText(Nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMovimientosContador = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        cbFiltro = new javax.swing.JComboBox();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tReporteContador = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        pbContador = new javax.swing.JProgressBar();

        jLabel1.setText("jLabel1");

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Movimientos del Contador");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/icono.png"))); // NOI18N

        btnMovimientosContador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMovimientosContador.setText("GENERAR REPORTE");
        btnMovimientosContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientosContadorActionPerformed(evt);
            }
        });

        jLabel3.setText("NOMBRE:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel4.setText("BÚSQUEDA:");

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "POR NOMBRE", "POR CODIGO" }));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/buscar_mini1.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tReporteContador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NRO", "NOMBRE", "MATRICULA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tReporteContador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tReporteContadorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tReporteContador);

        jLabel5.setText("NÚMERO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMovimientosContador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pbContador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMovimientosContador)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Movimienos del Contador");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarContador() {
        txtNombre.setEditable(false);
        txtNumero.setEditable(false);
        btnMovimientosContador.setEnabled(false);
        int tipoBusqueda = 0;
        if (cbFiltro.getSelectedItem() == "POR NOMBRE") {
            tipoBusqueda = 4;
        } else if (cbFiltro.getSelectedItem() == "POR CODIGO") {
            tipoBusqueda = 2;
        }
        ContadorBO doc = ContadorBO.getInstance();
        List<Cliente> l = doc.BuscarContador(txtBusqueda.getText(), tipoBusqueda);
        DefaultTableModel modelo = (DefaultTableModel) tReporteContador.getModel();
        modelo = (DefaultTableModel) tReporteContador.getModel();
        modelo.setRowCount(l.size());
        int contador = 0;
        for (Cliente docPago : l) {
            modelo.setNumRows(contador);
            modelo.addRow(new Object[contador]);
            tReporteContador.setValueAt(docPago.getIdCliente(), contador, 0);
            tReporteContador.setValueAt(contador + 1, contador, 1);
            tReporteContador.setValueAt(docPago.getPapePat() + ' ' + docPago.getPapeMat() + ' ' + docPago.getPnombre(), contador, 2);
            tReporteContador.setValueAt(docPago.getCcodigoCole(), contador, 3);
            contador++;
        }
    }

    public void ImprimirMovimientosContador() {
        try {
            if (this.cliente != null) {
                String jdbcDriver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
                Class.forName(jdbcDriver);
                SeguridadBO sBO = SeguridadBO.getInstance();
                String url = sBO.getUrlReporte();
                String user = "sa";
                String pass = "4dm1n1str4c10nGOB90570";
                Connection con = DriverManager.getConnection(url, user, pass);
                String fullPath = "";
                Map param;
                fullPath = "reportes/Historial_Contador.jasper";
                param = new HashMap();
                param.put("IDCLIENTE", this.cliente.getIdCliente());
                param.put("Codigo_Colegiatura", this.cliente.getCcodigoCole());
                param.put("Nombre_contador", txtNombre.getText());
                param.put("REPORT_LOCALE", new Locale("en", "EN"));
                JasperPrint JPrint = JasperFillManager.fillReport(fullPath, param, con);
                JasperViewer.viewReport(JPrint, false);
            } else {
                JOptionPane.showMessageDialog(this, "DEBE ELEGIR UN CONTADOR","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }


    private void btnMovimientosContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientosContadorActionPerformed
        frmPrincipal fPrin = (frmPrincipal) this.getParent().getParent().getParent().getParent().getParent();
        Thread queryThread = new Thread() {
            public void run() {
                frmCargando fCargando = new frmCargando();
                fPrin.AgregarFormulario(fCargando);
                int x = (fPrin.getWidth() - fCargando.getWidth()) / 2;
                int y = (fPrin.getHeight() - fCargando.getHeight()) / 2;
                fCargando.setLocation(x, y);
                fCargando.setVisible(true);
                fCargando.toFront();
                ImprimirMovimientosContador();
                fCargando.dispose();
            }
        };
        queryThread.start();
    }//GEN-LAST:event_btnMovimientosContadorActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Thread queryThread = new Thread() {
            public void run() {
                pbContador.setIndeterminate(true);
                pbContador.setStringPainted(true);
                pbContador.setString("BUSCANDO CONTADOR, POR FAVOR ESPERE");
                pbContador.setValue(100);
                pbContador.repaint();
                buscarContador();
                pbContador.setString("BUSQUEDA FINALIZADA");
                pbContador.setStringPainted(false);
                pbContador.setIndeterminate(false);
            }
        };
        queryThread.start();
    }//GEN-LAST:event_btnBuscarActionPerformed


    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        if (evt.getKeyCode() == 10) {
            this.buscarContador();
        }
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void tReporteContadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tReporteContadorMouseClicked
        if (evt.getClickCount() == 2) {
            int fila = tReporteContador.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tReporteContador.getModel();
            int idContador = Integer.valueOf(model.getValueAt(fila, 0).toString());
            SeguridadBO sBO = SeguridadBO.getINSTANCE();
            Cliente cli = (Cliente) sBO.CargarObjeto("Cliente", idContador);
            cliente = cli;
            txtNombre.setText(cli.getPapePat() + " " + cli.getPapeMat() + " " + cli.getPnombre());
            txtNumero.setText(cli.getCcodigoCole());
            txtNombre.setEditable(true);
            txtNumero.setEditable(true);
            btnMovimientosContador.setEnabled(true);
        }
    }//GEN-LAST:event_tReporteContadorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMovimientosContador;
    private javax.swing.JComboBox cbFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar pbContador;
    private javax.swing.JTable tReporteContador;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
