/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

import caja.bo.NotaBO;
import caja.bo.SeguridadBO;
import caja.frm.frmPrincipal;
import caja.mapeo.entidades.Cliente;
import caja.mapeo.entidades.DocumentoPago;
import caja.mapeo.entidades.Nota;
import caja.mapeo.entidades.TipoDocPago;
import caja.mapeo.entidades.TipoDocSerie;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import units.DatePicker;

/**
 *
 * @author user
 */
public class frmNota extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmRequerimientos
     */
    public frmNota() {
        initComponents();
        Date ahora = new Date();
        SimpleDateFormat formateador = new SimpleDateFormat("yyyy-MM-dd");
        txtDesde.setText(formateador.format(ahora));
        txtHasta.setText(formateador.format(ahora));

        TableColumn columna = tComprobantes.getColumn("NRO");
        columna.setPreferredWidth(40);
        columna.setMinWidth(40);
        columna.setMaxWidth(40);
        columna = tComprobantes.getColumn("NOTA");
        columna.setPreferredWidth(200);
        columna.setMinWidth(200);
        columna.setMaxWidth(200);
        columna = tComprobantes.getColumn("TIPO DOC");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna = tComprobantes.getColumn("MOTIVO");
        columna.setPreferredWidth(200);
        columna.setMinWidth(200);
        columna.setMaxWidth(200);
        columna = tComprobantes.getColumn("FECHA");
        columna.setPreferredWidth(80);
        columna.setMinWidth(80);
        columna.setMaxWidth(80);
//        columna = tComprobantes.getColumn("CLIENTE");
//        columna.setPreferredWidth(300);
//        columna.setMinWidth(300);
//        columna.setMaxWidth(300);
        columna = tComprobantes.getColumn("OBSERVACIÓN");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna = tComprobantes.getColumn("NOTACREDITOOBJ");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tComprobantes = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNro = new javax.swing.JTextField();
        chkComprobante = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDesde = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHasta = new javax.swing.JTextField();
        chkFecha = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnNuevo = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setClosable(true);
        setTitle("LISTADO DE NOTAS DE CREDITO / DEBITO");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/icono.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 600));

        tComprobantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO", "NOTA", "TIPO DOC", "FECHA", "MOTIVO", "CLIENTE", "OBSERVACIÓN", "NOTACREDITOOBJ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tComprobantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tComprobantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tComprobantes);

        btnBuscar.setBackground(new java.awt.Color(204, 204, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/buscar10.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("NRO NOTA:");

        txtNro.setToolTipText("");
        txtNro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroKeyTyped(evt);
            }
        });

        chkComprobante.setBackground(new java.awt.Color(204, 204, 255));
        chkComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkComprobanteActionPerformed(evt);
            }
        });

        jLabel3.setText("FECHA:");

        jLabel4.setText("DESDE:");

        txtDesde.setEditable(false);

        jLabel5.setText("HASTA:");

        txtHasta.setEditable(false);

        chkFecha.setBackground(new java.awt.Color(204, 204, 255));
        chkFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFechaActionPerformed(evt);
            }
        });

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(204, 204, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/requerimiento_nuevo.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNro, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chkComprobante))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chkFecha))
                                    .addComponent(jLabel3))
                                .addGap(0, 310, Short.MAX_VALUE))
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkComprobante, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chkFecha)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jButton2)
                                        .addComponent(jLabel5)
                                        .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3)))))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (!chkFecha.isSelected() && !chkComprobante.isSelected()) {
            JOptionPane.showMessageDialog(this,
                    "DEBE ELEGIR UN FILTRO PARA REALIZAR LA BUSQUEDA",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        NotaBO ncBO = NotaBO.getInstance();
        List<Nota> lNotas = new ArrayList();
        String filtro = "";
//        if (chkCliente.isSelected()) {
//            filtro = "n.documentoPago.cliente.";
//            lNotas = ncBO.BuscarNota_SegunFiltro(txtCliente.getText());
//        }
        if (chkFecha.isSelected()) {
            try {
//                SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                Date fromDate = df.parse(txtDesde.getText() + " 00:00:00");
                Date toDate = df.parse(txtHasta.getText() + " 23:59:59");

//                SimpleDateFormat fF = new SimpleDateFormat("yyyyMMdd");
//                filtro = "n.fecha BETWEEN " + fF.format(f.parse(txtDesde.getText())) + " 00:00:00 AND " + fF.format(f.parse(txtHasta.getText())) + " 23:59:59";
                lNotas = ncBO.BuscarNota_SegunFecha(fromDate, toDate);

//                filtro = "n.fecha BETWEEN " + fromDate + " AND " + toDate;
//            '20100615 10:00:00' AND '20100615 11:00:00';
//                lNotas = ncBO.BuscarNota_SegunFecha(txtDesde.getText(), txtHasta.getText());
            } catch (ParseException ex) {
                Logger.getLogger(frmNota.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
//        if (chkNroDocIdentidad.isSelected()) {
//            lNotas = ncBO.BuscarNota_SegunNroDocIdentidad(txtDocIdentidad.getText());
//        }
        if (chkComprobante.isSelected()) {
            if (txtNro.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "DEBE INGRESAR UN NRO DE SOLICITUD",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            int nro = Integer.valueOf(txtNro.getText());
            filtro = "n.nro = " + nro;
            lNotas = ncBO.BuscarNota_SegunFiltro(filtro);
        }
//        lNotas = ncBO.BuscarNota_SegunFiltro(filtro);
        DefaultTableModel modelDetalle = (DefaultTableModel) tComprobantes.getModel();
        int contador = 0;
        modelDetalle.setRowCount(0);
        for (Nota nc : lNotas) {
            modelDetalle.setNumRows(contador);
            modelDetalle.addRow(new Object[contador]);
            tComprobantes.setValueAt(contador + 1, contador, 0);
            String tipo = "";
            if (nc.getTipo() == 1) {
                tipo = "N. CREDITO ELEC. ";
            } else {
                tipo = "N. DEBITO ELEC. ";
            }
            tComprobantes.setValueAt(tipo + nc.getNroSerie() + "-" + String.format("%05d", nc.getNro()), contador, 1);
//            tComprobantes.setValueAt(nc.getComprobantePago().getTipoDocumento(), contador, 2);
//            tComprobantes.setValueAt("SERIE: " + nc.getComprobantePago().getNroSerie() + " - NRO: " + String.format("%05d", nc.getComprobantePago().getNro()), contador, 3);
            SimpleDateFormat formateador = new SimpleDateFormat("yyyy-MM-dd");
            tComprobantes.setValueAt(formateador.format(nc.getFecha()), contador, 3);
            tComprobantes.setValueAt(nc.getTipoNota(), contador, 4);
            String nombreCliente = "";
            if (nc.getDocumentoPago().getCliente() != null) {
                if (nc.getDocumentoPago().getCliente().getTipoCliente().equals("C")) {
                    nombreCliente = nc.getDocumentoPago().getCliente().getPapePat() + " " + nc.getDocumentoPago().getCliente().getPapeMat() + " " + nc.getDocumentoPago().getCliente().getPnombre();
                } else {
                    if (nc.getDocumentoPago().getCliente().getTipoCliente().equals("P")) {
                        nombreCliente = nc.getDocumentoPago().getCliente().getPapePat() + " " + nc.getDocumentoPago().getCliente().getPapeMat() + " " + nc.getDocumentoPago().getCliente().getPnombre();
                    } else {
                        if (nc.getDocumentoPago().getCliente().getTipoCliente().equals("S")) {
                            nombreCliente = nc.getDocumentoPago().getCliente().getSnombreSociedad();
                        } else {
                            if (nc.getDocumentoPago().getCliente().getTipoCliente().equals("E")) {
                                nombreCliente = nc.getDocumentoPago().getCliente().getEnombre();
                            } else {
                            }
                        }
                    }
                }
            }
            tComprobantes.setValueAt(nombreCliente, contador, 5); //OBSERVACION
            tComprobantes.setValueAt(nc, contador, 7);
            contador++;
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void CargarComprobante() {
        int fila = tComprobantes.getSelectedRow();
        Nota nc = (Nota) tComprobantes.getValueAt(fila, 7);

        SeguridadBO sBO = SeguridadBO.getInstance();
        DocumentoPago dp = (DocumentoPago) sBO.CargarObjeto("DocumentoPago", nc.getDocumentoPago().getIdDocumentoPago());
        nc.setDocumentoPago(dp);
        TipoDocSerie tm = (TipoDocSerie) sBO.CargarObjeto("TipoDocSerie", nc.getDocumentoPago().getTipoDocSerie().getId());
        nc.getDocumentoPago().setTipoDocSerie(tm);
        TipoDocPago tdp = (TipoDocPago) sBO.CargarObjeto("TipoDocPago", nc.getDocumentoPago().getTipoDocSerie().getTipoDocPago().getIdTipoDocPago());
        nc.getDocumentoPago().getTipoDocSerie().setTipoDocPago(tdp);
        Cliente c = (Cliente) sBO.CargarObjeto("Cliente", nc.getDocumentoPago().getCliente().getIdCliente());
        nc.getDocumentoPago().setCliente(c);
//        TipoOperacion tipoOperacion = (TipoOperacion) sBO.CargarObjeto("TipoOperacion", nc.getComprobantePago().getTipoOperacion().getId());
//        TipoDocumento tipoDocumento = (TipoDocumento) sBO.CargarObjeto("TipoDocumento", nc.getTipoDocumento().getId());
//        ClienteProveedor cliente = (ClienteProveedor) sBO.CargarObjeto("ClienteProveedor", nc.getComprobantePago().getClienteProveedor().getId());
//        nc.getDocumentoPago().setClienteProveedor(cliente);
//        TipoDocIdentidad tipoDocIdentidad = (TipoDocIdentidad) sBO.CargarObjeto("TipoDocIdentidad", nc.getComprobantePago().getClienteProveedor().getTipoDocIdentidad().getId());
//        nc.getDocumentoPago().getCliente().setTipoDocIdentidad(tipoDocIdentidad);
//        nc.setTipoDocumento(tipoDocumento);
//        nc.getDocumentoPago().setFormaPago(fp);
//        nc.getDocumentoPago().setTipoMoneda(tm);
//        nc.getDocumentoPago().setTipoOperacion(tipoOperacion);
//        nc.getDocumentoPago().setUsuarioByIdVendedor(vendedor);

        frmPrincipal f = (frmPrincipal) this.getParent().getParent().getParent().getParent().getParent();
        f.AbrirFormularioNotaDetalle(nc);
//        if (nc.getNotaElectronica() == null) {
//            f.abrirFormularioNotaCreditoDetale(nc);
//        } else {
//            if (!nc.getNotaElectronica()) {
//                f.abrirFormularioNotaCreditoDetale(nc);
//            } else {
//                f.abrirFormularioNotaCreditoDetaleElectronica(nc);
//            }
//        }
    }

    private void tComprobantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tComprobantesMouseClicked
        if (evt.getClickCount() == 2) {
            final frmPrincipal fPrin = (frmPrincipal) this.getParent().getParent().getParent().getParent().getParent();
            Thread queryThread = new Thread() {
                public void run() {
                    frmCargando fCargando = new frmCargando();
                    fPrin.AgregarFormulario(fCargando);
                    int x = (fPrin.getWidth() - fCargando.getWidth()) / 2;
                    int y = (fPrin.getHeight() - fCargando.getHeight()) / 2;
                    fCargando.setLocation(x, y);
                    fCargando.setVisible(true);
                    fCargando.toFront();
                    CargarComprobante();
                    fCargando.dispose();
                }
            };
            queryThread.start();
        }
    }//GEN-LAST:event_tComprobantesMouseClicked

    private void txtNroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNroKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DatePicker dtp = new DatePicker(this);
        if (!dtp.setPickedDate().isEmpty()) {
            txtDesde.setText(dtp.setPickedDate());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DatePicker dtp = new DatePicker(this);
        if (!dtp.setPickedDate().isEmpty()) {
            txtHasta.setText(dtp.setPickedDate());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void chkComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkComprobanteActionPerformed
        chkFecha.setSelected(false);
//        chkNroDocIdentidad.setSelected(false);
//        chkCliente.setSelected(false);
    }//GEN-LAST:event_chkComprobanteActionPerformed

    private void chkFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFechaActionPerformed
        chkComprobante.setSelected(false);
//        chkNroDocIdentidad.setSelected(false);
//        chkCliente.setSelected(false);
    }//GEN-LAST:event_chkFechaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        Nota nc = new Nota();
        nc.setEstado("A");
//        String[] opciones = {"NOTA CRÉDITO - ELECTRÓNICA", "NOTA DÉBITO - ELECTRÓNICA"};
//        String opcion = (String) JOptionPane.showInputDialog(this,
//                "ELEGIR EL TIPO DE NOTA DE CRÉDITO A GENERAR",
//                "TIPO NOTA DE CRÉDITO",
//                JOptionPane.QUESTION_MESSAGE,
//                null,
//                opciones,
//                opciones[0]);
        frmPrincipal f = (frmPrincipal) this.getParent().getParent().getParent().getParent().getParent();
        nc.setElectronico("S");
//        if (opcion.equals("NOTA CRÉDITO - ELECTRÓNICA")) {
//            nc.setTipoNota(tipoNota);
//        } else {
//            nc.setTipoNota(tipoNota);
//        }
        f.AbrirFormularioNotaDetalle(nc);
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox chkComprobante;
    private javax.swing.JCheckBox chkFecha;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tComprobantes;
    private javax.swing.JTextField txtDesde;
    private javax.swing.JTextField txtHasta;
    private javax.swing.JTextField txtNro;
    // End of variables declaration//GEN-END:variables
}
