/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

import caja.bo.AnioMesBO;
import caja.bo.ClienteBO;
import caja.bo.CuotasBO;
//import caja.bo.DeudasBO;
//import caja.bo.DocumentoPagoBO;
import caja.bo.FinanciamientoBO;
import caja.bo.PersonaBO;
//import caja.bo.PersonaBO;
//import caja.bo.ReincorporacionBO;
import caja.frm.frmPrincipal;
import caja.mapeo.entidades.AnioMes;
import caja.mapeo.entidades.Cliente;
//import caja.mapeo.entidades.Deuda;
import caja.mapeo.entidades.FinanciamientoDocumentoPago;
//import caja.mapeo.entidades.ReincorporacionDocumentoPago;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author user
 */
public class frmReporteDeudaSociedades extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReporteDeudaColegiados
     */
    public frmReporteDeudaSociedades() {
        initComponents();
        tListado.setAutoResizeMode(tListado.AUTO_RESIZE_OFF);
        TableColumn columna = tListado.getColumn("NRO");
        columna.setPreferredWidth(40);
        columna.setMinWidth(40);
        columna.setMaxWidth(40);
        columna = tListado.getColumn("ELIM");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tListado = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setTitle("REPORTE DEUDA SOCIEDADES");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/icono.png"))); // NOI18N

        tListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO", "MATRICULA", "NOMBRES", "ELIM", "TEL. FIJO", "TEL. CEL", "E-MAIL", "FEC AFIL", "DIRECCION", "DEP", "PRO", "DIS", "COB", "CIUDAD", "ESTADO", "C. ORDINARIA", "MONTO C.ORD", "FINANCIAMIENTO", "MONTO FINANCIAMIENTO", "REINCOR. 2015", "MONTO REINCOR. 2015", "MULTA1", "MULTA2", "REIN 2005", "REIN 2006", "OTRO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tListado);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/buscar5.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarDatos() {
        PersonaBO pBO = PersonaBO.getInstance();
        CuotasBO cuBO = CuotasBO.getInstance();
        ClienteBO cBO = ClienteBO.getInstance();
        List<Cliente> listado = cBO.ObtenerTodasSociedades();
        DefaultTableModel modelDetalle = (DefaultTableModel) tListado.getModel();
        modelDetalle.setNumRows(0);
        int contador = 0;
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        for (Cliente c : listado) {
            modelDetalle.setNumRows(contador);
            modelDetalle.addRow(new Object[contador]);
            tListado.setValueAt(contador + 1, contador, 0);
            if (c.getScodigoSoc() != null) {
                tListado.setValueAt(c.getScodigoSoc(), contador, 1);
            }
            if (c.getSnombreSociedad() != null) {
                tListado.setValueAt(c.getSnombreSociedad(), contador, 2);
            }
            if (c.getStelefonoFijo() != null) {
                tListado.setValueAt(c.getStelefonoFijo(), contador, 4);
            }
            if (c.getStelefonoCelular() != null) {
                tListado.setValueAt(c.getStelefonoCelular(), contador, 5);
            }
            if (c.getSemail() != null) {
                tListado.setValueAt(c.getSemail(), contador, 6);
            }
            if (c.getSfechaAfiliacion() != null) {
                tListado.setValueAt(formato.format(c.getSfechaAfiliacion()), contador, 7);
            }
            if (c.getSdireccion() != null) {
                tListado.setValueAt(c.getSdireccion(), contador, 8);
            }
            if (c.getSdepartamento() != null) {
                String nombre = pBO.ObtenerNombreDepartamento(c.getSdepartamento());
                tListado.setValueAt(nombre, contador, 9);
            }
            if (c.getSprovincia() != null) {
                String nombre = pBO.ObtenerNombreProvincia(c.getSprovincia());
                tListado.setValueAt(nombre, contador, 10);
            }
            if (c.getSdistrito() != null) {
                String nombre = pBO.ObtenerNombreDistrito(c.getSdistrito());
                tListado.setValueAt(nombre, contador, 11);
            }
            if (c.getScobrador() != null) {
                tListado.setValueAt(c.getScobrador(), contador, 12);
            }
            if (c.getSciudad() != null) {
                if (c.getSciudad().equals("A")) {
                    tListado.setValueAt("AREQUIPA", contador, 13);
                } else {
                    if (c.getSciudad().equals("L")) {
                        tListado.setValueAt("LIMA", contador, 13);
                    } else {
                    }
                }
            }
            if (c.getEstado() != null) {
                if (c.getEstado().equals("H")) {
                    tListado.setValueAt("HABIL", contador, 14);
                }
                if (c.getEstado().equals("I")) {
                    tListado.setValueAt("INHABIL", contador, 14);
                }
                if (c.getEstado().equals("L")) {
                    tListado.setValueAt("LICENCIA", contador, 14);
                }
                if (c.getEstado().equals("R")) {
                    tListado.setValueAt("RETIRADO", contador, 14);
                }
            }

            if (c.getEstado().equals("H") || c.getEstado().equals("I")) {
                double monto = 0;
                if (c.getSfechaAfiliacion() != null) {
                    List listadoCuotas = cuBO.ObtenerCuotasPendientesClienteSociedades(c);
                    if (listadoCuotas != null) {
                        for (Object pobj : listadoCuotas) {
                            Object[] obj = (Object[]) pobj;
                            if (obj[4] == null) {
                                monto = monto + (double) obj[5];
                            }
                        }
                        if (!listadoCuotas.isEmpty()) {
                            Object[] desde = (Object[]) listadoCuotas.get(0);
                            Object[] hasta = (Object[]) listadoCuotas.get(listadoCuotas.size() - 1);
                            AnioMesBO amBO = AnioMesBO.getInstance();
                            AnioMes amDesde = amBO.ObtenerAnioMesSegunNroOrden((int) desde[0]);
                            AnioMes amHasta = amBO.ObtenerAnioMesSegunNroOrden((int) hasta[0]);
                            tListado.setValueAt(amDesde.getAnio() + " / " + amDesde.getMes() + " - " + amHasta.getAnio() + " / " + amHasta.getMes(), contador, 15);
                        }
                    }
                }

                tListado.setValueAt(monto, contador, 16);
                FinanciamientoBO fBO = FinanciamientoBO.getInstance();
                List<FinanciamientoDocumentoPago> listadoFinanciamientos = fBO.ObtenerTodosFinanciamientosPendientes(c.getIdCliente());
                double montoFinanciamiento = 0;
                if (listadoFinanciamientos != null) {
                    for (FinanciamientoDocumentoPago fdp : listadoFinanciamientos) {
                        montoFinanciamiento = montoFinanciamiento + fdp.getMonto();
                    }
                    tListado.setValueAt("Cuotas: " + listadoFinanciamientos.size(), contador, 17);
                    tListado.setValueAt(montoFinanciamiento, contador, 18);
                }
            }
            contador = contador + 1;
        }
    }


    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        frmPrincipal fPrin = (frmPrincipal) this.getParent().getParent().getParent().getParent().getParent();
        Thread queryThread = new Thread() {
            public void run() {
                frmCargando fCargando = new frmCargando();
                fPrin.AgregarFormulario(fCargando);
                int x = (fPrin.getWidth() - fCargando.getWidth()) / 2;
                int y = (fPrin.getHeight() - fCargando.getHeight()) / 2;
                fCargando.setLocation(x, y);
                fCargando.setVisible(true);
                fCargando.toFront();
                CargarDatos();
                fCargando.dispose();
            }
        };
        queryThread.start();
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tListado;
    // End of variables declaration//GEN-END:variables
}
