/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

import caja.bo.AlumnoBO;
import caja.bo.SeguridadBO;
import caja.mapeo.entidades.Alumnos;
import caja.mapeo.entidades.Cliente;
import caja.mapeo.entidades.ConceptoPagoDetalle;
//import caja.frm.frmPrincipal;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
//import java.awt.event.KeyAdapter;
//import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author juan carlos
 */
public class frmReporteCursos extends javax.swing.JInternalFrame {

//    private String tipoCliente;
    private Alumnos aluActual;
    private List<Object> lAlumnos;
    private boolean accesoGuardar = false;

    /**
     * Creates new form frmReporteCursos
     */
    public frmReporteCursos() {
        initComponents();

        TableColumn columna = tAlumnos.getColumn("NRO");
        columna.setPreferredWidth(40);
        columna.setMinWidth(40);
        //columna.setMaxWidth(40);

        columna = tAlumnos.getColumn("ID");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);

        columna = tAlumnos.getColumn("ID DETALLE");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);

        columna = tAlumnos.getColumn("N.DOCUMENTO");
        columna.setPreferredWidth(100);
        columna.setMinWidth(70);

        columna = tAlumnos.getColumn("COLEGIATURA");
        columna.setPreferredWidth(100);
        columna.setMinWidth(70);

        //columna.setMaxWidth(500);
        columna = tAlumnos.getColumn("APELLIDO PATERNO");
        columna.setPreferredWidth(200);
        columna.setMinWidth(70);
        //columna.setMaxWidth(70);
        columna = tAlumnos.getColumn("APELLIDO MATERNO");
        columna.setPreferredWidth(200);
        columna.setMinWidth(70);
        //columna.setMaxWidth(0);
        columna = tAlumnos.getColumn("NOMBRES");
        columna.setPreferredWidth(200);
        columna.setMinWidth(70);
        //columna.setMaxWidth(70);
        columna = tAlumnos.getColumn("CONCEPTO CURSOS");
        columna.setPreferredWidth(450);
        columna.setMinWidth(150);

        columna = tAlumnos.getColumn("CODIGO");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);

        columna = tAlumnos.getColumn("MONTO");
        columna.setPreferredWidth(100);
        columna.setMinWidth(50);

        columna = tAlumnos.getColumn("T.PAGO");
        columna.setPreferredWidth(50);
        columna.setMinWidth(50);

        txtDNI.setEditable(false);
        txtCodigo.setEditable(false);
        txtMonto.setEditable(false);
        txtTipoPago.setEditable(false);
        txtNombre.setEditable(false);
        txtApellidoPaterno.setEditable(false);
        txtApellidoMaterno.setEditable(false);
        txtConceptoCurso.setEditable(false);
        txtCodigoCurso.setEditable(false);
        SeguridadBO sBO = SeguridadBO.getInstance();
        if (sBO.getUsuario().getRolUsuario().equals("SA")) {
            accesoGuardar = true;
        } else {
            if (sBO.getUsuario().getRolUsuario().equals("A")) {
                accesoGuardar = true;
            } else {
                accesoGuardar = false;
            }
        }

//        btnEliminar.setEnabled(false);
    }

    public void CargarDatos(String tipoCliente) {
        //this.tipoCliente = tipoCliente;
//        AlumnoBO aBO = AlumnoBO.getInstance();
//        List<Cliente> lClientes = aBO.ObtenerTodosClientes();
//        
//        
//        cbCodigo.setSelectedIndex(-1);
//        ((JTextField) cbCodigo.getEditor().getEditorComponent()).setText("");
//        cbCodigo.setPreferredSize(new Dimension(123, 20));
//        cbConceptoCurso.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAlumnos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTipoPago = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtConceptoCurso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCodigoCurso = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        cbFiltro = new javax.swing.JComboBox();
        pbAlumnos = new javax.swing.JProgressBar();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("BUSQUEDA ALUMNOS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/icono.png"))); // NOI18N

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/buscar_mini1.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NRO", "ID DETALLE", "N.DOCUMENTO", "COLEGIATURA", "APELLIDO PATERNO", "APELLIDO MATERNO", "NOMBRES", "CONCEPTO CURSOS", "CODIGO", "MONTO", "T.PAGO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tAlumnosMouseClicked(evt);
            }
        });
        tAlumnos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tAlumnosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tAlumnos);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Alumnos"));

        jLabel3.setText("N°  D.N.I.");

        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIKeyTyped(evt);
            }
        });

        jLabel4.setText("CÓDIGO:");

        jLabel5.setText("MONTO:");

        jLabel6.setText("TIPO CODIGO:");

        jLabel7.setText("NOMBRE:");

        jLabel8.setText("APELLIDO PATERNO:");

        jLabel9.setText("APELLIDO MATERNO:");

        jLabel10.setText("CONCEPTO CURSO:");

        jLabel11.setText("CÓDIGO DEL CURSO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(24, 24, 24))
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10)
                    .addComponent(txtConceptoCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCodigoCurso, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConceptoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel12.setText("BÚSQUEDA:");

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "POR CODIGO CURSO", "POR NOMBRE CURSO", "POR DNI", "POR COLEGIATURA", "POR APELLIDO PATERNO", "POR APELLIDO MATERNO" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbFiltro, 0, 143, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbAlumnos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarAlumno() {
        txtDNI.setEditable(false);
        txtCodigo.setEditable(false);
        txtMonto.setEditable(false);
        txtTipoPago.setEditable(false);
        txtNombre.setEditable(false);
        txtApellidoPaterno.setEditable(false);
        txtApellidoMaterno.setEditable(false);
        txtConceptoCurso.setEditable(false);
        txtCodigoCurso.setEditable(false);
        int tipoBusqueda = 0;
        if (cbFiltro.getSelectedItem() == "POR CODIGO CURSO") {
            tipoBusqueda = 1;
        } else if (cbFiltro.getSelectedItem() == "POR NOMBRE CURSO") {
            tipoBusqueda = 2;
        } else if (cbFiltro.getSelectedItem() == "POR DNI") {
            tipoBusqueda = 3;
        } else if (cbFiltro.getSelectedItem() == "POR COLEGIATURA") {
            tipoBusqueda = 4;
        } else if (cbFiltro.getSelectedItem() == "POR APELLIDO PATERNO") {
            tipoBusqueda = 5;
        } else if (cbFiltro.getSelectedItem() == "POR APELLIDO MATERNO") {
            tipoBusqueda = 6;
        }

        AlumnoBO a = AlumnoBO.getInstance();
        List<Alumnos> l = a.BuscarAlumno(txtBusqueda.getText(), tipoBusqueda);
        DefaultTableModel modelo = (DefaultTableModel) tAlumnos.getModel();
        modelo = (DefaultTableModel) tAlumnos.getModel();
        modelo.setRowCount(l.size());
        int contador = 0;
        for (Alumnos alu : l) {
            modelo.setNumRows(contador);
            modelo.addRow(new Object[contador]);
            tAlumnos.setValueAt(alu.getIdAlumno(), contador, 0);
            tAlumnos.setValueAt(contador + 1, contador, 1);
            tAlumnos.setValueAt(alu.getDocumentoPagoDet().getIdDocumentoPagoDet(), contador, 2);
            tAlumnos.setValueAt(alu.getDni(), contador, 3);
            tAlumnos.setValueAt(alu.getCodigo(), contador, 4);
            tAlumnos.setValueAt(alu.getApellidoPaterno(), contador, 5);
            tAlumnos.setValueAt(alu.getApellidoMaterno(), contador, 6);
            tAlumnos.setValueAt(alu.getNombres(), contador, 7);
            tAlumnos.setValueAt(alu.getConceptoCurso(), contador, 8);
            tAlumnos.setValueAt(alu.getCodigoCurso(), contador, 9);
            tAlumnos.setValueAt(alu.getMonto(), contador, 10);
            tAlumnos.setValueAt(alu.getTipoPago(), contador, 11);
            contador++;
        }
    }

//    private void Buscar(String codigo) {
//        int contador = 0;
//        AlumnoBO alu = AlumnoBO.getInstance();
//        
//        DefaultTableModel modelDetalle = (DefaultTableModel) tAlumnos.getModel();
//        
//        
//        this.lAlumnos = alu.ObtenerTodosAlumnosPorCurso(codigo);
//        
//        for (Object al : lAlumnos) {
//            Object[]ObjAl = (Object[])al;
//            modelDetalle.setRowCount(contador);
//            modelDetalle.addRow(new Object[contador]);
//            tAlumnos.setValueAt(contador + 1, contador, 0);
//            tAlumnos.setValueAt(ObjAl[1], contador, 1);
//            tAlumnos.setValueAt(ObjAl[2], contador, 2);
//            tAlumnos.setValueAt(ObjAl[3], contador, 3);
//            tAlumnos.setValueAt(ObjAl[4], contador, 4);
//            contador++;
//        }
//        btnBuscar.requestFocus();
//    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Thread queryThread = new Thread() {
            public void run() {
                pbAlumnos.setIndeterminate(true);
                pbAlumnos.setStringPainted(true);
                pbAlumnos.setString("BUSCANDO ALUMNO, POR FAVOR ESPERE");
                pbAlumnos.setValue(100);
                pbAlumnos.repaint();
                buscarAlumno();
                pbAlumnos.setString("BUSQUEDA FINALIZADA");
                pbAlumnos.setStringPainted(false);
                pbAlumnos.setIndeterminate(false);
            }
        };
        queryThread.start();

//        String codigo = "";
//        this.Buscar(codigo);
//
//        String tp;
//        tp = cbCodigo.getSelectedItem().toString();       
        //Buscar(tp);

    }//GEN-LAST:event_btnBuscarActionPerformed


    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        if (evt.getKeyCode() == 10) {
            this.buscarAlumno();
        }
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void txtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDNIKeyTyped

    private void tAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tAlumnosMouseClicked
        if (evt.getClickCount() == 2) {
            int fila = tAlumnos.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tAlumnos.getModel();
            String dni = String.valueOf(model.getValueAt(fila, 3));
            if (dni == null) {
                dni = "";
            } else {
                if (dni.equals("null")) {
                    dni = "";
                }
            }
            String codigo = String.valueOf(model.getValueAt(fila, 4));
            if (codigo == null) {
                codigo = "";
            } else {
                if (codigo.equals("null")) {
                    codigo = "";
                }
            }
            AlumnoBO a = AlumnoBO.getInstance();
            if (!dni.isEmpty()) {
                aluActual = a.ObtenerAlumno(dni);
            } else {
                if (!codigo.isEmpty()) {
                    aluActual = a.ObtenerAlumnoPorCodigo(codigo);
                } else {
                }
            }
            //aluActual = a.ObtenerAlumnoPorCodigo(codigo);

            txtDNI.setText(aluActual.getDni());

            txtCodigo.setText(aluActual.getCodigo());
            txtApellidoPaterno.setText(aluActual.getApellidoPaterno());
            txtApellidoMaterno.setText(aluActual.getApellidoMaterno());
            txtNombre.setText(aluActual.getNombres());
            txtConceptoCurso.setText(aluActual.getConceptoCurso());
            txtCodigoCurso.setText(aluActual.getCodigoCurso());
            txtMonto.setText(aluActual.getMonto().toString());
            txtTipoPago.setText(aluActual.getTipoPago());

            txtDNI.setEditable(true);
            txtCodigo.setEditable(true);
            txtApellidoPaterno.setEditable(true);
            txtApellidoMaterno.setEditable(true);
            txtNombre.setEditable(true);
            txtConceptoCurso.setEditable(true);
            txtCodigoCurso.setEditable(true);
            txtMonto.setEditable(true);
            txtTipoPago.setEditable(true);
        }
    }//GEN-LAST:event_tAlumnosMouseClicked

    private void tAlumnosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tAlumnosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            if (this.accesoGuardar) {
                int fila = tAlumnos.getSelectedRow();
                if (fila >= 0) {
                    int opcion = JOptionPane.showConfirmDialog(null, "¿ DESEA ELIMINAR EL ALUMNO ?");
                    if (opcion == JOptionPane.YES_OPTION) {
                        int idAlumno = (int) tAlumnos.getValueAt(fila, 0);
                        SeguridadBO sBO = SeguridadBO.getINSTANCE();
                        Alumnos a = (Alumnos) sBO.CargarObjeto("Alumnos", idAlumno);
                        AlumnoBO aBO = AlumnoBO.getInstance();
                        aBO.EliminarAlumnos(a);
                        DefaultTableModel model = (DefaultTableModel) tAlumnos.getModel();
                        model.removeRow(fila);
                    }
                }
            }
        }
    }//GEN-LAST:event_tAlumnosKeyPressed

//    private void ObtenerDatosConceptoCurso(String detCurso) {
//        AlumnoBO aluBO = AlumnoBO.getInstance();
//        List<ConceptoPagoDetalle> lConceptoPago = aluBO.ObtenerTodosConceptoPagoCursos();
//        for (ConceptoPagoDetalle cd : lConceptoPago) {
//            if(cd.getDescripcion().equals(detCurso))
//            {
//                btnBuscar.setEnabled(true);
//                btnImprimir.setEnabled(true);
//            }
//            else{
//                btnBuscar.setEnabled(false);
//                btnImprimir.setEnabled(false);
//            }
//            return;
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox cbFiltro;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar pbAlumnos;
    private javax.swing.JTable tAlumnos;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoCurso;
    private javax.swing.JTextField txtConceptoCurso;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTipoPago;
    // End of variables declaration//GEN-END:variables
}
