/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

import caja.bo.DocumentoPagoBO;
import caja.bo.SeguridadBO;
import caja.frm.frmPrincipal;
import caja.mapeo.entidades.Cliente;
import caja.mapeo.entidades.Cobrador;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.view.JasperViewer;
import units.DatePicker;

/**
 *
 * @author juan carlos
 */
public class frmReporteDiario extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReporteDiario
     */
    public frmReporteDiario() {
        initComponents();
        Date ahora = new Date();
        SimpleDateFormat formateador = new SimpleDateFormat("yyyy-MM-dd");
        txtFecha.setText(formateador.format(ahora));
        DocumentoPagoBO dBO = DocumentoPagoBO.getInstance();
        List<Cobrador> lCobrador = dBO.ObtenerTodosCobradores();
        Cobrador c = new Cobrador();
        Cliente cl = new Cliente();
        cl.setPapePat("NINGUNO");
        cl.setPapeMat("");
        cl.setPnombre("");
        c.setCliente(cl);
        cbCobrador.addItem(c);
        for (Cobrador co : lCobrador) {
            if (co.getEstado() != null) {
                if (co.getEstado().equals("H")) {
                    cbCobrador.addItem(co);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnFecha = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        cbCobrador = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte Diario");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/icono.png"))); // NOI18N

        jLabel1.setText("FECHA:");

        txtFecha.setEditable(false);

        btnFecha.setText("...");
        btnFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaActionPerformed(evt);
            }
        });

        btnReporte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReporte.setText("GENERAR REPORTE");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFecha))
                    .addComponent(cbCobrador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(cbCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaActionPerformed
        DatePicker dtp = new DatePicker(this);
        txtFecha.setText(dtp.setPickedDate());
    }//GEN-LAST:event_btnFechaActionPerformed
    
    public void ImprimirDocumentoPago() {
        try {
            String jdbcDriver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
            Class.forName(jdbcDriver);
            SeguridadBO sBO = SeguridadBO.getInstance();
            String url = sBO.getUrlReporte();
            //String url = "jdbc:sqlserver://localhost;databaseName=Caja";
            String user = "sa";
            //String pass = "sajuancarlos";
            String pass = "4dm1n1str4c10nGOB90570";
            Connection con = DriverManager.getConnection(url, user, pass);
            String fullPath = "";
            Map param;
            int idCobrador = ((Cobrador) cbCobrador.getSelectedItem()).getIdCobrador();
            int idUsuario = 0;
            if (idCobrador == 0) {
                fullPath = "reportes/reporteDiario.jasper";
            } else {
                DocumentoPagoBO dpBO = DocumentoPagoBO.getInstance();
                idUsuario = dpBO.obtenerIDUsuario_SegunIDCobrador(idCobrador);
                fullPath = "reportes/reporteDiarioCobrador.jasper";
            }
//            DocumentoPago doc = dpBO.getDocumentoPago();
            param = new HashMap();
//            param.put("IDDOCUMENTOPAGO", Integer.valueOf(doc.getIdDocumentoPago()));
//            param.put("TOTALENLETRAS", "SON: " + NumeroLetras.convertirNumerosALetras(lbTotal.getText(), doc.getMoneda()));
            //SimpleDateFormat formateador = new SimpleDateFormat("yyyyMMdd");
            String fecha_texto = txtFecha.getText();
            DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            DateFormat fAnio = new SimpleDateFormat("yyyy");
            DateFormat fMes = new SimpleDateFormat("MM");
            DateFormat fDia = new SimpleDateFormat("dd");
            Date date = format.parse(fecha_texto);
            param.put("ANIO", Integer.valueOf(fAnio.format(date)));
            param.put("MES", Integer.valueOf(fMes.format(date)));
            param.put("DIA", Integer.valueOf(fDia.format(date)));
            param.put("IDCOBRADOR", idCobrador);
            param.put("IDUSUARIO", idUsuario);
            param.put("FECHA", fecha_texto);
            param.put("REPORT_LOCALE", new Locale("en", "EN"));
            JasperPrint JPrint = JasperFillManager.fillReport(fullPath, param, con);
            
            JasperViewer.viewReport(JPrint, false);
            //JasperPrintManager.printReport(JPrint, true);
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }
    

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        frmPrincipal fPrin = (frmPrincipal) this.getParent().getParent().getParent().getParent().getParent();
        Thread queryThread = new Thread() {
            public void run() {
                frmCargando fCargando = new frmCargando();
                fPrin.AgregarFormulario(fCargando);
                int x = (fPrin.getWidth() - fCargando.getWidth()) / 2;
                int y = (fPrin.getHeight() - fCargando.getHeight()) / 2;
                fCargando.setLocation(x, y);
                fCargando.setVisible(true);
                fCargando.toFront();
                ImprimirDocumentoPago();
                fCargando.dispose();
            }
        };
        queryThread.start();

    }//GEN-LAST:event_btnReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFecha;
    private javax.swing.JButton btnReporte;
    private javax.swing.JComboBox cbCobrador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
