/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

import caja.bo.DocumentoPagoBO;
import caja.bo.SeguridadBO;
import caja.mapeo.entidades.Cliente;
import caja.mapeo.entidades.ConceptoPagoDetalle;
import caja.mapeo.entidades.DocumentoPago;
import caja.mapeo.entidades.DocumentoPagoDet;
import caja.mapeo.entidades.TipoDocPago;
import caja.mapeo.entidades.TipoDocSerie;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author user
 */
public class frmSeleccionarComprobanteDetalle extends javax.swing.JDialog {

    private Object frm;
    private int tipoCarga;

    /**
     * Creates new form frmSeleccionarComprobanteDetalle
     */
    public frmSeleccionarComprobanteDetalle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        TableColumn columna = tDetalle.getColumn("OBJ");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna = tDetalle.getColumn("NRO");
        columna.setPreferredWidth(40);
        columna.setMinWidth(40);
        columna.setMaxWidth(40);
        columna = tDetalle.getColumn("PAGO");
        columna.setPreferredWidth(700);
        columna.setMinWidth(700);
        columna.setMaxWidth(700);
        columna = tDetalle.getColumn("CANTIDAD");
        columna.setPreferredWidth(70);
        columna.setMinWidth(70);
        columna.setMaxWidth(70);
        columna = tDetalle.getColumn("P. UNITARIO");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna = tDetalle.getColumn("TOTAL");
        columna.setPreferredWidth(70);
        columna.setMinWidth(70);
        columna.setMaxWidth(70);
        columna = tDetalle.getColumn("NOMCONCEPTOPAGO");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna = tDetalle.getColumn("VALORVENTA");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna = tDetalle.getColumn("IGV");
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna.setPreferredWidth(0);
        columna = tDetalle.getColumn("IDINTERNO");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna = tDetalle.getColumn("GLOSA");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna = tDetalle.getColumn("PARTICIPANTES");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna = tDetalle.getColumn("EC");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna = tDetalle.getColumn("VALE_ACADEMICO");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tDetalle = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OBJ", "NRO", "PAGO", "CANTIDAD", "P. UNITARIO", "TOTAL", "NOMCONCEPTOPAGO", "VALORVENTA", "IGV", "IDINTERNO", "GLOSA", "PARTICIPANTES", "EC", "VALE_ACADEMICO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDetalleMouseClicked(evt);
            }
        });
        tDetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tDetalleKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tDetalle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tDetalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tDetalleKeyPressed

    }//GEN-LAST:event_tDetalleKeyPressed

    private void tDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDetalleMouseClicked
        if (evt.getClickCount() == 2) {
            int fila = tDetalle.getSelectedRow();
            if (fila >= 0) {
                DocumentoPagoDet dpd = (DocumentoPagoDet) tDetalle.getValueAt(fila, 0);
                if (this.tipoCarga == 1) {  //Vale academico cabecera
                    this.dispose();
                    SeguridadBO sBO = SeguridadBO.getINSTANCE();
                    DocumentoPago documentoPago = (DocumentoPago) sBO.CargarObjeto("DocumentoPago", dpd.getDocumentoPago().getIdDocumentoPago());
                    dpd.setDocumentoPago(documentoPago);
                    Cliente cliente = (Cliente) sBO.CargarObjeto("Cliente", dpd.getDocumentoPago().getCliente().getIdCliente());
                    dpd.getDocumentoPago().setCliente(cliente);
                    TipoDocSerie dp = (TipoDocSerie) sBO.CargarObjeto("TipoDocSerie", dpd.getDocumentoPago().getTipoDocSerie().getId());
                    dpd.getDocumentoPago().setTipoDocSerie(dp);
                    ConceptoPagoDetalle concepto = (ConceptoPagoDetalle) sBO.CargarObjeto("ConceptoPagoDetalle", dpd.getConceptoPagoDetalle().getIdConceptoPagoDetalle());
                    dpd.setConceptoPagoDetalle(concepto);
                    TipoDocPago td = (TipoDocPago) sBO.CargarObjeto("TipoDocPago", dp.getTipoDocPago().getIdTipoDocPago());
                    dpd.getDocumentoPago().getTipoDocSerie().setTipoDocPago(td);
                    if (concepto.getIdConceptoPagoDetalle() == 2) {
                        ((frmValeAcademicoDetalle) this.frm).setearDocumentoPagoDetalle_Cabecera(dpd);
                    }else{
                        JOptionPane.showMessageDialog(this, "SOLO ES POSIBLE ELEGIR EL CONCEPTO: CUOTA ORDINARIA", "ERROR", JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                }
                if (this.tipoCarga == 2) {  //Vale academico detalle
                    this.dispose();
                    ((frmValeAcademicoDetalle) this.frm).setearDocumentoPagoDetalle_Detalle(dpd);

                }
            }
        }
    }//GEN-LAST:event_tDetalleMouseClicked

    public void cargarDatos(Object f, int tc, DocumentoPago dp) {
        this.frm = f;
        this.tipoCarga = tc;
        DocumentoPagoBO dpBO = DocumentoPagoBO.getInstance();
        List<DocumentoPagoDet> lDetalle = dpBO.ObtenerDetalleComprobante(dp.getIdDocumentoPago());
        DefaultTableModel modelDetalle = (DefaultTableModel) tDetalle.getModel();
        int contador = 0;
        double precioVenta = 0;
        double igv = 0;
        double valorVenta = 0;
        for (DocumentoPagoDet dpd : lDetalle) {
            modelDetalle.setNumRows(contador);
            modelDetalle.addRow(new Object[contador]);
            tDetalle.setValueAt(dpd, contador, 0);
            tDetalle.setValueAt(contador + 1, contador, 1);
            if (dpd.getObservacion() == null) {
                tDetalle.setValueAt(dpd.getConceptoPagoDetalle().getDescripcion(), contador, 2);
            } else {
                if (dpd.getObservacion().isEmpty() || dpd.getObservacion().equals("null")) {
                    tDetalle.setValueAt(dpd.getConceptoPagoDetalle().getDescripcion(), contador, 2);
                } else {
                    tDetalle.setValueAt(dpd.getConceptoPagoDetalle().getDescripcion() + " (" + dpd.getObservacion() + ")", contador, 2);
                }
            }
            tDetalle.setValueAt(dpd.getCantidad(), contador, 3);
            tDetalle.setValueAt(dpd.getPrecioUnitario(), contador, 4);
            tDetalle.setValueAt(dpd.getValorVenta() + dpd.getIgv(), contador, 5);
            precioVenta = precioVenta + dpd.getValorVenta() + dpd.getIgv();
            igv = igv + dpd.getIgv();
            valorVenta = valorVenta + dpd.getValorVenta();
            contador = contador + 1;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSeleccionarComprobanteDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSeleccionarComprobanteDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSeleccionarComprobanteDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSeleccionarComprobanteDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmSeleccionarComprobanteDetalle dialog = new frmSeleccionarComprobanteDetalle(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tDetalle;
    // End of variables declaration//GEN-END:variables
}
