/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.caja;

import caja.bo.DocumentoPagoBO;
import caja.bo.NotaBO;
import caja.bo.SeguridadBO;
import caja.frm.frmPrincipal;
import caja.mapeo.entidades.Cliente;
import caja.mapeo.entidades.ConceptoPagoDetalle;
import caja.mapeo.entidades.DocumentoPago;
import caja.mapeo.entidades.DocumentoPagoDet;
import caja.mapeo.entidades.Nota;
import caja.mapeo.entidades.TipoDocPago;
import caja.mapeo.entidades.TipoDocSerie;
import caja.mapeo.entidades.Usuario;
import caja.mapeo.entidades.ValeAcademico;
import caja.mapeo.entidades.ValeAcademicoConsumo;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import units.DatePicker;

/**
 *
 * @author user
 */
public class frmValeAcademico extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmRequerimientos
     */
    public frmValeAcademico() {
        initComponents();
        Date ahora = new Date();
        SimpleDateFormat formateador = new SimpleDateFormat("yyyy-MM-dd");
        txtDesde.setText(formateador.format(ahora));
        txtHasta.setText(formateador.format(ahora));
        
        TableColumn columna = tComprobantes.getColumn("NRO");
        columna.setPreferredWidth(40);
        columna.setMinWidth(40);
        columna.setMaxWidth(40);
        columna = tComprobantes.getColumn("OBJ");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna = tComprobantes.getColumn("VALE");
        columna.setPreferredWidth(100);
        columna.setMinWidth(100);
        columna.setMaxWidth(100);
        columna = tComprobantes.getColumn("FECHA DESDE");
        columna.setPreferredWidth(80);
        columna.setMinWidth(80);
        columna.setMaxWidth(80);
        columna = tComprobantes.getColumn("FECHA HASTA");
        columna.setPreferredWidth(80);
        columna.setMinWidth(80);
        columna.setMaxWidth(80);
//        columna = tComprobantes.getColumn("CLIENTE");
//        columna.setPreferredWidth(300);
//        columna.setMinWidth(300);
//        columna.setMaxWidth(300);
        columna = tComprobantes.getColumn("MONTO");
        columna.setPreferredWidth(80);
        columna.setMinWidth(80);
        columna.setMaxWidth(80);
        columna = tComprobantes.getColumn("NOTACREDITOOBJ");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tComprobantes = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDesde = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHasta = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnNuevo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtContador = new javax.swing.JTextField();
        btnExportar = new javax.swing.JButton();

        setClosable(true);
        setTitle("VALE ACADÉMICO");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/icono.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 600));

        tComprobantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OBJ", "NRO", "VALE", "FECHA DESDE", "FECHA HASTA", "CLIENTE", "MONTO", "NOTACREDITOOBJ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tComprobantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tComprobantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tComprobantes);

        btnBuscar.setBackground(new java.awt.Color(204, 204, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/buscar10.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("NRO:");

        txtNro.setToolTipText("");
        txtNro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroKeyTyped(evt);
            }
        });

        jLabel3.setText("FECHA INICIO:");

        jLabel4.setText("DESDE:");

        jLabel5.setText("HASTA:");

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(204, 204, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/requerimiento_nuevo.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel6.setText("CONTADOR:");

        txtContador.setToolTipText("");
        txtContador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContadorKeyTyped(evt);
            }
        });

        btnExportar.setBackground(new java.awt.Color(204, 204, 255));
        btnExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/excel10.png"))); // NOI18N
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNro, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtContador, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addComponent(btnExportar, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jButton2)
                                    .addComponent(jLabel5)
                                    .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3))))
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DocumentoPagoBO dpBO = DocumentoPagoBO.getInstance();
        String filtro = "";
        try {
            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat fBusqueda = new SimpleDateFormat("yyyyMMdd");
            if (txtDesde.getText().trim().length() > 0) {
                filtro = filtro + " AND va.fecha_Inicio >= '" + fBusqueda.format(f.parse(txtDesde.getText())) + "' ";
            }
            if (txtHasta.getText().trim().length() > 0) {
                filtro = filtro + " AND va.fecha_Inicio <= '" + fBusqueda.format(f.parse(txtHasta.getText())) + "' ";
            }
        } catch (ParseException ex) {
            Logger.getLogger(frmValeAcademico.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (txtNro.getText().trim().length() > 0) {
            filtro = " AND va.nro = " + txtNro.getText().trim();
        }
        if (txtContador.getText().trim().length() > 0) {
            filtro = " AND c.PApePat + ' ' + c.PApeMat + ' ' + c.PNombre like '%" + txtContador.getText().trim() + "%'";
        }
        List<ValeAcademico> lValeAcademico = dpBO.buscarValeAcademico(filtro);
        DefaultTableModel modelDetalle = (DefaultTableModel) tComprobantes.getModel();
        int contador = 0;
        modelDetalle.setRowCount(0);
        for (ValeAcademico va  : lValeAcademico) {
            modelDetalle.setNumRows(contador);
            modelDetalle.addRow(new Object[contador]);
            tComprobantes.setValueAt(va, contador, 0);
            tComprobantes.setValueAt(contador + 1, contador, 1);
            tComprobantes.setValueAt(String.format("%07d", va.getNro()), contador, 2);
            SimpleDateFormat formateador = new SimpleDateFormat("yyyy-MM-dd");
            tComprobantes.setValueAt(formateador.format(va.getFechaInicio()), contador, 3);
            tComprobantes.setValueAt(formateador.format(va.getFechaFin()), contador, 4);
            if (va.getDocumentoPagoDetalle() != null) {
                Cliente c = null;
                if (va.getDocumentoPagoDetalle().getDocumentoPago().getClienteByIdContadorEmpresa() != null) {
                    SeguridadBO sBO = SeguridadBO.getINSTANCE();
                    c = (Cliente) sBO.CargarObjeto("Cliente", va.getDocumentoPagoDetalle().getDocumentoPago().getClienteByIdContadorEmpresa().getIdCliente());
                } else {
                    c = va.getDocumentoPagoDetalle().getDocumentoPago().getCliente();
                }
                tComprobantes.setValueAt(c.getPapePat() + " " + c.getPapeMat() + " " + c.getPnombre(), contador, 5);
            }
            tComprobantes.setValueAt(va.getMonto(), contador, 6);
            contador++;
        }
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    private void CargarComprobante() {
        int fila = tComprobantes.getSelectedRow();
        ValeAcademico va  = (ValeAcademico) tComprobantes.getValueAt(fila, 0);
        SeguridadBO sBO = SeguridadBO.getInstance();
        Usuario usuario = (Usuario) sBO.CargarObjeto("Usuario", va.getUsuario().getIdUsuario());
        va.setUsuario(usuario);
        if (va.getDocumentoPagoDetalle() != null) {
            DocumentoPagoDet dpd = (DocumentoPagoDet) sBO.CargarObjeto("DocumentoPagoDet", va.getDocumentoPagoDetalle().getIdDocumentoPagoDet());
            va.setDocumentoPagoDetalle(dpd);
            DocumentoPago documentoPago = (DocumentoPago) sBO.CargarObjeto("DocumentoPago", va.getDocumentoPagoDetalle().getDocumentoPago().getIdDocumentoPago());
            va.getDocumentoPagoDetalle().setDocumentoPago(documentoPago);
            Cliente cliente = (Cliente) sBO.CargarObjeto("Cliente", va.getDocumentoPagoDetalle().getDocumentoPago().getCliente().getIdCliente());
            va.getDocumentoPagoDetalle().getDocumentoPago().setCliente(cliente);
            TipoDocSerie dp = (TipoDocSerie) sBO.CargarObjeto("TipoDocSerie", va.getDocumentoPagoDetalle().getDocumentoPago().getTipoDocSerie().getId());
            va.getDocumentoPagoDetalle().getDocumentoPago().setTipoDocSerie(dp);
            ConceptoPagoDetalle concepto = (ConceptoPagoDetalle) sBO.CargarObjeto("ConceptoPagoDetalle", va.getDocumentoPagoDetalle().getConceptoPagoDetalle().getIdConceptoPagoDetalle());
            va.getDocumentoPagoDetalle().setConceptoPagoDetalle(concepto);
            TipoDocPago td = (TipoDocPago) sBO.CargarObjeto("TipoDocPago", dp.getTipoDocPago().getIdTipoDocPago());
            va.getDocumentoPagoDetalle().getDocumentoPago().getTipoDocSerie().setTipoDocPago(td);
        }
        frmPrincipal f = (frmPrincipal) this.getParent().getParent().getParent().getParent().getParent();
        f.AbrirFormularioValeAcademico(va);
    }

    private void tComprobantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tComprobantesMouseClicked
        if (evt.getClickCount() == 2) {
            final frmPrincipal fPrin = (frmPrincipal) this.getParent().getParent().getParent().getParent().getParent();
            Thread queryThread = new Thread() {
                public void run() {
                    frmCargando fCargando = new frmCargando();
                    fPrin.AgregarFormulario(fCargando);
                    int x = (fPrin.getWidth() - fCargando.getWidth()) / 2;
                    int y = (fPrin.getHeight() - fCargando.getHeight()) / 2;
                    fCargando.setLocation(x, y);
                    fCargando.setVisible(true);
                    fCargando.toFront();
                    CargarComprobante();
                    fCargando.dispose();
                }
            };
            queryThread.start();
        }
    }//GEN-LAST:event_tComprobantesMouseClicked

    private void txtNroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNroKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DatePicker dtp = new DatePicker(this);
        if (!dtp.setPickedDate().isEmpty()) {
            txtDesde.setText(dtp.setPickedDate());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DatePicker dtp = new DatePicker(this);
        if (!dtp.setPickedDate().isEmpty()) {
            txtHasta.setText(dtp.setPickedDate());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        try {
            ValeAcademico nc = new ValeAcademico();
            nc.setBorrado("1");
            nc.setNro(0);
            SeguridadBO sBO = SeguridadBO.getInstance();
            Date ahora = sBO.ObtenerFechaServidor();
            nc.setFechaInicio(ahora);
            Calendar c = Calendar.getInstance();
            c.setTime(nc.getFechaInicio());
            c.add(Calendar.YEAR, 1);
//            nc.setFechaFin(c.getTime());
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            nc.setFechaFin(format.parse("31/12/2023"));
            nc.setMonto(0.0);
            frmPrincipal f = (frmPrincipal) this.getParent().getParent().getParent().getParent().getParent();
            f.AbrirFormularioValeAcademico(nc);
        } catch (ParseException ex) {
            Logger.getLogger(frmValeAcademico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtContadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContadorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContadorKeyTyped

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        String[] opciones = {"A nivel de vale academico", "A nivel de detalle de consumo"};
        String opcionSeleccionada = (String) JOptionPane.showInputDialog(this,
                "¿ Que exportacion desea realizar ?",
                "Elegir",
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]);
        if (opcionSeleccionada == null) {
            return;
        }
        DocumentoPagoBO dpBO = DocumentoPagoBO.getInstance();
        String filtro = "";
        String filtroDetalle = "";
        try {
            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat fBusqueda = new SimpleDateFormat("yyyyMMdd");
            if (txtDesde.getText().trim().length() > 0) {
                filtro = filtro + " AND va.fecha_inicio >= '" + fBusqueda.format(f.parse(txtDesde.getText())) + "' ";
                filtroDetalle = filtroDetalle + " AND va.valeAcademico.fechaInicio >= '" + fBusqueda.format(f.parse(txtDesde.getText())) + "' ";
            }
            if (txtHasta.getText().trim().length() > 0) {
                filtro = filtro + " AND va.fecha_inicio <= '" + fBusqueda.format(f.parse(txtHasta.getText())) + "' ";
                filtroDetalle = filtroDetalle + " AND va.valeAcademico.fechaInicio <= '" + fBusqueda.format(f.parse(txtHasta.getText())) + "' ";
            }
        } catch (ParseException ex) {
            Logger.getLogger(frmValeAcademico.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (txtNro.getText().trim().length() > 0) {
            filtro = filtro + " AND va.nro = " + txtNro.getText().trim();
            filtroDetalle = filtroDetalle + " AND va.valeAcademico.nro = " + txtNro.getText().trim();
        }
        if (txtContador.getText().trim().length() > 0) {
            filtro = filtro + " AND va.documentoPagoDetalle.documentoPago.cliente.papePat + ' ' + va.documentoPagoDetalle.documentoPago.cliente.papeMat + ' ' + va.documentoPagoDetalle.documentoPago.cliente.pnombre like '%" + txtContador.getText().trim() + "%'";
            filtroDetalle = filtroDetalle + " AND va.valeAcademico.documentoPagoDetalle.documentoPago.cliente.papePat + ' ' + va.valeAcademico.documentoPagoDetalle.documentoPago.cliente.papeMat + ' ' + va.valeAcademico.documentoPagoDetalle.documentoPago.cliente.pnombre like '%" + txtContador.getText().trim() + "%'";
        }
        if (opcionSeleccionada.equals("A nivel de vale academico")) {
            List<ValeAcademico> lValeAcademico = dpBO.buscarValeAcademico(filtro);
            dpBO.exportarValeAcademico(lValeAcademico);
        } else {
            if (opcionSeleccionada.equals("A nivel de detalle de consumo")) {
                List<ValeAcademico> lValeAcademico = dpBO.buscarValeAcademico(filtro);
                dpBO.exportarValeAcademicoDetalle(lValeAcademico);
            }
        }
    }//GEN-LAST:event_btnExportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tComprobantes;
    private javax.swing.JTextField txtContador;
    private javax.swing.JTextField txtDesde;
    private javax.swing.JTextField txtHasta;
    private javax.swing.JTextField txtNro;
    // End of variables declaration//GEN-END:variables
}
