package caja.mapeo.entidades;
// Generated 30/10/2019 08:16:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AsignacionEvento generated by hbm2java
 */
public class AsignacionEvento  implements java.io.Serializable {


     private int id;
     private Evento evento;
     private Expositor expositor;
     private String borrado;
     private Set participantes = new HashSet(0);

    public AsignacionEvento() {
    }

	
    public AsignacionEvento(int id, Evento evento, Expositor expositor) {
        this.id = id;
        this.evento = evento;
        this.expositor = expositor;
    }
    public AsignacionEvento(int id, Evento evento, Expositor expositor, String borrado, Set participantes) {
       this.id = id;
       this.evento = evento;
       this.expositor = expositor;
       this.borrado = borrado;
       this.participantes = participantes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public Expositor getExpositor() {
        return this.expositor;
    }
    
    public void setExpositor(Expositor expositor) {
        this.expositor = expositor;
    }
    public String getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(String borrado) {
        this.borrado = borrado;
    }
    public Set getParticipantes() {
        return this.participantes;
    }
    
    public void setParticipantes(Set participantes) {
        this.participantes = participantes;
    }




}


