package caja.mapeo.entidades;
// Generated 15/10/2016 10:02:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CcfinanExport generated by hbm2java
 */
public class CcfinanExport  implements java.io.Serializable {


     private int id;
     private String matri;
     private String numer;
     private String tipop;
     private Date fepag;
     private Double impag;
     private Double saldo;
     private Double nctas;
     private Double cuota;
     private String mesDesde;
     private Double anioDesde;
     private String mesHasta;
     private Double anioHasta;

    public CcfinanExport() {
    }

	
    public CcfinanExport(int id) {
        this.id = id;
    }
    public CcfinanExport(int id, String matri, String numer, String tipop, Date fepag, Double impag, Double saldo, Double nctas, Double cuota, String mesDesde, Double anioDesde, String mesHasta, Double anioHasta) {
       this.id = id;
       this.matri = matri;
       this.numer = numer;
       this.tipop = tipop;
       this.fepag = fepag;
       this.impag = impag;
       this.saldo = saldo;
       this.nctas = nctas;
       this.cuota = cuota;
       this.mesDesde = mesDesde;
       this.anioDesde = anioDesde;
       this.mesHasta = mesHasta;
       this.anioHasta = anioHasta;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMatri() {
        return this.matri;
    }
    
    public void setMatri(String matri) {
        this.matri = matri;
    }
    public String getNumer() {
        return this.numer;
    }
    
    public void setNumer(String numer) {
        this.numer = numer;
    }
    public String getTipop() {
        return this.tipop;
    }
    
    public void setTipop(String tipop) {
        this.tipop = tipop;
    }
    public Date getFepag() {
        return this.fepag;
    }
    
    public void setFepag(Date fepag) {
        this.fepag = fepag;
    }
    public Double getImpag() {
        return this.impag;
    }
    
    public void setImpag(Double impag) {
        this.impag = impag;
    }
    public Double getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Double saldo) {
        this.saldo = saldo;
    }
    public Double getNctas() {
        return this.nctas;
    }
    
    public void setNctas(Double nctas) {
        this.nctas = nctas;
    }
    public Double getCuota() {
        return this.cuota;
    }
    
    public void setCuota(Double cuota) {
        this.cuota = cuota;
    }
    public String getMesDesde() {
        return this.mesDesde;
    }
    
    public void setMesDesde(String mesDesde) {
        this.mesDesde = mesDesde;
    }
    public Double getAnioDesde() {
        return this.anioDesde;
    }
    
    public void setAnioDesde(Double anioDesde) {
        this.anioDesde = anioDesde;
    }
    public String getMesHasta() {
        return this.mesHasta;
    }
    
    public void setMesHasta(String mesHasta) {
        this.mesHasta = mesHasta;
    }
    public Double getAnioHasta() {
        return this.anioHasta;
    }
    
    public void setAnioHasta(Double anioHasta) {
        this.anioHasta = anioHasta;
    }




}


