package caja.mapeo.entidades;
// Generated 15/10/2016 10:02:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

    private int idCliente;
    private TipoDocIdentidad tipoDocIdentidad;
    private UbigeoDistrito ubigeoDistritoByPidDistritoTra;
    private UbigeoDistrito ubigeoDistritoByPidDistritoDom;
    private String pnombre;
    private String papePat;
    private String papeMat;
    private String pdni;
    private String pnroDocumento;
    private String psexo;
    private Date pfechaNac;
    private String pdireccionDomicilio;
    private String pdireccionTrabajo;
    private String ptelefonoDomicilio;
    private String ptelefonoTrabajo;
    private String ptelefonoTrabajo1;
    private String ptelefonoCelular;
    private String ptelefonoCelular1;
    private String ccodigoCole;
    private String cctaCte;
    private String cuniversidad;
    private Date cfechaAfiliacion;
    private String cemail;
    private String pemail;
    private String cemailAlternativo;
    private String cbuzon;
    private String clugarCobranza;
    private String cobservacion;
    private String estadoCivil;
    private String cobcodigoCobrador;
    private Integer cdepDomicilio;
    private Integer cproDomicilio;
    private Integer cdisDomicilio;
    private Integer clocaDomicilio;
    private Integer cdepTrabajo;
    private Integer cproTrabajo;
    private Integer cdisTrabajo;
    private Integer clocaTrabajo;
    private String ccentroTrabajo;
    private String scodigoSoc;
    private String sruc;
    private Date sfechaAfiliacion;
    private String scondicion;
    private String snroCta;
    private Date sfechaPagos;
    private String semail;
    private String semailAlternativo;
    private String snombreSociedad;
    private String sdireccion;
    private String stelefonoFijo;
    private String stelefonoCelular;
    private String spaginaWeb;
    private String sobservacion;
    private String sciudad;
    private Integer sdepartamento;
    private Integer sprovincia;
    private Integer sdistrito;
    private String scobrador;
    private String eruc;
    private String enombre;
    private String enroCta;
    private String ebanco;
    private String econdicion;
    private String edireccion;
    private String etelefonoFijo;
    private String etelefonoCelular;
    private String eciudad;
    private String eemail;
    private Integer edepDomicilio;
    private Integer eproDomicilio;
    private Integer edisDomicilio;
    private String tipoCliente;
    private String estado;
    private String cesCertificado;
    private String cpasswd;
    private String cnroCertificacion;
    private String cmatAuditor;
    private String cestaActivo;
    private String eliminadoApp;
    private String esEstudioContable;
    private String lugarNacimiento;
    private String paginaWeb;
    private String nacionalidad;
    private Date fechaOptoTitulo;
    private Date fechaOptoGradoBachiller;
    private Universidad universidadTitulo;
    private Universidad universidadEstudios;
    private String modalidadObtencionTitulo;
    private String estudiosEspecializacion;
    private String otrosEstudios;
    private String becasObtenidas;
    private String correspondenciaFisica;
    private String actividadesCulturales;
    private String temasGustariaRecibirCapacitacion;
    private String nombreConyugue;
    private String nombreHijos;
    private String publicidad;
    private FichaDatos fichaDatos;
    private Set clienteCertificados = new HashSet(0);
    private Set usuarios = new HashSet(0);
    private Set documentoPagosForIdContadorEmpresa = new HashSet(0);
    private Set alumnoses = new HashSet(0);
    private Set deudas = new HashSet(0);
    private Set financiamientos = new HashSet(0);
    private Set cuotases = new HashSet(0);
    private Set pagoDeMases = new HashSet(0);
    private Set reincorporacions = new HashSet(0);
    private Set cobradors = new HashSet(0);
    private Set cuentaCorrientes = new HashSet(0);
    private Set documentoPagosForIdCliente = new HashSet(0);
    private Set gastoses = new HashSet(0);
    private Set emailings = new HashSet(0);
    private Set emailings_1 = new HashSet(0);
    private Set clienteDerechoHabientes = new HashSet(0);
    private Set clienteEstudioContables = new HashSet(0);
    private Set constanciaHabilitacions = new HashSet(0);

    public Cliente() {
    }

    public Cliente(int idCliente) {
        this.idCliente = idCliente;
    }

    public Cliente(int idCliente, TipoDocIdentidad tipoDocIdentidad, UbigeoDistrito ubigeoDistritoByPidDistritoTra, UbigeoDistrito ubigeoDistritoByPidDistritoDom, String pnombre, String papePat, String papeMat, String pdni, String pnroDocumento, String psexo, Date pfechaNac, String pdireccionDomicilio, String pdireccionTrabajo, String ptelefonoDomicilio, String ptelefonoTrabajo, String ptelefonoTrabajo1, String ptelefonoCelular, String ptelefonoCelular1, String ccodigoCole, String cctaCte, String cuniversidad, Date cfechaAfiliacion, String cemail, String cemailAlternativo, String cbuzon, String clugarCobranza, String cobservacion, String cobcodigoCobrador, Integer cdepDomicilio, Integer cproDomicilio, Integer cdisDomicilio, Integer clocaDomicilio, Integer cdepTrabajo, Integer cproTrabajo, Integer cdisTrabajo, Integer clocaTrabajo, String ccentroTrabajo, String scodigoSoc, String sruc, Date sfechaAfiliacion, String scondicion, String snroCta, Date sfechaPagos, String semail, String semailAlternativo, String snombreSociedad, String sdireccion, String stelefonoFijo, String stelefonoCelular, String spaginaWeb, String sobservacion, String sciudad, Integer sdepartamento, Integer sprovincia, Integer sdistrito, String scobrador, String eruc, String enombre, String enroCta, String ebanco, String econdicion, String edireccion, String etelefonoFijo, String etelefonoCelular, String eciudad, String eemail, String tipoCliente, String estado, String cesCertificado, String cpasswd, String cnroCertificacion, String cmatAuditor, String cestaActivo, Set usuarios, Set documentoPagosForIdContadorEmpresa, Set alumnoses, Set deudas, Set financiamientos, Set cuotases, Set pagoDeMases, Set reincorporacions, Set cobradors, Set cuentaCorrientes, Set documentoPagosForIdCliente, Set gastoses) {
        this.idCliente = idCliente;
        this.tipoDocIdentidad = tipoDocIdentidad;
        this.ubigeoDistritoByPidDistritoTra = ubigeoDistritoByPidDistritoTra;
        this.ubigeoDistritoByPidDistritoDom = ubigeoDistritoByPidDistritoDom;
        this.pnombre = pnombre;
        this.papePat = papePat;
        this.papeMat = papeMat;
        this.pdni = pdni;
        this.pnroDocumento = pnroDocumento;
        this.psexo = psexo;
        this.pfechaNac = pfechaNac;
        this.pdireccionDomicilio = pdireccionDomicilio;
        this.pdireccionTrabajo = pdireccionTrabajo;
        this.ptelefonoDomicilio = ptelefonoDomicilio;
        this.ptelefonoTrabajo = ptelefonoTrabajo;
        this.ptelefonoTrabajo1 = ptelefonoTrabajo1;
        this.ptelefonoCelular = ptelefonoCelular;
        this.ptelefonoCelular1 = ptelefonoCelular1;
        this.ccodigoCole = ccodigoCole;
        this.cctaCte = cctaCte;
        this.cuniversidad = cuniversidad;
        this.cfechaAfiliacion = cfechaAfiliacion;
        this.cemail = cemail;
        this.cemailAlternativo = cemailAlternativo;
        this.cbuzon = cbuzon;
        this.clugarCobranza = clugarCobranza;
        this.cobservacion = cobservacion;
        this.cobcodigoCobrador = cobcodigoCobrador;
        this.cdepDomicilio = cdepDomicilio;
        this.cproDomicilio = cproDomicilio;
        this.cdisDomicilio = cdisDomicilio;
        this.clocaDomicilio = clocaDomicilio;
        this.cdepTrabajo = cdepTrabajo;
        this.cproTrabajo = cproTrabajo;
        this.cdisTrabajo = cdisTrabajo;
        this.clocaTrabajo = clocaTrabajo;
        this.ccentroTrabajo = ccentroTrabajo;
        this.scodigoSoc = scodigoSoc;
        this.sruc = sruc;
        this.sfechaAfiliacion = sfechaAfiliacion;
        this.scondicion = scondicion;
        this.snroCta = snroCta;
        this.sfechaPagos = sfechaPagos;
        this.semail = semail;
        this.semailAlternativo = semailAlternativo;
        this.snombreSociedad = snombreSociedad;
        this.sdireccion = sdireccion;
        this.stelefonoFijo = stelefonoFijo;
        this.stelefonoCelular = stelefonoCelular;
        this.spaginaWeb = spaginaWeb;
        this.sobservacion = sobservacion;
        this.sciudad = sciudad;
        this.sdepartamento = sdepartamento;
        this.sprovincia = sprovincia;
        this.sdistrito = sdistrito;
        this.scobrador = scobrador;
        this.eruc = eruc;
        this.enombre = enombre;
        this.enroCta = enroCta;
        this.ebanco = ebanco;
        this.econdicion = econdicion;
        this.edireccion = edireccion;
        this.etelefonoFijo = etelefonoFijo;
        this.etelefonoCelular = etelefonoCelular;
        this.eciudad = eciudad;
        this.eemail = eemail;
        this.tipoCliente = tipoCliente;
        this.estado = estado;
        this.cesCertificado = cesCertificado;
        this.cpasswd = cpasswd;
        this.cnroCertificacion = cnroCertificacion;
        this.cmatAuditor = cmatAuditor;
        this.cestaActivo = cestaActivo;
        this.usuarios = usuarios;
        this.documentoPagosForIdContadorEmpresa = documentoPagosForIdContadorEmpresa;
        this.alumnoses = alumnoses;
        this.deudas = deudas;
        this.financiamientos = financiamientos;
        this.cuotases = cuotases;
        this.pagoDeMases = pagoDeMases;
        this.reincorporacions = reincorporacions;
        this.cobradors = cobradors;
        this.cuentaCorrientes = cuentaCorrientes;
        this.documentoPagosForIdCliente = documentoPagosForIdCliente;
        this.gastoses = gastoses;
    }

    public int getIdCliente() {
        return this.idCliente;
    }

    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    public TipoDocIdentidad getTipoDocIdentidad() {
        return this.tipoDocIdentidad;
    }

    public void setTipoDocIdentidad(TipoDocIdentidad tipoDocIdentidad) {
        this.tipoDocIdentidad = tipoDocIdentidad;
    }

    public UbigeoDistrito getUbigeoDistritoByPidDistritoTra() {
        return this.ubigeoDistritoByPidDistritoTra;
    }

    public void setUbigeoDistritoByPidDistritoTra(UbigeoDistrito ubigeoDistritoByPidDistritoTra) {
        this.ubigeoDistritoByPidDistritoTra = ubigeoDistritoByPidDistritoTra;
    }

    public UbigeoDistrito getUbigeoDistritoByPidDistritoDom() {
        return this.ubigeoDistritoByPidDistritoDom;
    }

    public void setUbigeoDistritoByPidDistritoDom(UbigeoDistrito ubigeoDistritoByPidDistritoDom) {
        this.ubigeoDistritoByPidDistritoDom = ubigeoDistritoByPidDistritoDom;
    }

    public String getPnombre() {
        return this.pnombre;
    }

    public void setPnombre(String pnombre) {
        this.pnombre = pnombre;
    }

    public String getPapePat() {
        return this.papePat;
    }

    public void setPapePat(String papePat) {
        this.papePat = papePat;
    }

    public String getPapeMat() {
        return this.papeMat;
    }

    public void setPapeMat(String papeMat) {
        this.papeMat = papeMat;
    }

    public String getPdni() {
        return this.pdni;
    }

    public void setPdni(String pdni) {
        this.pdni = pdni;
    }

    public String getPnroDocumento() {
        return this.pnroDocumento;
    }

    public void setPnroDocumento(String pnroDocumento) {
        this.pnroDocumento = pnroDocumento;
    }

    public String getPsexo() {
        return this.psexo;
    }

    public void setPsexo(String psexo) {
        this.psexo = psexo;
    }

    public Date getPfechaNac() {
        return this.pfechaNac;
    }

    public void setPfechaNac(Date pfechaNac) {
        this.pfechaNac = pfechaNac;
    }

    public String getPdireccionDomicilio() {
        return this.pdireccionDomicilio;
    }

    public void setPdireccionDomicilio(String pdireccionDomicilio) {
        this.pdireccionDomicilio = pdireccionDomicilio;
    }

    public String getPdireccionTrabajo() {
        return this.pdireccionTrabajo;
    }

    public void setPdireccionTrabajo(String pdireccionTrabajo) {
        this.pdireccionTrabajo = pdireccionTrabajo;
    }

    public String getPtelefonoDomicilio() {
        return this.ptelefonoDomicilio;
    }

    public void setPtelefonoDomicilio(String ptelefonoDomicilio) {
        this.ptelefonoDomicilio = ptelefonoDomicilio;
    }

    public String getPtelefonoTrabajo() {
        return this.ptelefonoTrabajo;
    }

    public void setPtelefonoTrabajo(String ptelefonoTrabajo) {
        this.ptelefonoTrabajo = ptelefonoTrabajo;
    }

    public String getPtelefonoTrabajo1() {
        return this.ptelefonoTrabajo1;
    }

    public void setPtelefonoTrabajo1(String ptelefonoTrabajo1) {
        this.ptelefonoTrabajo1 = ptelefonoTrabajo1;
    }

    public String getPtelefonoCelular() {
        return this.ptelefonoCelular;
    }

    public void setPtelefonoCelular(String ptelefonoCelular) {
        this.ptelefonoCelular = ptelefonoCelular;
    }

    public String getPtelefonoCelular1() {
        return this.ptelefonoCelular1;
    }

    public void setPtelefonoCelular1(String ptelefonoCelular1) {
        this.ptelefonoCelular1 = ptelefonoCelular1;
    }

    public String getCcodigoCole() {
        return this.ccodigoCole;
    }

    public void setCcodigoCole(String ccodigoCole) {
        this.ccodigoCole = ccodigoCole;
    }

    public String getCctaCte() {
        return this.cctaCte;
    }

    public void setCctaCte(String cctaCte) {
        this.cctaCte = cctaCte;
    }

    public String getCuniversidad() {
        return this.cuniversidad;
    }

    public void setCuniversidad(String cuniversidad) {
        this.cuniversidad = cuniversidad;
    }

    public Date getCfechaAfiliacion() {
        return this.cfechaAfiliacion;
    }

    public void setCfechaAfiliacion(Date cfechaAfiliacion) {
        this.cfechaAfiliacion = cfechaAfiliacion;
    }

    public String getCemail() {
        return this.cemail;
    }

    public void setCemail(String cemail) {
        this.cemail = cemail;
    }

    public String getCemailAlternativo() {
        return this.cemailAlternativo;
    }

    public void setCemailAlternativo(String cemailAlternativo) {
        this.cemailAlternativo = cemailAlternativo;
    }

    public String getCbuzon() {
        return this.cbuzon;
    }

    public void setCbuzon(String cbuzon) {
        this.cbuzon = cbuzon;
    }

    public String getClugarCobranza() {
        return this.clugarCobranza;
    }

    public void setClugarCobranza(String clugarCobranza) {
        this.clugarCobranza = clugarCobranza;
    }

    public String getCobservacion() {
        return this.cobservacion;
    }

    public void setCobservacion(String cobservacion) {
        this.cobservacion = cobservacion;
    }

    public String getCobcodigoCobrador() {
        return this.cobcodigoCobrador;
    }

    public void setCobcodigoCobrador(String cobcodigoCobrador) {
        this.cobcodigoCobrador = cobcodigoCobrador;
    }

    public Integer getCdepDomicilio() {
        return this.cdepDomicilio;
    }

    public void setCdepDomicilio(Integer cdepDomicilio) {
        this.cdepDomicilio = cdepDomicilio;
    }

    public Integer getCproDomicilio() {
        return this.cproDomicilio;
    }

    public void setCproDomicilio(Integer cproDomicilio) {
        this.cproDomicilio = cproDomicilio;
    }

    public Integer getCdisDomicilio() {
        return this.cdisDomicilio;
    }

    public void setCdisDomicilio(Integer cdisDomicilio) {
        this.cdisDomicilio = cdisDomicilio;
    }

    public Integer getClocaDomicilio() {
        return this.clocaDomicilio;
    }

    public void setClocaDomicilio(Integer clocaDomicilio) {
        this.clocaDomicilio = clocaDomicilio;
    }

    public Integer getCdepTrabajo() {
        return this.cdepTrabajo;
    }

    public void setCdepTrabajo(Integer cdepTrabajo) {
        this.cdepTrabajo = cdepTrabajo;
    }

    public Integer getCproTrabajo() {
        return this.cproTrabajo;
    }

    public void setCproTrabajo(Integer cproTrabajo) {
        this.cproTrabajo = cproTrabajo;
    }

    public Integer getCdisTrabajo() {
        return this.cdisTrabajo;
    }

    public void setCdisTrabajo(Integer cdisTrabajo) {
        this.cdisTrabajo = cdisTrabajo;
    }

    public Integer getClocaTrabajo() {
        return this.clocaTrabajo;
    }

    public void setClocaTrabajo(Integer clocaTrabajo) {
        this.clocaTrabajo = clocaTrabajo;
    }

    public String getCcentroTrabajo() {
        return this.ccentroTrabajo;
    }

    public void setCcentroTrabajo(String ccentroTrabajo) {
        this.ccentroTrabajo = ccentroTrabajo;
    }

    public String getScodigoSoc() {
        return this.scodigoSoc;
    }

    public void setScodigoSoc(String scodigoSoc) {
        this.scodigoSoc = scodigoSoc;
    }

    public String getSruc() {
        return this.sruc;
    }

    public void setSruc(String sruc) {
        this.sruc = sruc;
    }

    public Date getSfechaAfiliacion() {
        return this.sfechaAfiliacion;
    }

    public void setSfechaAfiliacion(Date sfechaAfiliacion) {
        this.sfechaAfiliacion = sfechaAfiliacion;
    }

    public String getScondicion() {
        return this.scondicion;
    }

    public void setScondicion(String scondicion) {
        this.scondicion = scondicion;
    }

    public String getSnroCta() {
        return this.snroCta;
    }

    public void setSnroCta(String snroCta) {
        this.snroCta = snroCta;
    }

    public Date getSfechaPagos() {
        return this.sfechaPagos;
    }

    public void setSfechaPagos(Date sfechaPagos) {
        this.sfechaPagos = sfechaPagos;
    }

    public String getSemail() {
        return this.semail;
    }

    public void setSemail(String semail) {
        this.semail = semail;
    }

    public String getSemailAlternativo() {
        return this.semailAlternativo;
    }

    public void setSemailAlternativo(String semailAlternativo) {
        this.semailAlternativo = semailAlternativo;
    }

    public String getSnombreSociedad() {
        return this.snombreSociedad;
    }

    public void setSnombreSociedad(String snombreSociedad) {
        this.snombreSociedad = snombreSociedad;
    }

    public String getSdireccion() {
        return this.sdireccion;
    }

    public void setSdireccion(String sdireccion) {
        this.sdireccion = sdireccion;
    }

    public String getStelefonoFijo() {
        return this.stelefonoFijo;
    }

    public void setStelefonoFijo(String stelefonoFijo) {
        this.stelefonoFijo = stelefonoFijo;
    }

    public String getStelefonoCelular() {
        return this.stelefonoCelular;
    }

    public void setStelefonoCelular(String stelefonoCelular) {
        this.stelefonoCelular = stelefonoCelular;
    }

    public String getSpaginaWeb() {
        return this.spaginaWeb;
    }

    public void setSpaginaWeb(String spaginaWeb) {
        this.spaginaWeb = spaginaWeb;
    }

    public String getSobservacion() {
        return this.sobservacion;
    }

    public void setSobservacion(String sobservacion) {
        this.sobservacion = sobservacion;
    }

    public String getSciudad() {
        return this.sciudad;
    }

    public void setSciudad(String sciudad) {
        this.sciudad = sciudad;
    }

    public Integer getSdepartamento() {
        return this.sdepartamento;
    }

    public void setSdepartamento(Integer sdepartamento) {
        this.sdepartamento = sdepartamento;
    }

    public Integer getSprovincia() {
        return this.sprovincia;
    }

    public void setSprovincia(Integer sprovincia) {
        this.sprovincia = sprovincia;
    }

    public Integer getSdistrito() {
        return this.sdistrito;
    }

    public void setSdistrito(Integer sdistrito) {
        this.sdistrito = sdistrito;
    }

    public String getScobrador() {
        return this.scobrador;
    }

    public void setScobrador(String scobrador) {
        this.scobrador = scobrador;
    }

    public String getEruc() {
        return this.eruc;
    }

    public void setEruc(String eruc) {
        this.eruc = eruc;
    }

    public String getEnombre() {
        return this.enombre;
    }

    public void setEnombre(String enombre) {
        this.enombre = enombre;
    }

    public String getEnroCta() {
        return this.enroCta;
    }

    public void setEnroCta(String enroCta) {
        this.enroCta = enroCta;
    }

    public String getEbanco() {
        return this.ebanco;
    }

    public void setEbanco(String ebanco) {
        this.ebanco = ebanco;
    }

    public String getEcondicion() {
        return this.econdicion;
    }

    public void setEcondicion(String econdicion) {
        this.econdicion = econdicion;
    }

    public String getEdireccion() {
        return this.edireccion;
    }

    public void setEdireccion(String edireccion) {
        this.edireccion = edireccion;
    }

    public String getEtelefonoFijo() {
        return this.etelefonoFijo;
    }

    public void setEtelefonoFijo(String etelefonoFijo) {
        this.etelefonoFijo = etelefonoFijo;
    }

    public String getEtelefonoCelular() {
        return this.etelefonoCelular;
    }

    public void setEtelefonoCelular(String etelefonoCelular) {
        this.etelefonoCelular = etelefonoCelular;
    }

    public String getEciudad() {
        return this.eciudad;
    }

    public void setEciudad(String eciudad) {
        this.eciudad = eciudad;
    }

    public String getEemail() {
        return this.eemail;
    }

    public void setEemail(String eemail) {
        this.eemail = eemail;
    }

    public String getTipoCliente() {
        return this.tipoCliente;
    }

    public void setTipoCliente(String tipoCliente) {
        this.tipoCliente = tipoCliente;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getCesCertificado() {
        return this.cesCertificado;
    }

    public void setCesCertificado(String cesCertificado) {
        this.cesCertificado = cesCertificado;
    }

    public String getCpasswd() {
        return this.cpasswd;
    }

    public void setCpasswd(String cpasswd) {
        this.cpasswd = cpasswd;
    }

    public String getCnroCertificacion() {
        return this.cnroCertificacion;
    }

    public void setCnroCertificacion(String cnroCertificacion) {
        this.cnroCertificacion = cnroCertificacion;
    }

    public String getCmatAuditor() {
        return this.cmatAuditor;
    }

    public void setCmatAuditor(String cmatAuditor) {
        this.cmatAuditor = cmatAuditor;
    }

    public String getCestaActivo() {
        return this.cestaActivo;
    }

    public void setCestaActivo(String cestaActivo) {
        this.cestaActivo = cestaActivo;
    }

    public Set getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

    public Set getDocumentoPagosForIdContadorEmpresa() {
        return this.documentoPagosForIdContadorEmpresa;
    }

    public void setDocumentoPagosForIdContadorEmpresa(Set documentoPagosForIdContadorEmpresa) {
        this.documentoPagosForIdContadorEmpresa = documentoPagosForIdContadorEmpresa;
    }

    public Set getAlumnoses() {
        return this.alumnoses;
    }

    public void setAlumnoses(Set alumnoses) {
        this.alumnoses = alumnoses;
    }

    public Set getDeudas() {
        return this.deudas;
    }

    public void setDeudas(Set deudas) {
        this.deudas = deudas;
    }

    public Set getFinanciamientos() {
        return this.financiamientos;
    }

    public void setFinanciamientos(Set financiamientos) {
        this.financiamientos = financiamientos;
    }

    public Set getCuotases() {
        return this.cuotases;
    }

    public void setCuotases(Set cuotases) {
        this.cuotases = cuotases;
    }

    public Set getPagoDeMases() {
        return this.pagoDeMases;
    }

    public void setPagoDeMases(Set pagoDeMases) {
        this.pagoDeMases = pagoDeMases;
    }

    public Set getReincorporacions() {
        return this.reincorporacions;
    }

    public void setReincorporacions(Set reincorporacions) {
        this.reincorporacions = reincorporacions;
    }

    public Set getCobradors() {
        return this.cobradors;
    }

    public void setCobradors(Set cobradors) {
        this.cobradors = cobradors;
    }

    public Set getCuentaCorrientes() {
        return this.cuentaCorrientes;
    }

    public void setCuentaCorrientes(Set cuentaCorrientes) {
        this.cuentaCorrientes = cuentaCorrientes;
    }

    public Set getDocumentoPagosForIdCliente() {
        return this.documentoPagosForIdCliente;
    }

    public void setDocumentoPagosForIdCliente(Set documentoPagosForIdCliente) {
        this.documentoPagosForIdCliente = documentoPagosForIdCliente;
    }

    public Set getGastoses() {
        return this.gastoses;
    }

    public void setGastoses(Set gastoses) {
        this.gastoses = gastoses;
    }

    public String getPemail() {
        return pemail;
    }

    public void setPemail(String pemail) {
        this.pemail = pemail;
    }

    public Set getClienteCertificados() {
        return clienteCertificados;
    }

    public void setClienteCertificados(Set clienteCertificados) {
        this.clienteCertificados = clienteCertificados;
    }

    public Set getEmailings() {
        return emailings;
    }

    public void setEmailings(Set emailings) {
        this.emailings = emailings;
    }

    public Set getClienteDerechoHabientes() {
        return clienteDerechoHabientes;
    }

    public void setClienteDerechoHabientes(Set clienteDerechoHabientes) {
        this.clienteDerechoHabientes = clienteDerechoHabientes;
    }

    public String getEstadoCivil() {
        return estadoCivil;
    }

    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    public Set getConstanciaHabilitacions() {
        return constanciaHabilitacions;
    }

    public void setConstanciaHabilitacions(Set constanciaHabilitacions) {
        this.constanciaHabilitacions = constanciaHabilitacions;
    }

    public String getEliminadoApp() {
        return eliminadoApp;
    }

    public void setEliminadoApp(String eliminadoApp) {
        this.eliminadoApp = eliminadoApp;
    }

    public Integer getEdepDomicilio() {
        return edepDomicilio;
    }

    public void setEdepDomicilio(Integer edepDomicilio) {
        this.edepDomicilio = edepDomicilio;
    }

    public Integer getEproDomicilio() {
        return eproDomicilio;
    }

    public void setEproDomicilio(Integer eproDomicilio) {
        this.eproDomicilio = eproDomicilio;
    }

    public Integer getEdisDomicilio() {
        return edisDomicilio;
    }

    public void setEdisDomicilio(Integer edisDomicilio) {
        this.edisDomicilio = edisDomicilio;
    }

    public String getEsEstudioContable() {
        return esEstudioContable;
    }

    public void setEsEstudioContable(String esEstudioContable) {
        this.esEstudioContable = esEstudioContable;
    }

    public Set getClienteEstudioContables() {
        return clienteEstudioContables;
    }

    public void setClienteEstudioContables(Set clienteEstudioContables) {
        this.clienteEstudioContables = clienteEstudioContables;
    }

    public String getLugarNacimiento() {
        return lugarNacimiento;
    }

    public void setLugarNacimiento(String lugarNacimiento) {
        this.lugarNacimiento = lugarNacimiento;
    }

    public String getPaginaWeb() {
        return paginaWeb;
    }

    public void setPaginaWeb(String paginaWeb) {
        this.paginaWeb = paginaWeb;
    }

    public Date getFechaOptoTitulo() {
        return fechaOptoTitulo;
    }

    public void setFechaOptoTitulo(Date fechaOptoTitulo) {
        this.fechaOptoTitulo = fechaOptoTitulo;
    }

    public Date getFechaOptoGradoBachiller() {
        return fechaOptoGradoBachiller;
    }

    public void setFechaOptoGradoBachiller(Date fechaOptoGradoBachiller) {
        this.fechaOptoGradoBachiller = fechaOptoGradoBachiller;
    }

    public String getModalidadObtencionTitulo() {
        return modalidadObtencionTitulo;
    }

    public void setModalidadObtencionTitulo(String modalidadObtencionTitulo) {
        this.modalidadObtencionTitulo = modalidadObtencionTitulo;
    }

    public String getEstudiosEspecializacion() {
        return estudiosEspecializacion;
    }

    public void setEstudiosEspecializacion(String estudiosEspecializacion) {
        this.estudiosEspecializacion = estudiosEspecializacion;
    }

    public String getOtrosEstudios() {
        return otrosEstudios;
    }

    public void setOtrosEstudios(String otrosEstudios) {
        this.otrosEstudios = otrosEstudios;
    }

    public String getBecasObtenidas() {
        return becasObtenidas;
    }

    public void setBecasObtenidas(String becasObtenidas) {
        this.becasObtenidas = becasObtenidas;
    }

    public String getCorrespondenciaFisica() {
        return correspondenciaFisica;
    }

    public void setCorrespondenciaFisica(String correspondenciaFisica) {
        this.correspondenciaFisica = correspondenciaFisica;
    }

    public FichaDatos getFichaDatos() {
        return fichaDatos;
    }

    public void setFichaDatos(FichaDatos fichaDatos) {
        this.fichaDatos = fichaDatos;
    }

    public String getActividadesCulturales() {
        return actividadesCulturales;
    }

    public void setActividadesCulturales(String actividadesCulturales) {
        this.actividadesCulturales = actividadesCulturales;
    }

    public String getNacionalidad() {
        return nacionalidad;
    }

    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    public String getTemasGustariaRecibirCapacitacion() {
        return temasGustariaRecibirCapacitacion;
    }

    public void setTemasGustariaRecibirCapacitacion(String temasGustariaRecibirCapacitacion) {
        this.temasGustariaRecibirCapacitacion = temasGustariaRecibirCapacitacion;
    }

    public String getNombreConyugue() {
        return nombreConyugue;
    }

    public void setNombreConyugue(String nombreConyugue) {
        this.nombreConyugue = nombreConyugue;
    }

    public String getNombreHijos() {
        return nombreHijos;
    }

    public void setNombreHijos(String nombreHijos) {
        this.nombreHijos = nombreHijos;
    }

    public String getPublicidad() {
        return publicidad;
    }

    public void setPublicidad(String publicidad) {
        this.publicidad = publicidad;
    }

    public Universidad getUniversidadTitulo() {
        return universidadTitulo;
    }

    public void setUniversidadTitulo(Universidad universidadTitulo) {
        this.universidadTitulo = universidadTitulo;
    }

    public Universidad getUniversidadEstudios() {
        return universidadEstudios;
    }

    public void setUniversidadEstudios(Universidad universidadEstudios) {
        this.universidadEstudios = universidadEstudios;
    }

}
