package caja.mapeo.entidades;
// Generated 15/10/2016 10:02:37 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Cliente generated by hbm2java
 */
public class ClienteEstudioContableEspecialidad {

    private int id;
    private ClienteEstudioContable clienteEstudioContable;
    private CurriculumTablaEspecialidades curriculumTablaEspecialidades;
    private String borrado; // Getters y setters 

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public ClienteEstudioContable getClienteEstudioContable() {
        return clienteEstudioContable;
    }

    public void setClienteEstudioContable(ClienteEstudioContable clienteEstudioContable) {
        this.clienteEstudioContable = clienteEstudioContable;
    }

    public CurriculumTablaEspecialidades getCurriculumTablaEspecialidades() {
        return curriculumTablaEspecialidades;
    }

    public void setCurriculumTablaEspecialidades(CurriculumTablaEspecialidades curriculumTablaEspecialidades) {
        this.curriculumTablaEspecialidades = curriculumTablaEspecialidades;
    }

    public String getBorrado() {
        return borrado;
    }

    public void setBorrado(String borrado) {
        this.borrado = borrado;
    }
}
