package caja.mapeo.entidades;
// Generated 15/10/2016 10:02:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * ConceptoPagoDetalle generated by hbm2java
 */
public class ConceptoPagoDetalle implements java.io.Serializable {

    private int idConceptoPagoDetalle;
    private String descripcion;
    private String observacion;
    private String cargo;
    private String abono;
    private String tipoCodigo;
    private String codigo;
    private String codigoPresupuesto;
    private String tieneIgv;
    private String estado;
    private String mostrarWeb;
    private Double porcentajeIgv;
    private Double porcentajeDetraccion;
    private TipoAfectacion tipoAfectacion;
    private CodigoBienServicioDetraccion codigoBienServicioDetraccion;
    private Set cuotases = new HashSet(0);
    private Set congresoConceptos = new HashSet(0);
    private Set documentoPagoDets = new HashSet(0);
    private Set docPagoAnuladoDetalles = new HashSet(0);
    private Set anioMesConceptos = new HashSet(0);
    private Set deudas = new HashSet(0);
    private Set eventoConceptoPagos = new HashSet(0);

    public ConceptoPagoDetalle() {
    }

    public ConceptoPagoDetalle(int idConceptoPagoDetalle, String descripcion) {
        this.idConceptoPagoDetalle = idConceptoPagoDetalle;
        this.descripcion = descripcion;
    }

    public ConceptoPagoDetalle(int idConceptoPagoDetalle, String descripcion, String observacion, String cargo, String abono, String tipoCodigo, String codigo, String tieneIgv, Double porcentajeIgv, Set cuotases, Set congresoConceptos, Set documentoPagoDets, Set docPagoAnuladoDetalles, Set anioMesConceptos, Set deudas) {
        this.idConceptoPagoDetalle = idConceptoPagoDetalle;
        this.descripcion = descripcion;
        this.observacion = observacion;
        this.cargo = cargo;
        this.abono = abono;
        this.tipoCodigo = tipoCodigo;
        this.codigo = codigo;
        this.tieneIgv = tieneIgv;
        this.porcentajeIgv = porcentajeIgv;
        this.cuotases = cuotases;
        this.congresoConceptos = congresoConceptos;
        this.documentoPagoDets = documentoPagoDets;
        this.docPagoAnuladoDetalles = docPagoAnuladoDetalles;
        this.anioMesConceptos = anioMesConceptos;
        this.deudas = deudas;
    }

    public int getIdConceptoPagoDetalle() {
        return this.idConceptoPagoDetalle;
    }

    public void setIdConceptoPagoDetalle(int idConceptoPagoDetalle) {
        this.idConceptoPagoDetalle = idConceptoPagoDetalle;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public String getCargo() {
        return this.cargo;
    }

    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    public String getAbono() {
        return this.abono;
    }

    public void setAbono(String abono) {
        this.abono = abono;
    }

    public String getTipoCodigo() {
        return this.tipoCodigo;
    }

    public void setTipoCodigo(String tipoCodigo) {
        this.tipoCodigo = tipoCodigo;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getTieneIgv() {
        return this.tieneIgv;
    }

    public void setTieneIgv(String tieneIgv) {
        this.tieneIgv = tieneIgv;
    }

    public Double getPorcentajeIgv() {
        return this.porcentajeIgv;
    }

    public void setPorcentajeIgv(Double porcentajeIgv) {
        this.porcentajeIgv = porcentajeIgv;
    }

    public Set getCuotases() {
        return this.cuotases;
    }

    public void setCuotases(Set cuotases) {
        this.cuotases = cuotases;
    }

    public Set getCongresoConceptos() {
        return this.congresoConceptos;
    }

    public void setCongresoConceptos(Set congresoConceptos) {
        this.congresoConceptos = congresoConceptos;
    }

    public Set getDocumentoPagoDets() {
        return this.documentoPagoDets;
    }

    public void setDocumentoPagoDets(Set documentoPagoDets) {
        this.documentoPagoDets = documentoPagoDets;
    }

    public Set getDocPagoAnuladoDetalles() {
        return this.docPagoAnuladoDetalles;
    }

    public void setDocPagoAnuladoDetalles(Set docPagoAnuladoDetalles) {
        this.docPagoAnuladoDetalles = docPagoAnuladoDetalles;
    }

    public Set getAnioMesConceptos() {
        return this.anioMesConceptos;
    }

    public void setAnioMesConceptos(Set anioMesConceptos) {
        this.anioMesConceptos = anioMesConceptos;
    }

    public Set getDeudas() {
        return this.deudas;
    }

    public void setDeudas(Set deudas) {
        this.deudas = deudas;
    }

    @Override
    public String toString() {
        return this.descripcion;
    }

    public TipoAfectacion getTipoAfectacion() {
        return tipoAfectacion;
    }

    public void setTipoAfectacion(TipoAfectacion tipoAfectacion) {
        this.tipoAfectacion = tipoAfectacion;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getMostrarWeb() {
        return mostrarWeb;
    }

    public void setMostrarWeb(String mostrarWeb) {
        this.mostrarWeb = mostrarWeb;
    }

    public Set getEventoConceptoPagos() {
        return eventoConceptoPagos;
    }

    public void setEventoConceptoPagos(Set eventoConceptoPagos) {
        this.eventoConceptoPagos = eventoConceptoPagos;
    }

    public String getCodigoPresupuesto() {
        return codigoPresupuesto;
    }

    public void setCodigoPresupuesto(String codigoPresupuesto) {
        this.codigoPresupuesto = codigoPresupuesto;
    }

    public Double getPorcentajeDetraccion() {
        return porcentajeDetraccion;
    }

    public void setPorcentajeDetraccion(Double porcentajeDetraccion) {
        this.porcentajeDetraccion = porcentajeDetraccion;
    }

    public CodigoBienServicioDetraccion getCodigoBienServicioDetraccion() {
        return codigoBienServicioDetraccion;
    }

    public void setCodigoBienServicioDetraccion(CodigoBienServicioDetraccion codigoBienServicioDetraccion) {
        this.codigoBienServicioDetraccion = codigoBienServicioDetraccion;
    }

}
