package caja.mapeo.entidades;
// Generated 15/10/2016 10:02:37 PM by Hibernate Tools 4.3.1



/**
 * Deuda generated by hbm2java
 */
public class Deuda  implements java.io.Serializable {


     private int id;
     private Cliente cliente;
     private ConceptoPagoDetalle conceptoPagoDetalle;
     private DocumentoPagoDet documentoPagoDet;
     private Double monto;
     private String estado;
     private String sePuedeFinanciar;
     private Double montoCancelado;
     private Integer idFinanciamientoNuevo;

    public Deuda() {
    }

	
    public Deuda(int id) {
        this.id = id;
    }
    public Deuda(int id, Cliente cliente, ConceptoPagoDetalle conceptoPagoDetalle, DocumentoPagoDet documentoPagoDet, Double monto, String estado, Double montoCancelado, Integer idFinanciamientoNuevo) {
       this.id = id;
       this.cliente = cliente;
       this.conceptoPagoDetalle = conceptoPagoDetalle;
       this.documentoPagoDet = documentoPagoDet;
       this.monto = monto;
       this.estado = estado;
       this.montoCancelado = montoCancelado;
       this.idFinanciamientoNuevo = idFinanciamientoNuevo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public ConceptoPagoDetalle getConceptoPagoDetalle() {
        return this.conceptoPagoDetalle;
    }
    
    public void setConceptoPagoDetalle(ConceptoPagoDetalle conceptoPagoDetalle) {
        this.conceptoPagoDetalle = conceptoPagoDetalle;
    }
    public DocumentoPagoDet getDocumentoPagoDet() {
        return this.documentoPagoDet;
    }
    
    public void setDocumentoPagoDet(DocumentoPagoDet documentoPagoDet) {
        this.documentoPagoDet = documentoPagoDet;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Double getMontoCancelado() {
        return this.montoCancelado;
    }
    
    public void setMontoCancelado(Double montoCancelado) {
        this.montoCancelado = montoCancelado;
    }
    public Integer getIdFinanciamientoNuevo() {
        return this.idFinanciamientoNuevo;
    }
    
    public void setIdFinanciamientoNuevo(Integer idFinanciamientoNuevo) {
        this.idFinanciamientoNuevo = idFinanciamientoNuevo;
    }

    public String getSePuedeFinanciar() {
        return sePuedeFinanciar;
    }

    public void setSePuedeFinanciar(String sePuedeFinanciar) {
        this.sePuedeFinanciar = sePuedeFinanciar;
    }




}


