package caja.mapeo.entidades;
// Generated 15/10/2016 10:02:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentoPagoDet generated by hbm2java
 */
public class DocumentoPagoDet implements java.io.Serializable {

    private int idDocumentoPagoDet;
    private ConceptoPagoDetalle conceptoPagoDetalle;
    private DocumentoPago documentoPago;
    private int cantidad;
    private double precioUnitario;
    private Integer anioDesde;
    private Integer mesDesde;
    private Integer anioHasta;
    private Integer mesHasta;
    private String observacion;
    private Double valorVenta;
    private Double precioVenta;
    private Double igv;
    private String tieneDescuento;
    private Double descuento;
    private Double igvPorcentaje;
    private Double porcentajeDetraccion;
    private Double montoDetraccion;
    private String codigoBienServicioDetraccion;
    private String glosa;
    private String codigoTipoTributo;
    private String codigoInternacionalTipoTributo;
    private String codigoTipoAfectacion;
    private String nombreTipoTributo;
    private Set alumnoses = new HashSet(0);
    private Set reincorporacionDocumentoPagos = new HashSet(0);
    private Set financiamientoDocumentoPagos = new HashSet(0);
    private Set cuotases = new HashSet(0);
    private Set deudas = new HashSet(0);
    private Set congresoParticipanteses = new HashSet(0);
    private Set cuentaCorrientes = new HashSet(0);
    private Set participantes = new HashSet(0);
    private Set valeAcademicos = new HashSet(0);
    private Set valeAcademicoConsumos = new HashSet(0);
    private Set constanciaHabilitacions = new HashSet(0);

    public DocumentoPagoDet() {
    }

    public DocumentoPagoDet(int idDocumentoPagoDet, ConceptoPagoDetalle conceptoPagoDetalle, DocumentoPago documentoPago, int cantidad, double precioUnitario) {
        this.idDocumentoPagoDet = idDocumentoPagoDet;
        this.conceptoPagoDetalle = conceptoPagoDetalle;
        this.documentoPago = documentoPago;
        this.cantidad = cantidad;
        this.precioUnitario = precioUnitario;
    }

    public DocumentoPagoDet(int idDocumentoPagoDet, ConceptoPagoDetalle conceptoPagoDetalle, DocumentoPago documentoPago, int cantidad, double precioUnitario, Integer anioDesde, Integer mesDesde, Integer anioHasta, Integer mesHasta, String observacion, Double valorVenta, Double precioVenta, Double igv, String tieneDescuento, Double descuento, String glosa, Set alumnoses, Set reincorporacionDocumentoPagos, Set financiamientoDocumentoPagos, Set cuotases, Set deudas, Set congresoParticipanteses, Set cuentaCorrientes) {
        this.idDocumentoPagoDet = idDocumentoPagoDet;
        this.conceptoPagoDetalle = conceptoPagoDetalle;
        this.documentoPago = documentoPago;
        this.cantidad = cantidad;
        this.precioUnitario = precioUnitario;
        this.anioDesde = anioDesde;
        this.mesDesde = mesDesde;
        this.anioHasta = anioHasta;
        this.mesHasta = mesHasta;
        this.observacion = observacion;
        this.valorVenta = valorVenta;
        this.precioVenta = precioVenta;
        this.igv = igv;
        this.tieneDescuento = tieneDescuento;
        this.descuento = descuento;
        this.glosa = glosa;
        this.alumnoses = alumnoses;
        this.reincorporacionDocumentoPagos = reincorporacionDocumentoPagos;
        this.financiamientoDocumentoPagos = financiamientoDocumentoPagos;
        this.cuotases = cuotases;
        this.deudas = deudas;
        this.congresoParticipanteses = congresoParticipanteses;
        this.cuentaCorrientes = cuentaCorrientes;
    }

    public int getIdDocumentoPagoDet() {
        return this.idDocumentoPagoDet;
    }

    public void setIdDocumentoPagoDet(int idDocumentoPagoDet) {
        this.idDocumentoPagoDet = idDocumentoPagoDet;
    }

    public ConceptoPagoDetalle getConceptoPagoDetalle() {
        return this.conceptoPagoDetalle;
    }

    public void setConceptoPagoDetalle(ConceptoPagoDetalle conceptoPagoDetalle) {
        this.conceptoPagoDetalle = conceptoPagoDetalle;
    }

    public DocumentoPago getDocumentoPago() {
        return this.documentoPago;
    }

    public void setDocumentoPago(DocumentoPago documentoPago) {
        this.documentoPago = documentoPago;
    }

    public int getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public double getPrecioUnitario() {
        return this.precioUnitario;
    }

    public void setPrecioUnitario(double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }

    public Integer getAnioDesde() {
        return this.anioDesde;
    }

    public void setAnioDesde(Integer anioDesde) {
        this.anioDesde = anioDesde;
    }

    public Integer getMesDesde() {
        return this.mesDesde;
    }

    public void setMesDesde(Integer mesDesde) {
        this.mesDesde = mesDesde;
    }

    public Integer getAnioHasta() {
        return this.anioHasta;
    }

    public void setAnioHasta(Integer anioHasta) {
        this.anioHasta = anioHasta;
    }

    public Integer getMesHasta() {
        return this.mesHasta;
    }

    public void setMesHasta(Integer mesHasta) {
        this.mesHasta = mesHasta;
    }

    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public Double getValorVenta() {
        return this.valorVenta;
    }

    public void setValorVenta(Double valorVenta) {
        this.valorVenta = valorVenta;
    }

    public Double getPrecioVenta() {
        return this.precioVenta;
    }

    public void setPrecioVenta(Double precioVenta) {
        this.precioVenta = precioVenta;
    }

    public Double getIgv() {
        return this.igv;
    }

    public void setIgv(Double igv) {
        this.igv = igv;
    }

    public String getTieneDescuento() {
        return this.tieneDescuento;
    }

    public void setTieneDescuento(String tieneDescuento) {
        this.tieneDescuento = tieneDescuento;
    }

    public Double getDescuento() {
        return this.descuento;
    }

    public void setDescuento(Double descuento) {
        this.descuento = descuento;
    }

    public String getGlosa() {
        return this.glosa;
    }

    public void setGlosa(String glosa) {
        this.glosa = glosa;
    }

    public Set getAlumnoses() {
        return this.alumnoses;
    }

    public void setAlumnoses(Set alumnoses) {
        this.alumnoses = alumnoses;
    }

    public Set getReincorporacionDocumentoPagos() {
        return this.reincorporacionDocumentoPagos;
    }

    public void setReincorporacionDocumentoPagos(Set reincorporacionDocumentoPagos) {
        this.reincorporacionDocumentoPagos = reincorporacionDocumentoPagos;
    }

    public Set getFinanciamientoDocumentoPagos() {
        return this.financiamientoDocumentoPagos;
    }

    public void setFinanciamientoDocumentoPagos(Set financiamientoDocumentoPagos) {
        this.financiamientoDocumentoPagos = financiamientoDocumentoPagos;
    }

    public Set getCuotases() {
        return this.cuotases;
    }

    public void setCuotases(Set cuotases) {
        this.cuotases = cuotases;
    }

    public Set getDeudas() {
        return this.deudas;
    }

    public void setDeudas(Set deudas) {
        this.deudas = deudas;
    }

    public Set getCongresoParticipanteses() {
        return this.congresoParticipanteses;
    }

    public void setCongresoParticipanteses(Set congresoParticipanteses) {
        this.congresoParticipanteses = congresoParticipanteses;
    }

    public Set getCuentaCorrientes() {
        return this.cuentaCorrientes;
    }

    public void setCuentaCorrientes(Set cuentaCorrientes) {
        this.cuentaCorrientes = cuentaCorrientes;
    }

    public Double getIgvPorcentaje() {
        return igvPorcentaje;
    }

    public void setIgvPorcentaje(Double igvPorcentaje) {
        this.igvPorcentaje = igvPorcentaje;
    }

    public String getCodigoTipoTributo() {
        return codigoTipoTributo;
    }

    public void setCodigoTipoTributo(String codigoTipoTributo) {
        this.codigoTipoTributo = codigoTipoTributo;
    }

    public String getCodigoInternacionalTipoTributo() {
        return codigoInternacionalTipoTributo;
    }

    public void setCodigoInternacionalTipoTributo(String codigoInternacionalTipoTributo) {
        this.codigoInternacionalTipoTributo = codigoInternacionalTipoTributo;
    }

    public String getNombreTipoTributo() {
        return nombreTipoTributo;
    }

    public void setNombreTipoTributo(String nombreTipoTributo) {
        this.nombreTipoTributo = nombreTipoTributo;
    }

    public String getCodigoTipoAfectacion() {
        return codigoTipoAfectacion;
    }

    public void setCodigoTipoAfectacion(String codigoTipoAfectacion) {
        this.codigoTipoAfectacion = codigoTipoAfectacion;
    }

    public Set getParticipantes() {
        return participantes;
    }

    public void setParticipantes(Set participantes) {
        this.participantes = participantes;
    }

    public Set getValeAcademicos() {
        return valeAcademicos;
    }

    public void setValeAcademicos(Set valeAcademicos) {
        this.valeAcademicos = valeAcademicos;
    }

    public Set getValeAcademicoConsumos() {
        return valeAcademicoConsumos;
    }

    public void setValeAcademicoConsumos(Set valeAcademicoConsumos) {
        this.valeAcademicoConsumos = valeAcademicoConsumos;
    }

    public Set getConstanciaHabilitacions() {
        return constanciaHabilitacions;
    }

    public void setConstanciaHabilitacions(Set constanciaHabilitacions) {
        this.constanciaHabilitacions = constanciaHabilitacions;
    }

    public Double getPorcentajeDetraccion() {
        return porcentajeDetraccion;
    }

    public void setPorcentajeDetraccion(Double porcentajeDetraccion) {
        this.porcentajeDetraccion = porcentajeDetraccion;
    }

    public Double getMontoDetraccion() {
        return montoDetraccion;
    }

    public void setMontoDetraccion(Double montoDetraccion) {
        this.montoDetraccion = montoDetraccion;
    }

    public String getCodigoBienServicioDetraccion() {
        return codigoBienServicioDetraccion;
    }

    public void setCodigoBienServicioDetraccion(String codigoBienServicioDetraccion) {
        this.codigoBienServicioDetraccion = codigoBienServicioDetraccion;
    }

}
