package caja.mapeo.entidades;
// Generated 30/10/2019 08:16:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private int id;
     private TipoEvento tipoEvento;
     private String nombre;
     private String codigo;
     private String objetivo;
     private String dirigidoa;
     private String descripcion;
     private String urlImagen;
     private String lugar;
     private String duracion;
     private Integer capacidad;
     private String cursoIncluye;
     private Short nroLikes;
     private Integer nroVisualizaciones;
     private Character estado;
     private String borrado;
     private Set actividads = new HashSet(0);
     private Set metodologias = new HashSet(0);
     private Set inversions = new HashSet(0);
     private Set asignacionEventos = new HashSet(0);
     private Set objetivoses = new HashSet(0);
     private Set eventoConceptoPagos = new HashSet(0);
     private Set periodos = new HashSet(0);

    public Evento() {
    }

	
    public Evento(int id) {
        this.id = id;
    }
    public Evento(int id, TipoEvento tipoEvento, String nombre, String codigo, String objetivo, String dirigidoa, String descripcion, String urlImagen, String lugar, String duracion, Integer capacidad, String cursoIncluye, Short nroLikes, Integer nroVisualizaciones, Character estado, String borrado, Set actividads, Set metodologias, Set inversions, Set asignacionEventos, Set objetivoses, Set eventoConceptoPagos, Set periodos) {
       this.id = id;
       this.tipoEvento = tipoEvento;
       this.nombre = nombre;
       this.codigo = codigo;
       this.objetivo = objetivo;
       this.dirigidoa = dirigidoa;
       this.descripcion = descripcion;
       this.urlImagen = urlImagen;
       this.lugar = lugar;
       this.duracion = duracion;
       this.capacidad = capacidad;
       this.cursoIncluye = cursoIncluye;
       this.nroLikes = nroLikes;
       this.nroVisualizaciones = nroVisualizaciones;
       this.estado = estado;
       this.borrado = borrado;
       this.actividads = actividads;
       this.metodologias = metodologias;
       this.inversions = inversions;
       this.asignacionEventos = asignacionEventos;
       this.objetivoses = objetivoses;
       this.eventoConceptoPagos = eventoConceptoPagos;
       this.periodos = periodos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TipoEvento getTipoEvento() {
        return this.tipoEvento;
    }
    
    public void setTipoEvento(TipoEvento tipoEvento) {
        this.tipoEvento = tipoEvento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getObjetivo() {
        return this.objetivo;
    }
    
    public void setObjetivo(String objetivo) {
        this.objetivo = objetivo;
    }
    public String getDirigidoa() {
        return this.dirigidoa;
    }
    
    public void setDirigidoa(String dirigidoa) {
        this.dirigidoa = dirigidoa;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUrlImagen() {
        return this.urlImagen;
    }
    
    public void setUrlImagen(String urlImagen) {
        this.urlImagen = urlImagen;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public Integer getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }
    public String getCursoIncluye() {
        return this.cursoIncluye;
    }
    
    public void setCursoIncluye(String cursoIncluye) {
        this.cursoIncluye = cursoIncluye;
    }
    public Short getNroLikes() {
        return this.nroLikes;
    }
    
    public void setNroLikes(Short nroLikes) {
        this.nroLikes = nroLikes;
    }
    public Integer getNroVisualizaciones() {
        return this.nroVisualizaciones;
    }
    
    public void setNroVisualizaciones(Integer nroVisualizaciones) {
        this.nroVisualizaciones = nroVisualizaciones;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public String getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(String borrado) {
        this.borrado = borrado;
    }
    public Set getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set actividads) {
        this.actividads = actividads;
    }
    public Set getMetodologias() {
        return this.metodologias;
    }
    
    public void setMetodologias(Set metodologias) {
        this.metodologias = metodologias;
    }
    public Set getInversions() {
        return this.inversions;
    }
    
    public void setInversions(Set inversions) {
        this.inversions = inversions;
    }
    public Set getAsignacionEventos() {
        return this.asignacionEventos;
    }
    
    public void setAsignacionEventos(Set asignacionEventos) {
        this.asignacionEventos = asignacionEventos;
    }
    public Set getObjetivoses() {
        return this.objetivoses;
    }
    
    public void setObjetivoses(Set objetivoses) {
        this.objetivoses = objetivoses;
    }
    public Set getEventoConceptoPagos() {
        return this.eventoConceptoPagos;
    }
    
    public void setEventoConceptoPagos(Set eventoConceptoPagos) {
        this.eventoConceptoPagos = eventoConceptoPagos;
    }
    public Set getPeriodos() {
        return this.periodos;
    }
    
    public void setPeriodos(Set periodos) {
        this.periodos = periodos;
    }
    
    @Override
    public String toString(){
        return this.codigo + " - " + this.nombre;
    }




}


