package caja.mapeo.entidades;
// Generated 30/10/2019 08:16:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Expositor generated by hbm2java
 */
public class Expositor  implements java.io.Serializable {


     private int id;
     private Cliente cliente;
     private String institucion;
     private String nivelAcademico;
     private String nombreNivelAcademico;
     private String email;
     private String urlFoto;
     private Character frecuente;
     private String borrado;
     private String curriculum;
     private Set asignacionEventos = new HashSet(0);
     private Set curriculums = new HashSet(0);

    public Expositor() {
    }

	
    public Expositor(int id) {
        this.id = id;
    }
    public Expositor(int id, Cliente cliente, String institucion, String nivelAcademico, String nombreNivelAcademico, String email, String urlFoto, Character frecuente, String borrado, String curriculum, Set asignacionEventos, Set curriculums) {
       this.id = id;
       this.cliente = cliente;
       this.institucion = institucion;
       this.nivelAcademico = nivelAcademico;
       this.nombreNivelAcademico = nombreNivelAcademico;
       this.email = email;
       this.urlFoto = urlFoto;
       this.frecuente = frecuente;
       this.borrado = borrado;
       this.curriculum = curriculum;
       this.asignacionEventos = asignacionEventos;
       this.curriculums = curriculums;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }
    public String getNivelAcademico() {
        return this.nivelAcademico;
    }
    
    public void setNivelAcademico(String nivelAcademico) {
        this.nivelAcademico = nivelAcademico;
    }
    public String getNombreNivelAcademico() {
        return this.nombreNivelAcademico;
    }
    
    public void setNombreNivelAcademico(String nombreNivelAcademico) {
        this.nombreNivelAcademico = nombreNivelAcademico;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUrlFoto() {
        return this.urlFoto;
    }
    
    public void setUrlFoto(String urlFoto) {
        this.urlFoto = urlFoto;
    }
    public Character getFrecuente() {
        return this.frecuente;
    }
    
    public void setFrecuente(Character frecuente) {
        this.frecuente = frecuente;
    }
    public String getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(String borrado) {
        this.borrado = borrado;
    }
    public String getCurriculum() {
        return this.curriculum;
    }
    
    public void setCurriculum(String curriculum) {
        this.curriculum = curriculum;
    }
    public Set getAsignacionEventos() {
        return this.asignacionEventos;
    }
    
    public void setAsignacionEventos(Set asignacionEventos) {
        this.asignacionEventos = asignacionEventos;
    }
    public Set getCurriculums() {
        return this.curriculums;
    }
    
    public void setCurriculums(Set curriculums) {
        this.curriculums = curriculums;
    }




}


