package caja.mapeo.entidades;
// Generated 15/10/2016 10:02:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FinanciamientoDocumentoPago generated by hbm2java
 */
public class FinanciamientoDocumentoPago  implements java.io.Serializable {


     private int id;
     private DocumentoPagoDet documentoPagoDet;
     private Financiamiento financiamiento;
     private String estado;
     private Double monto;
     private Date fechaVencimiento;
     private Integer nroCuota;
     private Integer diasProrroga;
     private Double montoSinPagoDeMas;
     private Double montoPagoDeMas;
     private Integer idFinanciamientoNuevo;

    public FinanciamientoDocumentoPago() {
    }

	
    public FinanciamientoDocumentoPago(int id) {
        this.id = id;
    }
    public FinanciamientoDocumentoPago(int id, DocumentoPagoDet documentoPagoDet, Financiamiento financiamiento, String estado, Double monto, Date fechaVencimiento, Integer nroCuota, Integer diasProrroga, Double montoSinPagoDeMas, Double montoPagoDeMas, Integer idFinanciamientoNuevo) {
       this.id = id;
       this.documentoPagoDet = documentoPagoDet;
       this.financiamiento = financiamiento;
       this.estado = estado;
       this.monto = monto;
       this.fechaVencimiento = fechaVencimiento;
       this.nroCuota = nroCuota;
       this.diasProrroga = diasProrroga;
       this.montoSinPagoDeMas = montoSinPagoDeMas;
       this.montoPagoDeMas = montoPagoDeMas;
       this.idFinanciamientoNuevo = idFinanciamientoNuevo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public DocumentoPagoDet getDocumentoPagoDet() {
        return this.documentoPagoDet;
    }
    
    public void setDocumentoPagoDet(DocumentoPagoDet documentoPagoDet) {
        this.documentoPagoDet = documentoPagoDet;
    }
    public Financiamiento getFinanciamiento() {
        return this.financiamiento;
    }
    
    public void setFinanciamiento(Financiamiento financiamiento) {
        this.financiamiento = financiamiento;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public Integer getNroCuota() {
        return this.nroCuota;
    }
    
    public void setNroCuota(Integer nroCuota) {
        this.nroCuota = nroCuota;
    }
    public Integer getDiasProrroga() {
        return this.diasProrroga;
    }
    
    public void setDiasProrroga(Integer diasProrroga) {
        this.diasProrroga = diasProrroga;
    }
    public Double getMontoSinPagoDeMas() {
        return this.montoSinPagoDeMas;
    }
    
    public void setMontoSinPagoDeMas(Double montoSinPagoDeMas) {
        this.montoSinPagoDeMas = montoSinPagoDeMas;
    }
    public Double getMontoPagoDeMas() {
        return this.montoPagoDeMas;
    }
    
    public void setMontoPagoDeMas(Double montoPagoDeMas) {
        this.montoPagoDeMas = montoPagoDeMas;
    }
    public Integer getIdFinanciamientoNuevo() {
        return this.idFinanciamientoNuevo;
    }
    
    public void setIdFinanciamientoNuevo(Integer idFinanciamientoNuevo) {
        this.idFinanciamientoNuevo = idFinanciamientoNuevo;
    }




}


