package caja.mapeo.entidades;
// Generated 15/10/2016 10:02:37 PM by Hibernate Tools 4.3.1



/**
 * GastoDetalle generated by hbm2java
 */
public class GastoDetalle  implements java.io.Serializable {


     private int idGastosDetalle;
     private ConceptoGastoDetalle conceptoGastoDetalle;
     private Gastos gastos;
     private int cantidad;
     private double precioUnitario;
     private String observacion;

    public GastoDetalle() {
    }

	
    public GastoDetalle(int idGastosDetalle, ConceptoGastoDetalle conceptoGastoDetalle, Gastos gastos, int cantidad, double precioUnitario) {
        this.idGastosDetalle = idGastosDetalle;
        this.conceptoGastoDetalle = conceptoGastoDetalle;
        this.gastos = gastos;
        this.cantidad = cantidad;
        this.precioUnitario = precioUnitario;
    }
    public GastoDetalle(int idGastosDetalle, ConceptoGastoDetalle conceptoGastoDetalle, Gastos gastos, int cantidad, double precioUnitario, String observacion) {
       this.idGastosDetalle = idGastosDetalle;
       this.conceptoGastoDetalle = conceptoGastoDetalle;
       this.gastos = gastos;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.observacion = observacion;
    }
   
    public int getIdGastosDetalle() {
        return this.idGastosDetalle;
    }
    
    public void setIdGastosDetalle(int idGastosDetalle) {
        this.idGastosDetalle = idGastosDetalle;
    }
    public ConceptoGastoDetalle getConceptoGastoDetalle() {
        return this.conceptoGastoDetalle;
    }
    
    public void setConceptoGastoDetalle(ConceptoGastoDetalle conceptoGastoDetalle) {
        this.conceptoGastoDetalle = conceptoGastoDetalle;
    }
    public Gastos getGastos() {
        return this.gastos;
    }
    
    public void setGastos(Gastos gastos) {
        this.gastos = gastos;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


