package caja.mapeo.entidades;
// Generated 15/10/2016 10:02:37 PM by Hibernate Tools 4.3.1

/**
 * TipoDocIdentidad generated by hbm2java
 */
public class NotaDetalle implements java.io.Serializable {

    private int id;
    private Nota nota;
    private int cantidad;
    private double valorVenta;
    private DocumentoPagoDet documentoPagoDet;
    private double igv;
    private double igvPorcentaje;
    private Double montoDetraccion;
    private String codigoTipoTributo;
    private String nombreTipoTributo;
    private String codigoInternacionalTipoTributo;
    private String codigoTipoAfectacion;

    public NotaDetalle() {
    }

    public NotaDetalle(int id, Nota nota, int cantidad, double valorVenta, DocumentoPagoDet documentoPagoDet, double igv, double igvPorcentaje, String codigoTipoTributo, String nombreTipoTributo, String codigoInternacionalTipoTributo, String codigoTipoAfectacion) {
        this.id = id;
        this.nota = nota;
        this.cantidad = cantidad;
        this.valorVenta = valorVenta;
        this.documentoPagoDet = documentoPagoDet;
        this.igv = igv;
        this.igvPorcentaje = igvPorcentaje;
        this.codigoTipoTributo = codigoTipoTributo;
        this.nombreTipoTributo = nombreTipoTributo;
        this.codigoInternacionalTipoTributo = codigoInternacionalTipoTributo;
        this.codigoTipoAfectacion = codigoTipoAfectacion;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Nota getNota() {
        return nota;
    }

    public void setNota(Nota nota) {
        this.nota = nota;
    }

    public int getCantidad() {
        return cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public double getValorVenta() {
        return valorVenta;
    }

    public void setValorVenta(double valorVenta) {
        this.valorVenta = valorVenta;
    }

    public DocumentoPagoDet getDocumentoPagoDet() {
        return documentoPagoDet;
    }

    public void setDocumentoPagoDet(DocumentoPagoDet documentoPagoDet) {
        this.documentoPagoDet = documentoPagoDet;
    }

    public double getIgv() {
        return igv;
    }

    public void setIgv(double igv) {
        this.igv = igv;
    }

    public double getIgvPorcentaje() {
        return igvPorcentaje;
    }

    public void setIgvPorcentaje(double igvPorcentaje) {
        this.igvPorcentaje = igvPorcentaje;
    }

    public String getCodigoTipoTributo() {
        return codigoTipoTributo;
    }

    public void setCodigoTipoTributo(String codigoTipoTributo) {
        this.codigoTipoTributo = codigoTipoTributo;
    }

    public String getNombreTipoTributo() {
        return nombreTipoTributo;
    }

    public void setNombreTipoTributo(String nombreTipoTributo) {
        this.nombreTipoTributo = nombreTipoTributo;
    }

    public String getCodigoInternacionalTipoTributo() {
        return codigoInternacionalTipoTributo;
    }

    public void setCodigoInternacionalTipoTributo(String codigoInternacionalTipoTributo) {
        this.codigoInternacionalTipoTributo = codigoInternacionalTipoTributo;
    }

    public String getCodigoTipoAfectacion() {
        return codigoTipoAfectacion;
    }

    public void setCodigoTipoAfectacion(String codigoTipoAfectacion) {
        this.codigoTipoAfectacion = codigoTipoAfectacion;
    }

    public Double getMontoDetraccion() {
        return montoDetraccion;
    }

    public void setMontoDetraccion(Double montoDetraccion) {
        this.montoDetraccion = montoDetraccion;
    }

}
