package caja.mapeo.entidades;
// Generated 15/10/2016 10:02:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ReincorporacionDocumentoPago generated by hbm2java
 */
public class ReincorporacionDocumentoPago  implements java.io.Serializable {


     private int id;
     private DocumentoPagoDet documentoPagoDet;
     private Reincorporacion reincorporacion;
     private String estado;
     private Double monto;
     private Date fechaVencimiento;
     private Integer nroCuota;
     private Integer diasProrroga;
     private Double montoFondo;
     private Double montoOtros;

    public ReincorporacionDocumentoPago() {
    }

	
    public ReincorporacionDocumentoPago(int id) {
        this.id = id;
    }
    public ReincorporacionDocumentoPago(int id, DocumentoPagoDet documentoPagoDet, Reincorporacion reincorporacion, String estado, Double monto, Date fechaVencimiento, Integer nroCuota, Integer diasProrroga, Double montoFondo, Double montoOtros) {
       this.id = id;
       this.documentoPagoDet = documentoPagoDet;
       this.reincorporacion = reincorporacion;
       this.estado = estado;
       this.monto = monto;
       this.fechaVencimiento = fechaVencimiento;
       this.nroCuota = nroCuota;
       this.diasProrroga = diasProrroga;
       this.montoFondo = montoFondo;
       this.montoOtros = montoOtros;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public DocumentoPagoDet getDocumentoPagoDet() {
        return this.documentoPagoDet;
    }
    
    public void setDocumentoPagoDet(DocumentoPagoDet documentoPagoDet) {
        this.documentoPagoDet = documentoPagoDet;
    }
    public Reincorporacion getReincorporacion() {
        return this.reincorporacion;
    }
    
    public void setReincorporacion(Reincorporacion reincorporacion) {
        this.reincorporacion = reincorporacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public Integer getNroCuota() {
        return this.nroCuota;
    }
    
    public void setNroCuota(Integer nroCuota) {
        this.nroCuota = nroCuota;
    }
    public Integer getDiasProrroga() {
        return this.diasProrroga;
    }
    
    public void setDiasProrroga(Integer diasProrroga) {
        this.diasProrroga = diasProrroga;
    }
    public Double getMontoFondo() {
        return this.montoFondo;
    }
    
    public void setMontoFondo(Double montoFondo) {
        this.montoFondo = montoFondo;
    }
    public Double getMontoOtros() {
        return this.montoOtros;
    }
    
    public void setMontoOtros(Double montoOtros) {
        this.montoOtros = montoOtros;
    }




}


