package caja.mapeo.entidades;
// Generated 15/10/2016 10:02:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocIdentidad generated by hbm2java
 */
public class TipoNota implements java.io.Serializable {

    private int id;
    private String codigo;
    private String descripcion;
    private int tipoNota;
    private Set notas = new HashSet(0);

    public TipoNota() {
    }

    public TipoNota(int id, String codigo, String descripcion) {
        this.id = id;
        this.codigo = codigo;
        this.descripcion = descripcion;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set getNotas() {
        return notas;
    }

    public void setNotas(Set notas) {
        this.notas = notas;
    }

    public int getTipoNota() {
        return tipoNota;
    }

    public void setTipoNota(int tipoNota) {
        this.tipoNota = tipoNota;
    }

    @Override
    public String toString() {
        return this.codigo + " - " + this.descripcion;
    }

}
