package caja.mapeo.entidades;
// Generated 30/09/2017 12:07:35 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumento generated by hbm2java
 */
public class TipoAfectacion implements java.io.Serializable {

    private int id;
    private String codigo;
    private String descripcion;
    private TipoTributo tipoTributo;
    private Set conceptoPagoDetalles = new HashSet(0);

    public TipoAfectacion() {
    }

    public TipoAfectacion(int id, String codigo) {
        this.id = id;
        this.codigo = codigo;
    }

    public TipoAfectacion(int id, String codigo, String descripcion, TipoTributo tipoAfectacion) {
        this.id = id;
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.tipoTributo = tipoAfectacion;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }


    public Set getConceptoPagoDetalles() {
        return conceptoPagoDetalles;
    }

    public void setConceptoPagoDetalles(Set conceptoPagoDetalles) {
        this.conceptoPagoDetalles = conceptoPagoDetalles;
    }

    public TipoTributo getTipoTributo() {
        return tipoTributo;
    }

    public void setTipoTributo(TipoTributo tipoTributo) {
        this.tipoTributo = tipoTributo;
    }



    @Override
    public String toString() {
        return this.codigo + " - " + this.descripcion;
    }

}
