/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.administracion;

import caja.bo.ClienteBO;
import caja.mapeo.entidades.ClienteAuditorIndependiente;
import caja.mapeo.entidades.ClienteDerechoHabiente;
import caja.mapeo.entidades.ClienteSociedadVigencia;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import units.DatePicker;

/**
 *
 * @author user
 */
public class frmClienteSociedadVigencia extends javax.swing.JDialog {

    private int fila;
    private int tipoCarga;
    private frmSociedad frm;
    private ClienteSociedadVigencia clienteSociedadVigencia = null;

    /**
     * Creates new form frmClienteDerechoHabiente
     */
    public frmClienteSociedadVigencia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtFechaVigenciaDesde = new javax.swing.JTextField();
        txtFechaVigenciaHasta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnFecha4 = new javax.swing.JButton();
        btnFecha5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Fecha Desde:");

        txtFechaVigenciaDesde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaVigenciaDesdeKeyTyped(evt);
            }
        });

        txtFechaVigenciaHasta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaVigenciaHastaKeyTyped(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Fecha Hasta:");

        btnFecha4.setText("...");
        btnFecha4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecha4ActionPerformed(evt);
            }
        });

        btnFecha5.setText("...");
        btnFecha5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecha5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaVigenciaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaVigenciaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFecha4)
                            .addComponent(btnFecha5))
                        .addGap(4, 4, 4)))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaVigenciaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFecha4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFechaVigenciaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFecha5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarDatos(frmSociedad fr, int tc, int fi, ClienteSociedadVigencia dh) {
        this.fila = fi;
        this.tipoCarga = tc;
        this.frm = fr;
        this.clienteSociedadVigencia = dh;
//        txtFechaAfiliacion.setText("");
        txtFechaVigenciaDesde.setText("");
        txtFechaVigenciaHasta.setText("");
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
//        if (dh.getFechaAfiliacion() != null) {
//            txtFechaAfiliacion.setText(f.format(dh.getFechaAfiliacion()));
//        }
        if (dh.getFechaDesde() != null) {
            txtFechaVigenciaDesde.setText(f.format(dh.getFechaDesde()));
        }
        if (dh.getFechaHasta() != null) {
            txtFechaVigenciaHasta.setText(f.format(dh.getFechaHasta()));
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

//        if (txtFechaAfiliacion.getText().trim().isEmpty()) {
//            JOptionPane.showMessageDialog(this,
//                    "Debe ingresar la fecha de afiliación",
//                    "ERROR",
//                    JOptionPane.ERROR_MESSAGE);
//            return;
//        }
        if (txtFechaVigenciaDesde.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe ingresar la fecha vigencia desde",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtFechaVigenciaHasta.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe ingresar la fecha vigencia hasta",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.clienteSociedadVigencia.setBorrado("1");
        SimpleDateFormat formatoDeFecha = new SimpleDateFormat("yyyy-MM-dd");
        try {
//            this.auditorIndependiente.setFechaAfiliacion(txtFechaAfiliacion.getText().trim().isEmpty() ? null : formatoDeFecha.parse(txtFechaAfiliacion.getText()));
            this.clienteSociedadVigencia.setFechaDesde(txtFechaVigenciaDesde.getText().trim().isEmpty() ? null : formatoDeFecha.parse(txtFechaVigenciaDesde.getText()));
            this.clienteSociedadVigencia.setFechaHasta(txtFechaVigenciaHasta.getText().trim().isEmpty() ? null : formatoDeFecha.parse(txtFechaVigenciaHasta.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error en el formato de fecha, debe tener el siguiente formato: yyyy-MM-dd", "ERROR",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (this.tipoCarga == 1) {
            this.frm.agregarVigencia(this.clienteSociedadVigencia);
        } else {
            this.frm.actualizarVigencia(this.fila, clienteSociedadVigencia);
        }
//            cBO.ActualizarObjeto(this.derechoHabiente);
//            JOptionPane.showMessageDialog(this, "Se  el derecho habiente", "OK", JOptionPane.WARNING_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFechaVigenciaDesdeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaVigenciaDesdeKeyTyped
        if (txtFechaVigenciaDesde.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFechaVigenciaDesdeKeyTyped

    private void txtFechaVigenciaHastaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaVigenciaHastaKeyTyped
        if (txtFechaVigenciaHasta.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFechaVigenciaHastaKeyTyped

    private void btnFecha4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecha4ActionPerformed
        DatePicker dtp = new DatePicker(this);
        if (!dtp.setPickedDate().isEmpty()) {
            txtFechaVigenciaDesde.setText(dtp.setPickedDate());
        }
    }//GEN-LAST:event_btnFecha4ActionPerformed

    private void btnFecha5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecha5ActionPerformed
        DatePicker dtp = new DatePicker(this);
        if (!dtp.setPickedDate().isEmpty()) {
            txtFechaVigenciaHasta.setText(dtp.setPickedDate());
        }
    }//GEN-LAST:event_btnFecha5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClienteSociedadVigencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClienteSociedadVigencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClienteSociedadVigencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClienteSociedadVigencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmClienteSociedadVigencia dialog = new frmClienteSociedadVigencia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFecha4;
    private javax.swing.JButton btnFecha5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtFechaVigenciaDesde;
    private javax.swing.JTextField txtFechaVigenciaHasta;
    // End of variables declaration//GEN-END:variables
}
