/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.administracion;

import caja.bo.ConceptoPagoDetalleBO;
import caja.bo.ManagerBO;
import caja.bo.SeguridadBO;
import caja.bo.TipoTributoBO;
import caja.bo.soloMayusculas;
import caja.mapeo.entidades.CodigoBienServicioDetraccion;
import caja.mapeo.entidades.ConceptoPagoDetalle;
import caja.mapeo.entidades.TipoAfectacion;
import caja.mapeo.entidades.TipoTributo;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author juan carlos
 */
public class frmConceptoPagoDetalle extends javax.swing.JInternalFrame {

    private ConceptoPagoDetalle conceptoPago;

    /**
     * Creates new form frmConceptoPagoDetalle
     */
    public frmConceptoPagoDetalle() {
        initComponents();

        TableColumn columna = tConceptos.getColumn("NRO");
        columna.setPreferredWidth(20);
        columna = tConceptos.getColumn("ID");
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna.setPreferredWidth(0);
        columna = tConceptos.getColumn("CODIGO");
        columna.setPreferredWidth(30);
        columna = tConceptos.getColumn("TIPO CODIGO");
        columna.setPreferredWidth(30);
        columna = tConceptos.getColumn("DESCRIPCION");
        columna.setPreferredWidth(300);
        columna = tConceptos.getColumn("IGV");
        columna.setPreferredWidth(20);
        columna = tConceptos.getColumn("PORCENTAJE");
        columna.setPreferredWidth(40);
        columna = tConceptos.getColumn("CARGO");
        columna.setPreferredWidth(30);
        columna = tConceptos.getColumn("ABONO");
        columna.setPreferredWidth(30);
        columna = tConceptos.getColumn("WEB");
        columna.setPreferredWidth(30);
        columna = tConceptos.getColumn("ESTADO");
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna.setPreferredWidth(0);

        txtCodigo.setEditable(false);
        txtCodigoPresupuesto.setEditable(false);
        txtTipoCodigo.setEditable(false);
        txtCargo.setEditable(false);
        txtAbono.setEditable(false);
        cbIgv.setEnabled(false);
//        txtIGV.setDocument(new soloMayusculas());
        txtPorcentaje.setEditable(false);
        txtObservacion.setEditable(false);
        txtObservacion.setDocument(new soloMayusculas());
        txtDescripcion.setEditable(false);
        txtDescripcion.setDocument(new soloMayusculas());
        TipoTributoBO ttBO = TipoTributoBO.getInstance();
        List<TipoTributo> lT = ttBO.ObtenerTodosTipoTributo();
        for (TipoTributo tt : lT) {
            cbTipoTributo.addItem(tt);
        }
        List<TipoAfectacion> lA = ttBO.ObtenerAfectaciones(((TipoTributo) cbTipoTributo.getSelectedItem()).getId());
        for (TipoAfectacion tt : lA) {
            cbTipoAfectacion.addItem(tt);
        }

        CodigoBienServicioDetraccion noItem = new CodigoBienServicioDetraccion();
        noItem.setId(-1);
        noItem.setCodigo("");
        noItem.setDescripcion("SELECCIONAR");
        cbCodigoDetraccion.addItem(noItem);
        ManagerBO mgBO = ManagerBO.getInstance();
        List<CodigoBienServicioDetraccion> ld = mgBO.ObtenerTodosCodigoBienServicioDetraccion();
        for (CodigoBienServicioDetraccion tt : ld) {
            cbCodigoDetraccion.addItem(tt);
        }

        tConceptos.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused, int row, int column) {
                setBackground(Color.white);//color de fondo
                table.getClass().getCanonicalName();
                table.setForeground(Color.black);//color de texto
                if (String.valueOf(table.getValueAt(row, 9)).equals("I")) {
                    setBackground(Color.decode("#ffa0a2"));
                }
                super.getTableCellRendererComponent(table, value, selected, focused, row, column);
                return this;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        cbFiltro = new javax.swing.JComboBox();
        btnBuscar = new javax.swing.JButton();
        btnNuevoConceptoPago = new javax.swing.JButton();
        pbConceptoPagoDetalle = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tConceptos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtAbono = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtObservacion = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTipoCodigo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbTipoAfectacion = new javax.swing.JComboBox();
        cbIgv = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbTipoTributo = new javax.swing.JComboBox();
        cbEstado = new javax.swing.JComboBox<>();
        cbMostrarWeb = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCodigoPresupuesto = new javax.swing.JTextField();
        cbCodigoDetraccion = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        txtPorcentajeDetraccion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ADMINISTRACIÓN CONCEPTO PAGO");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/icono.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(901, 600));

        jLabel2.setText("Búsqueda:");

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "POR NOMBRE", "POR CODIGO", "POR TIPO CODIGO", "POR CARGO", "POR ABONO" }));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/buscar5.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevoConceptoPago.setText("NUEVO CONCEPTO PAGO");
        btnNuevoConceptoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoConceptoPagoActionPerformed(evt);
            }
        });

        tConceptos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NRO", "TIPO CODIGO", "CODIGO", "DESCRIPCION", "IGV", "PORCENTAJE", "CARGO", "ABONO", "ESTADO", "WEB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tConceptos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tConceptosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tConceptos);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS CONCEPTO PAGO"));

        jLabel3.setText("CODIGO:");

        jLabel4.setText("CARGO:");

        jLabel5.setText("ABONO:");

        jLabel6.setText("DETRACCIÓN:");

        jLabel7.setText("DESCRIPCION:");

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        txtAbono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAbonoKeyPressed(evt);
            }
        });

        txtCargo.setPreferredSize(new java.awt.Dimension(30, 20));
        txtCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCargoKeyPressed(evt);
            }
        });

        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyPressed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/Guardar2.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel8.setText("TIPO CODIGO:");

        txtTipoCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTipoCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTipoCodigoKeyTyped(evt);
            }
        });

        jLabel9.setText("TIENE IGV:");

        jLabel10.setText("% IGV:");

        txtPorcentaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPorcentajeKeyPressed(evt);
            }
        });

        jLabel1.setText("T. AFECTACION:");

        cbIgv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));

        jLabel11.setText("T. TRIBUTO:");

        cbTipoTributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoTributoActionPerformed(evt);
            }
        });

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HABILITADO", "INHABILITADO" }));

        cbMostrarWeb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));

        jLabel12.setText("MOSTRAR WEB:");

        jLabel13.setText("C. PPTO:");

        txtCodigoPresupuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoPresupuestoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoPresupuestoKeyTyped(evt);
            }
        });

        jLabel14.setText("% DETRACCIÓN:");

        jLabel15.setText("OBS:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbCodigoDetraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPorcentajeDetraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtObservacion))
                            .addComponent(txtDescripcion)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTipoTributo, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTipoCodigo)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(txtAbono))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipoAfectacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCodigoPresupuesto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbIgv, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMostrarWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(353, 353, 353))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbTipoTributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbTipoAfectacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtCodigoPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txtTipoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbIgv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMostrarWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCodigoDetraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtPorcentajeDetraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbConceptoPagoDetalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevoConceptoPago)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnNuevoConceptoPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbConceptoPagoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarConceptoPagoDetalle() {
        txtCodigo.setEditable(false);
        txtCodigoPresupuesto.setEditable(false);
        txtTipoCodigo.setEditable(false);
        txtCargo.setEditable(false);
        txtAbono.setEditable(false);
        cbIgv.setEnabled(false);
        txtPorcentaje.setEditable(false);
        txtObservacion.setEditable(false);
        txtDescripcion.setEditable(false);

        int tipoBusqueda = 0;
        if (cbFiltro.getSelectedItem() == "POR NOMBRE") {
            tipoBusqueda = 1;
        } else if (cbFiltro.getSelectedItem() == "POR CODIGO") {
            tipoBusqueda = 2;
        } else if (cbFiltro.getSelectedItem() == "POR TIPO CODIGO") {
            tipoBusqueda = 3;
        } else if (cbFiltro.getSelectedItem() == "POR CARGO") {
            tipoBusqueda = 4;
        } else if (cbFiltro.getSelectedItem() == "POR ABONO") {
            tipoBusqueda = 5;
        }

        ConceptoPagoDetalleBO cpd = ConceptoPagoDetalleBO.getInstance();
        List<ConceptoPagoDetalle> l = cpd.BuscarConceptoPagoDetalle(txtBusqueda.getText(), tipoBusqueda);
        DefaultTableModel modelo = (DefaultTableModel) tConceptos.getModel();
        modelo = (DefaultTableModel) tConceptos.getModel();
        modelo.setRowCount(l.size());
        int contador = 0;
        for (ConceptoPagoDetalle cp : l) {
            modelo.setNumRows(contador);
            modelo.addRow(new Object[contador]);
            tConceptos.setValueAt(cp, contador, 0);
            tConceptos.setValueAt(contador + 1, contador, 1);
            tConceptos.setValueAt(cp.getTipoCodigo(), contador, 2);
            tConceptos.setValueAt(cp.getCodigo(), contador, 3);
            tConceptos.setValueAt(cp.getDescripcion(), contador, 4);
            tConceptos.setValueAt(cp.getTieneIgv(), contador, 5);
            tConceptos.setValueAt(cp.getPorcentajeIgv(), contador, 6);
            tConceptos.setValueAt(cp.getCargo(), contador, 7);
            tConceptos.setValueAt(cp.getAbono(), contador, 8);
            tConceptos.setValueAt(cp.getEstado(), contador, 9);
            if (cp.getMostrarWeb() != null) {
                tConceptos.setValueAt(cp.getMostrarWeb(), contador, 10);
            } else {
                tConceptos.setValueAt("NO", contador, 10);
            }
            contador++;
        }

    }


    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        if (evt.getKeyCode() == 10) {
            this.buscarConceptoPagoDetalle();
        }
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Thread queryThread = new Thread() {
            public void run() {
                pbConceptoPagoDetalle.setIndeterminate(true);
                pbConceptoPagoDetalle.setStringPainted(true);
                pbConceptoPagoDetalle.setString("BUSCANDO CONCEPTO DE PAGO, POR FAVOR ESPERE");
                pbConceptoPagoDetalle.setValue(1000);
                pbConceptoPagoDetalle.repaint();
                buscarConceptoPagoDetalle();
                pbConceptoPagoDetalle.setString("BUSQUEDA FINALIZADA");
                pbConceptoPagoDetalle.setStringPainted(false);
                pbConceptoPagoDetalle.setIndeterminate(false);
            }
        };
        queryThread.start();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoConceptoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoConceptoPagoActionPerformed
        txtCodigo.setEditable(true);
        txtCodigoPresupuesto.setEditable(true);
        txtTipoCodigo.setEditable(true);
        txtCargo.setEditable(true);
        txtAbono.setEditable(true);
        txtObservacion.setEditable(true);
        cbIgv.setEnabled(true);
        txtPorcentaje.setEditable(true);
        txtDescripcion.setEditable(true);
        txtCodigo.setFocusable(true);
        txtCodigo.requestFocus();
        txtCodigo.setText("");
        txtCodigoPresupuesto.setText("");
        txtTipoCodigo.setText("");
        txtCargo.setText("");
        txtAbono.setText("");
//        txtIGV.setText("");
        txtPorcentaje.setText("");
        txtPorcentajeDetraccion.setText("");
        cbCodigoDetraccion.setSelectedIndex(0);
        txtObservacion.setText("");
        txtDescripcion.setText("");
        btnGuardar.setEnabled(true);
        SeguridadBO sBO = SeguridadBO.getInstance();
        if (sBO.getUsuario().getRolUsuario().equals("USUARIO")) {
            btnGuardar.setEnabled(false);
        }
        this.conceptoPago = new ConceptoPagoDetalle();
    }//GEN-LAST:event_btnNuevoConceptoPagoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!txtCodigo.getText().isEmpty() && !txtTipoCodigo.getText().isEmpty()
                && !txtCargo.getText().isEmpty() && !txtAbono.getText().isEmpty()
                //                && !txtObservacion.getText().isEmpty() 
                && !txtDescripcion.getText().isEmpty()) //&& !txtIGV.getText().isEmpty() && !txtPorcentaje.getText().isEmpty()
        {
            if (txtCodigo.getText().length() != 4) {
                JOptionPane.showMessageDialog(this,
                        "El Código debe tener 4 digitos", "ERROR",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (txtCodigoPresupuesto.getText().length() > 10) {
                JOptionPane.showMessageDialog(this,
                        "El Código no debe tener más de 10 digitos", "ERROR",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (txtCodigoPresupuesto.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Debe poner un Código de Presupuesto", "ERROR",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (txtTipoCodigo.getText().length() != 2) {
                JOptionPane.showMessageDialog(this,
                        "El Tipo de Código debe tener 2 digitos", "ERROR",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                this.conceptoPago.setCodigo(txtCodigo.getText());
                this.conceptoPago.setCodigoPresupuesto(txtCodigoPresupuesto.getText());
                this.conceptoPago.setTipoCodigo(txtTipoCodigo.getText());
                this.conceptoPago.setCargo(txtCargo.getText());
                this.conceptoPago.setAbono(txtAbono.getText());
                this.conceptoPago.setTipoAfectacion((TipoAfectacion) cbTipoAfectacion.getSelectedItem());
                this.conceptoPago.setMostrarWeb(cbMostrarWeb.getSelectedItem().toString());
                if (cbIgv.getSelectedItem().toString().equals("SI")) {
                    this.conceptoPago.setTieneIgv("S");
                } else {
                    this.conceptoPago.setTieneIgv("N");
                }
                if (!txtPorcentaje.getText().isEmpty()) {
                    this.conceptoPago.setPorcentajeIgv(Double.parseDouble(txtPorcentaje.getText()));
                } else {
                    this.conceptoPago.setPorcentajeIgv(0.0);
                }
                if (!txtPorcentajeDetraccion.getText().isEmpty()) {
                    this.conceptoPago.setPorcentajeDetraccion(Double.parseDouble(txtPorcentajeDetraccion.getText()));
                } else {
                    this.conceptoPago.setPorcentajeDetraccion(0.0);
                }
                if (cbEstado.getSelectedItem().toString().equals("HABILITADO")) {
                    this.conceptoPago.setEstado("H");
                } else {
                    this.conceptoPago.setEstado("I");
                }
                this.conceptoPago.setObservacion(txtObservacion.getText());
                this.conceptoPago.setDescripcion(txtDescripcion.getText());
                CodigoBienServicioDetraccion codigoBienServicioDetraccion = (CodigoBienServicioDetraccion) cbCodigoDetraccion.getSelectedItem();
                this.conceptoPago.setCodigoBienServicioDetraccion(null);
                if (codigoBienServicioDetraccion.getId() > 0) {
                    if (this.conceptoPago.getPorcentajeDetraccion() <= 0) {
                        JOptionPane.showMessageDialog(this, "Debe poner un porcentaje de detracción", "ERROR",
                                JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    this.conceptoPago.setCodigoBienServicioDetraccion(codigoBienServicioDetraccion);
                }
                ConceptoPagoDetalleBO conceptoPagoDetalle = ConceptoPagoDetalleBO.getInstance();
                if (this.conceptoPago.getIdConceptoPagoDetalle() == 0) {
                    conceptoPagoDetalle.GuardarConceptoPagoDetalle(this.conceptoPago);
                    JOptionPane.showMessageDialog(this, "Se inserto el Concepto de Pago Correctamente", "OK",
                            JOptionPane.INFORMATION_MESSAGE);
                } else {
                    conceptoPagoDetalle.ActualizarConceptoPagoDetalle(this.conceptoPago);
                    JOptionPane.showMessageDialog(this, "Se actualizo el Concepto de Pago Correctamente", "OK",
                            JOptionPane.INFORMATION_MESSAGE);
                }
                txtCodigo.setEditable(false);
                txtCodigoPresupuesto.setEditable(false);
                txtTipoCodigo.setEditable(false);
                txtCargo.setEditable(false);
                txtAbono.setEditable(false);
                cbIgv.setEnabled(false);
                txtPorcentaje.setEditable(false);
                txtObservacion.setEditable(false);
                txtDescripcion.setEditable(false);
                txtCodigo.setText("");
                txtCodigoPresupuesto.setText("");
                txtTipoCodigo.setText("");
                txtCargo.setText("");
                txtAbono.setText("");
                txtPorcentaje.setText("");
                txtObservacion.setText("");
                txtDescripcion.setText("");
                txtPorcentajeDetraccion.setText("");
                cbCodigoDetraccion.setSelectedIndex(0);
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            JOptionPane.showMessageDialog(this, "Por favor llene todos los Campos", "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tConceptosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tConceptosMouseClicked
        if (evt.getClickCount() == 2) {
            int fila = tConceptos.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tConceptos.getModel();
            ConceptoPagoDetalle cpd = (ConceptoPagoDetalle) model.getValueAt(fila, 0);
            this.conceptoPago = cpd;
            String tipoCodigo = String.valueOf(model.getValueAt(fila, 2));
            String codigo = String.valueOf(model.getValueAt(fila, 3));
            ConceptoPagoDetalleBO conceptoPagoDetalle = ConceptoPagoDetalleBO.getInstance();
            conceptoPago = conceptoPagoDetalle.ObtenerConceptoPagoDetalle1(tipoCodigo + codigo);
            txtCodigo.setText(conceptoPago.getCodigo());
            txtCodigoPresupuesto.setText(conceptoPago.getCodigoPresupuesto());
            txtTipoCodigo.setText(conceptoPago.getTipoCodigo());
            txtCargo.setText(conceptoPago.getCargo());
            txtAbono.setText(conceptoPago.getAbono());
            if (conceptoPago.getTieneIgv() != null) {
                if (conceptoPago.getTieneIgv().equals("S")) {
                    cbIgv.setSelectedItem("SI");
                } else {
                    cbIgv.setSelectedItem("NO");
                }
            }
            if (conceptoPago.getMostrarWeb() != null) {
                cbMostrarWeb.setSelectedItem(conceptoPago.getMostrarWeb());
            } else {
                cbMostrarWeb.setSelectedItem("NO");
            }
            if (this.conceptoPago.getTipoAfectacion() != null) {
                SeguridadBO sBO = SeguridadBO.getInstance();
                TipoAfectacion tAfectacion = (TipoAfectacion) sBO.CargarObjeto("TipoAfectacion", this.conceptoPago.getTipoAfectacion().getId());
                this.conceptoPago.setTipoAfectacion(tAfectacion);
                TipoTributo tTributo = (TipoTributo) sBO.CargarObjeto("TipoTributo", this.conceptoPago.getTipoAfectacion().getTipoTributo().getId());
                this.conceptoPago.getTipoAfectacion().setTipoTributo(tTributo);
                for (int i = 0; i < cbTipoTributo.getItemCount(); i++) {
                    TipoTributo tt = ((TipoTributo) cbTipoTributo.getItemAt(i));
                    if (tt.getId() == this.conceptoPago.getTipoAfectacion().getTipoTributo().getId()) {
                        cbTipoTributo.setSelectedItem(tt);
                        for (int j = 0; j < cbTipoAfectacion.getItemCount(); j++) {
                            TipoAfectacion t = ((TipoAfectacion) cbTipoAfectacion.getItemAt(j));
                            if (t.getId() == this.conceptoPago.getTipoAfectacion().getId()) {
                                cbTipoAfectacion.setSelectedItem(t);
                                break;
                            }
                        }
                    }
                }
            }
            cbCodigoDetraccion.setSelectedIndex(0);
            if (this.conceptoPago.getCodigoBienServicioDetraccion() != null) {
                SeguridadBO sBO = SeguridadBO.getInstance();
                CodigoBienServicioDetraccion codigoBienServicioDetraccion = (CodigoBienServicioDetraccion) sBO.CargarObjeto("CodigoBienServicioDetraccion", this.conceptoPago.getCodigoBienServicioDetraccion().getId());
                this.conceptoPago.setCodigoBienServicioDetraccion(codigoBienServicioDetraccion);
                for (int i = 0; i < cbCodigoDetraccion.getItemCount(); i++) {
                    CodigoBienServicioDetraccion tt = ((CodigoBienServicioDetraccion) cbCodigoDetraccion.getItemAt(i));
                    if (tt.getId() == this.conceptoPago.getCodigoBienServicioDetraccion().getId()) {
                        cbCodigoDetraccion.setSelectedItem(tt);
                    }
                }
            }
            if (this.conceptoPago.getEstado() != null) {
                if (this.conceptoPago.getEstado().equals("H")) {
                    cbEstado.setSelectedItem("HABILITADO");
                } else {
                    cbEstado.setSelectedItem("INHABILITADO");
                }
            } else {
                cbEstado.setSelectedItem("INHABILITADO");
            }
            txtPorcentaje.setText(conceptoPago.getPorcentajeIgv().toString());
            txtPorcentajeDetraccion.setText(!Objects.isNull(conceptoPago.getPorcentajeDetraccion()) ? conceptoPago.getPorcentajeDetraccion().toString() : "0.0");
            txtObservacion.setText(conceptoPago.getObservacion());
            txtDescripcion.setText(conceptoPago.getDescripcion());
            txtCodigo.setEditable(true);
            txtCodigoPresupuesto.setEditable(true);
            txtTipoCodigo.setEditable(true);
            txtCargo.setEditable(true);
            txtAbono.setEditable(true);
            cbIgv.setEditable(true);
            txtPorcentaje.setEditable(true);
            txtObservacion.setEditable(true);
            txtDescripcion.setEditable(true);
            cbIgv.setEnabled(true);
            btnGuardar.setEnabled(true);
            SeguridadBO sBO = SeguridadBO.getInstance();
            if (sBO.getUsuario().getRolUsuario().equals("USUARIO")) {
                btnGuardar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tConceptosMouseClicked

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (!txtCodigo.getText().isEmpty()) {
                txtTipoCodigo.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this,
                        "DEBE PONER EL CÓDIGO",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtCodigoKeyPressed


    private void txtDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (!txtDescripcion.getText().isEmpty()) {
                btnGuardar.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this,
                        "DEBE PONER LA DESCRIPCIÓN",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtDescripcionKeyPressed

    private void txtTipoCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoCodigoKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (!txtTipoCodigo.getText().isEmpty()) {
                txtCargo.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this,
                        "DEBE PONER EL TIPO DE CÓDIGO",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtTipoCodigoKeyPressed

    private void txtTipoCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoCodigoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTipoCodigoKeyTyped

    private void txtPorcentajeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentajeKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (!txtPorcentaje.getText().isEmpty()) {
                txtDescripcion.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this,
                        "DEBE PONER EL PORCENTAJE",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtPorcentajeKeyPressed

    private void txtCargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCargoKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (!txtCargo.getText().isEmpty()) {
                txtAbono.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this,
                        "DEBE PONER EL CARGO",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtCargoKeyPressed

    private void txtAbonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAbonoKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (!txtAbono.getText().isEmpty()) {
                cbIgv.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this,
                        "DEBE PONER EL ABONO",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtAbonoKeyPressed

    private void cbTipoTributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoTributoActionPerformed
        cbTipoAfectacion.removeAllItems();
        TipoTributoBO ttBO = TipoTributoBO.getInstance();
        List<TipoAfectacion> lA = ttBO.ObtenerAfectaciones(((TipoTributo) cbTipoTributo.getSelectedItem()).getId());
        for (TipoAfectacion tt : lA) {
            cbTipoAfectacion.addItem(tt);
        }
    }//GEN-LAST:event_cbTipoTributoActionPerformed

    private void txtCodigoPresupuestoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPresupuestoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPresupuestoKeyPressed

    private void txtCodigoPresupuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPresupuestoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPresupuestoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevoConceptoPago;
    private javax.swing.JComboBox cbCodigoDetraccion;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox cbFiltro;
    private javax.swing.JComboBox<String> cbIgv;
    private javax.swing.JComboBox<String> cbMostrarWeb;
    private javax.swing.JComboBox cbTipoAfectacion;
    private javax.swing.JComboBox cbTipoTributo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar pbConceptoPagoDetalle;
    private javax.swing.JTable tConceptos;
    private javax.swing.JTextField txtAbono;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoPresupuesto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextField txtPorcentaje;
    private javax.swing.JTextField txtPorcentajeDetraccion;
    private javax.swing.JTextField txtTipoCodigo;
    // End of variables declaration//GEN-END:variables
}
