/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.administracion;

import caja.bo.CongresoBO;
import caja.frm.caja.frmCargando;
import caja.frm.frmPrincipal;
import caja.mapeo.entidades.Congreso;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import units.DatePicker;

/**
 *
 * @author user
 */
public class frmCongreso extends javax.swing.JInternalFrame {

    private Congreso congreso;

    /**
     * Creates new form frmPersona
     */
    public frmCongreso() {
        initComponents();
//        txtFechaEnvio.setText("1900-01-01");
        txtFechaCongreso.setText("1900-01-01");
//        txtFechaRecepcion.setText("1900-01-01");
        this.congreso = new Congreso();

        TableColumn columna = tOficio.getColumn("NRO");
        columna.setPreferredWidth(40);
        columna.setMinWidth(40);
        columna.setMaxWidth(40);
        columna = tOficio.getColumn("FECHA");
        columna.setPreferredWidth(100);
        columna.setMinWidth(100);
        columna.setMaxWidth(100);
//        columna = tOficio.getColumn("CUI");
//        columna.setPreferredWidth(70);
//        columna.setMinWidth(70);
//        columna.setMaxWidth(70);
//        columna = tOficio.getColumn("FEC. NAC.");
//        columna.setPreferredWidth(70);
//        columna.setMinWidth(70);
//        columna.setMaxWidth(70);
//        columna = tOficio.getColumn("SEXO");
//        columna.setPreferredWidth(50);
//        columna.setMinWidth(50);
//        columna.setMaxWidth(50);
        columna = tOficio.getColumn("CONGRESOOBJ");
        columna.setPreferredWidth(0);
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tOficio = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreCongreso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnFechaOficio = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        txtFechaCongreso = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("CONGRESO");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/icono.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel1.setText("NOMBRE:");

        tOficio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO", "CONGRESO", "FECHA", "CONGRESOOBJ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tOficio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tOficioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tOficio);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/nuevoOficio.png"))); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/buscar5.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS CONGRESO"));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("NOMBRE:");

        txtNombreCongreso.setEditable(false);
        txtNombreCongreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreCongresoKeyTyped(evt);
            }
        });

        jLabel8.setText("FECHA:");

        btnFechaOficio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/calendario.png"))); // NOI18N
        btnFechaOficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaOficioActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/Guardar2.png"))); // NOI18N
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/Editar Trabajador 1.png"))); // NOI18N
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        txtFechaCongreso.setEditable(false);
        txtFechaCongreso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreCongreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaCongreso, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechaOficio)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtNombreCongreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txtFechaCongreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFechaOficio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar)
                    .addComponent(btnGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFechaOficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaOficioActionPerformed
        DatePicker dtp = new DatePicker(this);
        if (!dtp.setPickedDate().isEmpty()) {
            txtFechaCongreso.setText(dtp.setPickedDate());
        }
    }//GEN-LAST:event_btnFechaOficioActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed


        if (!txtNombreCongreso.getText().isEmpty() && !txtFechaCongreso.getText().isEmpty()) {
//            if (txtNroOficio.getText().length() != 8) {
//                JOptionPane.showMessageDialog(this,
//                        "El DNI debe tener 8 digitos",
//                        "ERROR",
//                        JOptionPane.ERROR_MESSAGE);
//                return;
//            }
            this.congreso.setNombre(txtNombreCongreso.getText());

            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            try {
                this.congreso.setFecha(format.parse(txtFechaCongreso.getText()));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this,
                        "OCURRIO UN PROBLEMA CON LA FECHA",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            CongresoBO cBO = CongresoBO.getInstance();
            if (this.congreso.getId() == 0) {
                boolean seGuardo = cBO.GuardarCongreso(this.congreso);
                if (seGuardo) {
                    JOptionPane.showMessageDialog(this,
                            "SE GUARDÓ LOS DATOS",
                            "OK",
                            JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "NO SE PUDO GUARDAR LOS DATOS",
                            "ERROR",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                boolean seGuardo = cBO.ActualizarCongreso(this.congreso);
                if (seGuardo) {
                    JOptionPane.showMessageDialog(this,
                            "SE ACTUALIZÓ LOS DATOS",
                            "OK",
                            JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "NO SE PUDO ACTUALIZAR LOS DATOS",
                            "ERROR",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            txtNombreCongreso.setEditable(false);
            txtFechaCongreso.setEditable(false);
            btnFechaOficio.setEnabled(false);
            btnGuardar.setEnabled(false);
            btnEditar.setEnabled(false);
            btnFechaOficio.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Por favor llene todos los Campos",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        this.congreso = new Congreso();
        txtNombreCongreso.setEditable(true);
//        txtFechaCongreso.setEditable(true);
        btnFechaOficio.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnFechaOficio.setEnabled(true);

        txtNombreCongreso.setText("");
        txtFechaCongreso.setText("1900-01-01");
        txtNombreCongreso.setFocusable(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNombreCongresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCongresoKeyTyped
//        if (txtNombreCongreso.getText().length() == 8) {
//            evt.consume();
//        } else {
//            char c = evt.getKeyChar();
//            if (!Character.isDigit(c)) {
//                getToolkit().beep();
//                evt.consume();
//            }
//        }
    }//GEN-LAST:event_txtNombreCongresoKeyTyped

    private void buscarOficio() {
        CongresoBO oBO = CongresoBO.getInstance();
//        List<Oficio> listado = oBO.BuscarOficio(title, SOMEBITS);
        List<Congreso> listado = oBO.ObtenerTodasCongresos();
        DefaultTableModel modelo = (DefaultTableModel) tOficio.getModel();
        modelo.setRowCount(0);
        int contador = 0;
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        for (Congreso o : listado) {
            modelo.setNumRows(contador);
            modelo.addRow(new Object[contador]);
            tOficio.setValueAt(contador + 1, contador, 0);
            tOficio.setValueAt(o.getNombre(), contador, 1);
            tOficio.setValueAt(format.format(o.getFecha()), contador, 2);
            tOficio.setValueAt(o, contador, 3);
            contador++;
        }
        txtNombreCongreso.setText("");
        txtFechaCongreso.setText("1900-01-01");
        txtNombreCongreso.setEditable(false);
        txtFechaCongreso.setEditable(false);
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        frmPrincipal fPrin = (frmPrincipal) this.getParent().getParent().getParent().getParent().getParent();
        Thread queryThread = new Thread() {
            public void run() {
                frmCargando fCargando = new frmCargando();
                fPrin.AgregarFormulario(fCargando);
                int x = (fPrin.getWidth() - fCargando.getWidth()) / 2;
                int y = (fPrin.getHeight() - fCargando.getHeight()) / 2;
                fCargando.setLocation(x, y);
                fCargando.setVisible(true);
                fCargando.toFront();
                buscarOficio();
                fCargando.dispose();
            }
        };
        queryThread.start();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tOficioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tOficioMouseClicked
        try {
            if (evt.getClickCount() == 2) {
                int fila = tOficio.getSelectedRow();
                DefaultTableModel model = (DefaultTableModel) tOficio.getModel();
                Congreso c = (Congreso) model.getValueAt(fila, 3);
                this.congreso = c;
                txtNombreCongreso.setText(c.getNombre());
                SimpleDateFormat formatoDeFecha = new SimpleDateFormat("yyyy-MM-dd");
                if (c.getFecha() != null) {
                    txtFechaCongreso.setText(formatoDeFecha.format(c.getFecha()));
                } else {
                    txtFechaCongreso.setText("1900-01-01");
                }
                txtNombreCongreso.setEditable(false);
                txtFechaCongreso.setEditable(false);
                btnFechaOficio.setEnabled(false);
                btnGuardar.setEnabled(false);
                btnEditar.setEnabled(true);
                btnFechaOficio.setEnabled(false);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tOficioMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (this.congreso.getId() != 0) {
            txtNombreCongreso.setEditable(true);
            txtFechaCongreso.setEditable(true);
            btnFechaOficio.setEnabled(true);
            btnGuardar.setEnabled(true);
            btnEditar.setEnabled(false);
            btnFechaOficio.setEnabled(true);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

//    public void agregarAutoridad(Oficio o) {
//        this.oficio = o;
//        txtDniAutoridad.setText(this.oficio.getPersona().getNroDocIdentidad());
//        txtNombreAutoridad.setText(this.oficio.getPersona().getApePat() + " " + this.oficio.getPersona().getApeMat() + " " + this.oficio.getPersona().getNombres());
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFechaOficio;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tOficio;
    private javax.swing.JFormattedTextField txtFechaCongreso;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtNombreCongreso;
    // End of variables declaration//GEN-END:variables
}
