/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.administracion;

import caja.bo.TipoDocIdentidadBO;
import caja.bo.soloMayusculas;
import caja.mapeo.entidades.TipoDocIdentidad;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author juan carlos
 */
public class frmTipoDocIdentidad extends javax.swing.JInternalFrame {

    private TipoDocIdentidad tipoDocIdentidad;
    
    /**
     * Creates new form frmTipoDocIdentidad
     */
    public frmTipoDocIdentidad() {
        initComponents();
        
        TableColumn columna = tIdentidad.getColumn("NRO");
        columna.setPreferredWidth(20);
        columna = tIdentidad.getColumn("ID");
        columna.setPreferredWidth(0);
        columna.setMaxWidth(0);
        columna.setMinWidth(0);
        columna = tIdentidad.getColumn("NOMBRE");
        columna.setPreferredWidth(50);
        columna = tIdentidad.getColumn("CODIGO");
        columna.setPreferredWidth(20);
        columna = tIdentidad.getColumn("DESCRIPCION");
        columna.setPreferredWidth(200);
        
        
        txtCodigo.setEditable(false);
        txtNombre.setEditable(false);
        txtNombre.setDocument(new soloMayusculas());
        txtDescripcion.setEditable(false);
        txtDescripcion.setDocument(new soloMayusculas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        cbFiltro = new javax.swing.JComboBox();
        btnBuscar = new javax.swing.JButton();
        btnNuevoDocumento = new javax.swing.JButton();
        pbTipoDocIdentidad = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tIdentidad = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Formulario de Documentos de Identidad");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ADMINISTRACIÓN DE DOCUMENTOS DE IDENTIDAD");

        jLabel2.setText("Búsqueda:");

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "POR NOMBRE", "POR CODIGO", "POR DESCRIPCION" }));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevoDocumento.setText("Nuevo Documento");
        btnNuevoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoDocumentoActionPerformed(evt);
            }
        });

        tIdentidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NRO", "NOMBRE", "CODIGO", "DESCRIPCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tIdentidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tIdentidadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tIdentidad);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Documento de Identidad"));

        jLabel3.setText("CÓDIGO:");

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        jLabel4.setText("NOMBRE:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        jLabel5.setText("DESCRIPCIÓN:");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pbTipoDocIdentidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(39, 39, 39)
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnBuscar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(btnNuevoDocumento))
                    .addComponent(jScrollPane1))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnNuevoDocumento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pbTipoDocIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void buscarTipoDocumetoIdentidad() {

        txtCodigo.setEditable(false);
        txtNombre.setEditable(false);
        txtDescripcion.setEditable(false);
    
        
        int tipoBusqueda = 0;
        if (cbFiltro.getSelectedItem() == "POR NOMBRE") {
            tipoBusqueda = 1;
        } else if (cbFiltro.getSelectedItem() == "POR CODIGO") {
            tipoBusqueda = 2;
        } else if (cbFiltro.getSelectedItem() == "POR DESCRIPCION") 
        {   tipoBusqueda = 3;
        }
        
        TipoDocIdentidadBO tdi = TipoDocIdentidadBO.getInstance();
        List<TipoDocIdentidad> l = tdi.BuscarTipoDocumntoIdentidad(txtBusqueda.getText(), tipoBusqueda);
        DefaultTableModel modelo = (DefaultTableModel) tIdentidad.getModel();
        modelo = (DefaultTableModel) tIdentidad.getModel();
        modelo.setRowCount(l.size());
        int contador = 0;
        for (TipoDocIdentidad di : l) {
            modelo.setNumRows(contador);
            modelo.addRow(new Object[contador]);
            tIdentidad.setValueAt(di.getIdTipoDocIdentidad(), contador, 0);
            tIdentidad.setValueAt(contador + 1, contador, 1);
            tIdentidad.setValueAt(di.getNombre(), contador, 2);
            //tIdentidad.setValueAt(di.getCodigoDocIde(), contador, 3);
            tIdentidad.setValueAt(di.getDescripcion(), contador, 4);
            contador++;
        }
          
    }
    
    
    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        if (evt.getKeyCode() == 10) {
            this.buscarTipoDocumetoIdentidad();
        }
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Thread queryThread = new Thread() {
            public void run() 
            {
                
                pbTipoDocIdentidad.setIndeterminate(true);
                pbTipoDocIdentidad.setStringPainted(true);
                pbTipoDocIdentidad.setString("BUSCANDO TIPO DOCUMENTO IDENTIDAD, POR FAVOR ESPERE");
                pbTipoDocIdentidad.setValue(1000);
                pbTipoDocIdentidad.repaint();
                buscarTipoDocumetoIdentidad();
                pbTipoDocIdentidad.setString("BUSQUEDA FINALIZADA");
                pbTipoDocIdentidad.setStringPainted(false);
                pbTipoDocIdentidad.setIndeterminate(false);

            }
        };
        queryThread.start();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoDocumentoActionPerformed
        txtCodigo.setEditable(true);
        txtNombre.setEditable(true);
        txtDescripcion.setEditable(true);
        txtCodigo.setFocusable(true);
        txtCodigo.requestFocus();
        
        
        txtCodigo.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
    }//GEN-LAST:event_btnNuevoDocumentoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!txtCodigo.getText().isEmpty() && !txtNombre.getText().isEmpty())
                //&& !txtDescripcion.getText().isEmpty()) 
                
        {
            if (txtCodigo.getText().length() != 2) {
                JOptionPane.showMessageDialog(this,
                        "El Código debe tener 2 digitos", "ERROR",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            try {
                TipoDocIdentidad tdi = new TipoDocIdentidad();
                //tdi.setCodigoDocIde(txtCodigo.getText());
                tdi.setNombre(txtNombre.getText());
                tdi.setDescripcion(txtDescripcion.getText());
                
                
                TipoDocIdentidadBO tipoDocIdentidad = TipoDocIdentidadBO.getInstance();
                tipoDocIdentidad.GuardarTipoDocumntoIdentidad(tdi, txtCodigo.getText());
               

                txtCodigo.setEditable(false);
                txtNombre.setEditable(false);
                txtDescripcion.setEditable(false);
                
                
                txtCodigo.setText("");
                txtNombre.setText("");
                txtDescripcion.setText("");
                
                JOptionPane.showMessageDialog(this, "Se insertó el Tipo de Documento de Identidad Correctamente", "OK",
                        JOptionPane.INFORMATION_MESSAGE);

            } 
        catch (Exception e) {
                e.printStackTrace();
            }

        } 
        else {
            JOptionPane.showMessageDialog(this, "Por favor llene todos los Campos", "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tIdentidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tIdentidadMouseClicked
        if (evt.getClickCount() == 2) {
            
            btnGuardar.setEnabled(false);
            
            int fila = tIdentidad.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tIdentidad.getModel();
            String codigo = String.valueOf(model.getValueAt(fila, 3));
            
            TipoDocIdentidadBO tipoDocIde = TipoDocIdentidadBO.getInstance();
            tipoDocIdentidad = tipoDocIde.ObtenerTipoDocumntoIdentidad(codigo);
            
            
            
            
            //txtCodigo.setText(tipoDocIdentidad.getCodigoDocIde());
            txtNombre.setText(tipoDocIdentidad.getNombre());
            txtDescripcion.setText(tipoDocIdentidad.getDescripcion());
            
            txtCodigo.setEditable(true);
            txtNombre.setEditable(true);
            txtDescripcion.setEditable(true);
            
        }
    }//GEN-LAST:event_tIdentidadMouseClicked

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == false) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (!txtCodigo.getText().isEmpty() && !txtNombre.getText().isEmpty())
                //&& !txtDescripcion.getText().isEmpty()) 
                
        {
            int fila = tIdentidad.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tIdentidad.getModel();
            String codigo = String.valueOf(model.getValueAt(fila, 1));
            
            try
            {
                if(tipoDocIdentidad == null){
                    JOptionPane.showMessageDialog(this, "Debes seleccionar un Tipo de documento de Identidad", "OK",
                            JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                
                //tipoDocIdentidad.setCodigoDocIde(txtCodigo.getText());
                tipoDocIdentidad.setNombre(txtNombre.getText());
                tipoDocIdentidad.setDescripcion(txtDescripcion.getText());
                
            
                TipoDocIdentidadBO tipoDocIde = TipoDocIdentidadBO.getInstance();
                tipoDocIde.ActualizarTipoDocumntoIdentidad(tipoDocIdentidad, txtCodigo.getText());
                
                
                txtCodigo.setEditable(false);
                txtNombre.setEditable(false);
                txtDescripcion.setEditable(false);
                

                txtCodigo.setText("");
                txtNombre.setText("");
                txtDescripcion.setText("");
                
            
                JOptionPane.showMessageDialog(this, "Se actualizó el Tipo de Documento de Identidad Correctamente", "OK",
                        JOptionPane.INFORMATION_MESSAGE);
            
            }
            
            catch(Exception e)
            {
                e.printStackTrace();
            }
         

        }
        else{
            JOptionPane.showMessageDialog(this, "No se pudo actualizar el Tipo de Documento de Pago", "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (!txtCodigo.getText().isEmpty()) {
                txtNombre.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this,
                        "DEBE INGRESAR EL CÓDIGO",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (!txtNombre.getText().isEmpty()) {
                txtDescripcion.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this,
                        "DEBE INGRESAR EL NOMBRE",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevoDocumento;
    private javax.swing.JComboBox cbFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar pbTipoDocIdentidad;
    private javax.swing.JTable tIdentidad;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
