/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caja.frm.administracion;

import caja.bo.CobradorBO;
import caja.bo.ManagerBO;
import caja.bo.PersonaBO;
import caja.bo.SeguridadBO;
import caja.bo.soloMayusculas;
import caja.mapeo.entidades.Cliente;
import caja.mapeo.entidades.Cobrador;
import caja.mapeo.entidades.UbigeoDepartamento;
import caja.mapeo.entidades.UbigeoDistrito;
import caja.mapeo.entidades.UbigeoProvincia;
import caja.mapeo.entidades.Universidad;
import java.awt.event.KeyEvent;
//import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
//import units.DatePicker;
//import units.DatePicker;

/**
 *
 * @author juan carlos
 */
public class frmUniversidad extends javax.swing.JInternalFrame {

//    private Cliente cliActual;
    private Universidad universidad = new Universidad();

    private List<UbigeoDepartamento> lUbigeoDepartamento;
    List<UbigeoProvincia> lUbigeoProvincias;
    List<UbigeoDistrito> lUbigeoDistrito;
    private boolean accesoGuardar = true;

    /**
     * Creates new form frmCobrador
     */
    public frmUniversidad() {
        initComponents();
        TableColumn columna = tUniversidad.getColumn("NRO");
        columna.setMinWidth(40);
        columna.setMaxWidth(40);
        columna.setPreferredWidth(40);
        columna = tUniversidad.getColumn("OBJ");
        columna.setMinWidth(0);
        columna.setMaxWidth(0);
        columna.setPreferredWidth(0);
        txtNombre.setEditable(false);
        CobradorBO cobBO = CobradorBO.getInstance();
        SeguridadBO sBO = SeguridadBO.getInstance();
        if (sBO.getUsuario().getRolUsuario().equals("SA")) {
            accesoGuardar = true;
        } else {
            if (sBO.getUsuario().getRolUsuario().equals("A")) {
                accesoGuardar = true;
            } else {
                accesoGuardar = false;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnIngresarCobrador = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tUniversidad = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        pbCobrador = new javax.swing.JProgressBar();
        btnGuardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Formulario de Universidad");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/icono.png"))); // NOI18N
        setName(""); // NOI18N

        jLabel1.setText("Búsqueda:");

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/buscar_mini1.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnIngresarCobrador.setText("Ingresar");
        btnIngresarCobrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarCobradorActionPerformed(evt);
            }
        });

        tUniversidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OBJ", "NRO", "NOMBRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tUniversidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tUniversidadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tUniversidad);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel2.setText("NOMBRE:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja/images/Guardar2.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbCobrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIngresarCobrador))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnIngresarCobrador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarCobrador() {
        txtNombre.setEditable(false);
        String filtro = " u.nombre like '%" + txtNombre.getText().trim() + "%'";
        ManagerBO c = ManagerBO.getInstance();
        List<Universidad> l = c.ObtenerUniversidad_SegunFiltro(filtro);
        DefaultTableModel model = (DefaultTableModel) tUniversidad.getModel();
        model = (DefaultTableModel) tUniversidad.getModel();
        model.setRowCount(l.size());
        int cont = 0;
        for (Universidad p : l) {
            model.setNumRows(cont);
            model.addRow(new Object[cont]);
            tUniversidad.setValueAt(p, cont, 0);
            tUniversidad.setValueAt(cont + 1, cont, 1);
            tUniversidad.setValueAt(p, cont, 2);
            cont++;
        }
    }


    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Thread queryThread = new Thread() {
            public void run() {
                pbCobrador.setIndeterminate(true);
                pbCobrador.setStringPainted(true);
                pbCobrador.setString("BUSCANDO COBRADOR, POR FAVOR ESPERE");
                pbCobrador.setValue(100);
                pbCobrador.repaint();
                buscarCobrador();
                pbCobrador.setString("BUSQUEDA FINALIZADA");
                pbCobrador.setStringPainted(false);
                pbCobrador.setIndeterminate(false);
            }
        };
        queryThread.start();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnIngresarCobradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarCobradorActionPerformed
        this.universidad = new Universidad();
        txtNombre.setEditable(true);
        txtNombre.setText("");
    }//GEN-LAST:event_btnIngresarCobradorActionPerformed

    private static boolean ValidarFecha(String fecha) {
        try {
            SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
            formatoFecha.setLenient(false);
            formatoFecha.parse(fecha);
        } catch (ParseException e) {
            return false;
        }
        return true;
    }


    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!txtNombre.getText().isEmpty()) {
            try {
                this.universidad.setNombre(txtNombre.getText().trim());
                ManagerBO cob = ManagerBO.getInstance();
                if (this.universidad.getId() == 0) {
                    this.universidad.setBorrado("1");
                    cob.GuardarObjeto(this.universidad);
                    JOptionPane.showMessageDialog(this, "Se guardó los datos ", "OK",
                            JOptionPane.INFORMATION_MESSAGE);
                } else {
                    cob.ActualizarObjeto(this.universidad);
                    JOptionPane.showMessageDialog(this, "Se actualizó los datos", "OK",
                            JOptionPane.INFORMATION_MESSAGE);
                }
                txtNombre.setEditable(false);
                txtNombre.setText("");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Debe llenar todos los Campos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tUniversidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tUniversidadMouseClicked
        if (evt.getClickCount() == 2) {
            int fila = tUniversidad.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tUniversidad.getModel();
            this.universidad = (Universidad) model.getValueAt(fila, 0);
            txtNombre.setText(this.universidad.getNombre());
            txtNombre.setEditable(true);
            if (this.accesoGuardar) {
                btnGuardar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tUniversidadMouseClicked

    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        if (evt.getKeyCode() == 10) {
            this.buscarCobrador();
        }
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            PersonaBO pBO = PersonaBO.getInstance();
//            Cliente persona = pBO.ObtenerPersona(txtNombre.getText());
//            if (persona != null) {
//                txtNombres.setText(persona.getPapePat() + ' ' + persona.getPapeMat() + ' ' + persona.getPnombre());
//                this.cobrador.setCliente(persona);
//            } else {
//                txtNombres.setText("");
//                this.cobrador.setCliente(null);
//            }
//        }
    }//GEN-LAST:event_txtNombreKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIngresarCobrador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar pbCobrador;
    private javax.swing.JTable tUniversidad;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
